### ISSUE TITLE
Create shortcut links (.lnk) to launch specific connections

### ISSUE THREAD

**Issue by majkinetor** [1Remote/1Remote#188]
**Is your enhancement related to a problem? Please describe.**

Sometimes you want to work with some group of connections with higher focus. It would be great if one could mark a group with tag(s) and then launch connections via single click or hotkey that Windows shortcuts support.

**Describe the solution you'd like**

Provide a CLI params to PRM for this. Then sugar coat it with feature that creates shortcuts interactively.

For example:

`> premotem -open "#my-project #db"`

would start all connections that satisfy this filter. Otherwise, single connection could be run via connection id (as name is not unique):

`> premotem -open `23`

With CLI arguments such as those creating desktop shortcut manually or via app is trivial

**NOTE**: This is just an idea, CLI arguments should definitely be thought out more precisely.

**Comment by VShawn** [comment]
Since we have a launcher, I dont think a shortcut is needed.

and `start all connections that satisfy this filter` is overkill for personal usage.

**Comment by majkinetor** [comment]
Yeah, you are right.

**Comment by majkinetor** [comment]
I think we ditched this one prematurely as experience is not the same.
Its especially relevant for remote apps as it provides seamless integration with OS. Also you have another mechanism to organize stuff if you have large collection - pin them on taskbar, or create desktop shortcuts. 

Its also easy to implement. 

I will reopen this and put it in Limbo, so I don't forget about it. No need for you to implement it, I will do it myself eventually.

**Comment by VShawn** [comment]
I make quick investigation about how to start a Windows Store APP by .lnk with parameters.

Get nothing useful.

**Comment by majkinetor** [comment]
Its not end of the world no to support that case... It could always be fixed later anyway.

**Comment by VShawn** [comment]
yeah I'm just looking into the feasibility

**Comment by majkinetor** [comment]
OMG, store apps suck so bad:

https://docs.unity3d.com/560/Documentation/Manual/windowsstore-commandlinearguments.html
https://www.reddit.com/r/Windows10/comments/es97px/pass_commandline_arguments_to_windows_store_game/

**Comment by majkinetor** [comment]
I wouldn't waste time on that. We could have some workaround for this, but it all involves too much work.

**Comment by Kikilluh** [comment]
Hi,

I was about to create an issue and I found this one where you were talking about it.  
I think it might be nice to be able to select multiple connections in the launcher, maybe with ctrl-click or shitft-click. What do you think ?

So per example we could select a tag, and then launch all the connections at once.

**Comment by VShawn** [comment]
Hi @Kikilluh 

actually you can select a tag and open them all here.

![image](https://user-images.githubusercontent.com/10143738/193971622-7523c5b8-0419-4f5d-aeff-66feb39c6628.png)

BTW I dont want involved mouse operation in the launcher, the task of our launcher is `open a new session by keyboard only`

**Comment by VShawn** [comment]
close since we have #427
