### ISSUE TITLE
Changes for new application name

### ISSUE THREAD

**Issue by VShawn** [1Remote/1Remote#238]
Based on internal discussion we settled currently on:

- OneRemote 
One Remote Access Manager to Rule Them All 
Shortcut: 1RAM, 1RM

_Originally posted by @majkinetor in https://github.com/VShawn/PRemoteM/issues/214#issuecomment-1126957496_

Tasks:

1. [x] Move to organization
1. [x] Repository name
1. [x] Link in the wiki
1. [x] Solution name including the name in the code.
1. [x] Repository link in the chocolatey package metadata
2. [x] Chocolatey package name
1. [x] Environment variables in protocols `PRM_` prefix to `_ORM` or `RM_`
3. [x] Executable name (1Remote.exe)
4. [x] Executable Icon 
5. [x] Windows UI titlebar 
6. [x] About UI 
7. [x] Names in the docs.

**Comment by majkinetor** [comment]
You already changed it.

**Comment by majkinetor** [comment]
I added all other necessary tasks.

**Comment by VShawn** [comment]
Time to create a Logo for 1RM.

This may not be a good idea:

![logo400](https://user-images.githubusercontent.com/10143738/216757700-9ad477a6-58fd-4f3e-a4fd-d0dfd0f8778a.png)

**Comment by majkinetor** [comment]
Closing this, all things are done. Waiting for choco package to be approved.
