### ISSUE TITLE
When connection is minimized, launching connections do not restore the window

### ISSUE THREAD

**Issue by majkinetor** [1Remote/1Remote#291]
I often keep 1RM minimized. When I use launcher or list, it opens new connection in the background and doesn't restore it.

The experienced behavior is that literary nothing happens and you see there is a connection there when you manually restore it.

Also, with luancher sometimes it even skips creating connection (can't reproduce it all the time) and with lister it seems this never happens.

**Comment by VShawn** [comment]
Okey I fixed it.

[PRemoteM.0.7.1.6.beta.1-x64.zip](https://github.com/1Remote/PRemoteM/files/9630636/PRemoteM.0.7.1.6.beta.1-x64.zip)

**Comment by majkinetor** [comment]
Looks like regression or it never worked: https://github.com/1Remote/1Remote/discussions/381

**Comment by VShawn** [comment]
fix it again with 2e336244680ea4dc9c03c0f38aecf857bf2e4c56
