### ISSUE TITLE
Connections are restricted to a single credentials  -

### ISSUE THREAD

**Issue by FlamingoDaBird** [1Remote/1Remote#301]
**Is your feature request related to a problem? Please describe.**
I have to create double rdp connections to the same server if I'd like to login as another user.

**Describe the solution you'd like**
Would be nice if there was an option to save different credentials and connect them somehow to the same RDP connection.

**Describe alternatives you've considered**
Or perhaps an alternate connection, say if you press shift then initiate your connection the alternative connection would be selected.
Or if it could as if several credentials are linked, not sure about the best way to go about it,
Other applications utilize a folder hierarchy to inherit several configurations. Would be nice if there's a simple way to go about it.  :)  

**Additional context**
Thank you for an excellent application <3

**Comment by majkinetor** [comment]
> Other applications utilize a folder hierarchy to inherit several configurations. 

You can use tags for that here. Once gruped, you can bulk edit them.

Your case is trivially solved bu copying the connection(s), and mass changing user. This can be simplifed by grouping connections with tags. 

Without this, one possiblity would be the option to add multiple usernames and passwords to the same connection (not just RDP) and to make one default. To launch connection with different credentials then, we could have something like SHIFT + click to offer a list of users before connecting. This is not tirival to implement as you need to support bulk editing array of users.

**Comment by FlamingoDaBird** [comment]
Hi majkineator
I was considering doing it that way :) but I have lots of connections so that would result in a lot of duplicates, and I like to keep the list to a minimum of connections if possible.

That's why was wondering if it was a possibility or if there's any interest on implementing a credentials object of some kind. 

I do love the bulk edit feature, a life saver!

Thank you

**Comment by majkinetor** [comment]
I think this should go to discussion and voting. One usecase doesn't justify implementation in my opinion.

**Comment by VShawn** [comment]
discissed in https://github.com/1Remote/PRemoteM/issues/103. 

This ticket made a point to adjust the ip and port by a 3rd part app before PRM start a connection. Too hardcore IMO


For me, I created 2 sissons for this, one is used in my office via local network, one is for work from home via public address.

![image](https://user-images.githubusercontent.com/10143738/195328433-b3f07312-1a0a-465c-ab32-ab9f29837b09.png)

**Comment by majkinetor** [comment]
Its not the same request IMO. He wanted to do this outside, while we talk about internal support here for multiple values on specific fields.  Also, this request is about credential only, which is way more frequent then dynamic ports or ips. 

With multiple credentials it seems trivial to enable workflow that would let you choose credential when you start a connection with modifier (lets say shift key or middle mouse click). Like I said, bulk edit is main problem here, but it could be worked out - a) change only first credential b) replace entire list with new one c) compare by username and act like bulk tag editing.

**Comment by majkinetor** [comment]
If you want us to try this out @VShawn, I can try to design this feature the way it would require low amount of code changes.

**Comment by majkinetor** [comment]
Here is the first idea:

![image](https://user-images.githubusercontent.com/85767/195403341-40e0f407-df1e-4681-a2f0-b707da590256.png)

1. Starting a connection should now use default cred
2. Mod + start connection shows menu of credentials to choose before it is started
    - Also new menu item: `Connect with credentials`
3. Bulk edit simple:  Allow only bulk editing default credential, so its the same as before
4. Bulk edit complex:
    - In bulk edit mode show combo option:  `edit mode: [ set | add | remove ]`
    - if mode is "Set" , and list is not empty, all connections will have the same list of creds (default)
    - if mode is "Add", all connections will keep existing list of creds, and get new ones from the add list
    - if mode is "Remove" all connections will loose listed connections (only name is used, password is ignored)
    - only one mode can be used, but you can use all if you bulk edit multiple times
    - just as with tags, you can find common conections and add them if the mode is Set, plus one `<different options>`  
   
Bulk edit complex version is something that we should have with tags too (#184).

**Comment by VShawn** [comment]
Sounds easy to achieve, but I think we need also import 'alternative address'.

![image](https://user-images.githubusercontent.com/10143738/195473940-f3486ad5-cf83-4482-a390-ca33fce79979.png)

**Comment by VShawn** [comment]
How is everything going? Can we get some reference from other APPs? I think it would be a great challenge on credentials buck manage if we add alternative credentials featurs. And there must be someone ask for a comment credential share to several sessions.

**Comment by majkinetor** [comment]
What part of above idea is problematic? We can go with bulk edit simple for starts if that is troubling you.

**Comment by VShawn** [comment]
finally done after so many changes.

![image](https://user-images.githubusercontent.com/10143738/221332888-7c30f6c4-7a51-464e-a784-2b8ceb70bd58.png)

**Comment by VShawn** [comment]
It works with RDP only for now.
