### ISSUE TITLE
Follow system theme

### ISSUE THREAD

**Issue by majkinetor** [1Remote/1Remote#302]
**Is your enhancement related to a problem? Please describe.**
We have an option to choose theme. Among them are dark and light themes.

**Describe the solution you'd like**
There should be an checkbox in theme configuration to follow system theme.  If choosen, app automatically determines if its going to use light or dark theme based on OS settings.

**Comment by VShawn** [comment]
not sure how to tigger by system theme changed event in a win32 app. 

More investigation is needed.

**Comment by majkinetor** [comment]
Its a registry key. See [this module](https://github.com/leandrocrs/windows-theme).

Since PRM is mostly run constantly, it needs to check this on activation and switch theme. Its usuall that apps do this on the startup, but in this case it would be meaningless.

**Comment by majkinetor** [comment]
FYI

https://learn.microsoft.com/en-us/windows/apps/desktop/modernize/apply-windows-themes

**Comment by VShawn** [comment]
I now believe that we should not spend time on this ticket as it does not provide core functionality and cannot enhance UX significantly
