### ISSUE TITLE
Launcher keyshortcut not working when main Window in secondary screen

### ISSUE THREAD

**Issue by DaWy** [1Remote/1Remote#342]
OS: Windows 11 Pro
Version: 21H2
PRemoteM: 0.7.2.1

When having 2 displays, If I move the main PremoteM connection window to the secondary screen, and my mouse is in the primary screen, the launcher shortcut doesn't work.

When connection window is in the primary screen, the shortcut works on both screens, very weird. 

So, a table detailing the cases with ALT+M issue:

Extended mode. Mouse on PRIMARY, Window on SECONDARY: Not Working
Extended mode. Mouse on SECONDARY, Window on SECONDARY: Working
Extended mode. Mouse on PRIMARY, Window on PRIMARY: Working
Extended mode: Mouse on SECONDARY, Window on PRIMARY: Working

**Comment by VShawn** [comment]
very weird...

actually I have 3 displays.

Extended mode. Mouse on PRIMARY, Window on SECONDARY: Working for me
![image](https://user-images.githubusercontent.com/10143738/212448327-a4964cfc-2c76-4089-9c98-66a16ec6867f.png)

**Comment by VShawn** [comment]
could you please check you log, and find out if there was some log shows `Call shortcut to invoke launcher Visibility = Hidden` after it not working?

![image](https://user-images.githubusercontent.com/10143738/212459071-a71e4b86-64e8-4a9c-bb09-c12989a5d399.png)

log files located here if you are testing on microsoft store version:
![image](https://user-images.githubusercontent.com/10143738/212459089-ab4f452a-7f42-44fe-bd7c-8ee8ac95f82a.png)

if you find ``Call shortcut to invoke launcher Visibility = Hidden` then ture out `alt + m` was recognized.

**Comment by DaWy** [comment]
Sorry for the delay, been busy these days. I found the culprit. When Windows screen scale is changed in to any value more than 100%, it happens the behaviour I posted in the issue.

Only happens when:

**Mouse on PRIMARY screen, Window on SECONDARY screen*

If I change back the window scale to 100% on the secondary screen, the launcher works again as expected. 

About the logs... When doing the shortcut to show the launcher with the Window scale on secondary at 100%, log show this:

`[T:001][09:45:09.576]	`Debug`		Call shortcut to invoke launcher Visibility = Hidden`

Doing this on Windows Scale at 150%, log show the exact same... I think problem is not launcher not showing, problem is launcher position is based on default scale. I noticed when changing screen scale, launcher windows moves to the right. Heres an example:

Scale settings:
- Primary: 100%
- Secondary: 150%

Launcher windows not showing...

Scale settings:
- Primary: 100%
- Secondary: 125%

![image](https://user-images.githubusercontent.com/1610889/220294779-fd9bf01d-af51-40c7-913c-a4f96ca51e24.png)

Scale settings:
- Primary: 100%
- Secondary: 100%

![image](https://user-images.githubusercontent.com/1610889/220295177-a2acb814-4cc9-4627-892a-c969558131da.png)

**Comment by DaWy** [comment]
Ok I "temporaly" solved this. This only happens when changing scale while PRemote is running. If app is closed and opened again, issue is gone.

So seems  that the issue is app is not "refreshing" in some kind Windows scale info, so when scale is changed while app is running, it does not update the position and scale of the launcher Window.

**Comment by VShawn** [comment]
Yes I discovered this `scale` issue at the beginning of the project, and it seemed to be unfixable at the time. I need to confirm it again.
