### ISSUE TITLE
Not all title buttons are visible always

### ISSUE THREAD

**Issue by majkinetor** [1Remote/1Remote#346]
Sometimes this happens to me:

![image](https://user-images.githubusercontent.com/85767/213917103-67f00a03-2926-4a7b-aa0c-dcd00a1a2eb9.png)

There is no restore button so I can't maximize it correctly and part of the 1RM is behind the taskbar.

When I restart connection it is there:

![image](https://user-images.githubusercontent.com/85767/213917186-e9a3fc06-8f79-42be-af79-55a944cc45df.png)

I am not sure when this happens, will try to catch it.

**Comment by VShawn** [comment]
is that a RDP session?

**Comment by majkinetor** [comment]
Yeah, RDP.

**Comment by majkinetor** [comment]
I didn't see this for some time. Maybe it is resolved. I will close this for now and if it appears again reopen it.
