### ISSUE TITLE
RDP multi monitor, when going to windowed, acts as if only 1 screen

### ISSUE THREAD

**Issue by fancellu** [1Remote/1Remote#355]
Using MS remote desktop, when I go back to windowed mode (ctrl-alt-pause), I get a window with scrollbars, so I can see both screens in the window, and scroll between them. 

Using Remote1, I can only see one screen, and all windows are then moved to that screen, so if I restore full screen again, 
one screen is empty and all the windows have moved to the other screen.

**Comment by VShawn** [comment]
Yes this is how I design it. 

It's my personal taste.

I using 3 monitors every day. And IMO the behavior of MSTSC is meaningless. Because I can hardly handle the large large desk in a small window and move the content carefully with the scroll bar...

**Comment by fancellu** [comment]
Ok, I prefer the MS remote desktop behaviour, especially with respect to not moving all my windows to one screen. 

I was looking for an alternative, as MS remote desktop moves/resizes its window each time I go from full screen, slowly creeping across the screen, then flying to the next screen. Annoying, but at least it lets me see both screens and doesn't rearrange my windows. Oh well.

**Comment by VShawn** [comment]
Ahh I see what you want.

Well you can change your RDP settings like this:

![image](https://user-images.githubusercontent.com/10143738/218613909-0a38cd85-14aa-4586-91d1-5f36eb299e04.png)


It will works like this:

![image](https://user-images.githubusercontent.com/10143738/218613955-5e808b79-b1a8-4af2-bce9-1a05d22766ab.png)

Now it won't rearrange your desk :)

If you prefer a scrollbar, then set `resolution` to `fix`

![image](https://user-images.githubusercontent.com/10143738/218614528-44dbc838-a987-45ba-9fba-ca267d79a71a.png)

**Comment by VShawn** [comment]
Ahh I see what you want.

Well you can change your RDP settings like this:

![image](https://user-images.githubusercontent.com/10143738/218613909-0a38cd85-14aa-4586-91d1-5f36eb299e04.png)


It will works like this:

![image](https://user-images.githubusercontent.com/10143738/218613955-5e808b79-b1a8-4af2-bce9-1a05d22766ab.png)

Now it won't rearrange your desk :)

If you prefer a scrollbar, then set `resolution` to `fix`

![image](https://user-images.githubusercontent.com/10143738/218614528-44dbc838-a987-45ba-9fba-ca267d79a71a.png)

**Comment by fancellu** [comment]
That's exactly what I wanted. Thanks. And it doesn't creep across the screen each time I go back to windowed mode, like MS RDT.

BTW, I note that ctrl-alt-pause takes it out of full screen, just like MS RDT, but in windowed mode, it doesn't listen to 
ctrl-alt-pause to take it back to full screen.

**Comment by fancellu** [comment]
Ah, ok, still does "odd stuff".

i.e. in window, maximized to left screen with scrollbars.
I make it go full screen, so I see both screens on remote box, all is fine, then I click restore, and the window flies to the right screen

I'd expect it to go back to the screen it was on, i.e. the left

**Comment by VShawn** [comment]
Sorry for the delay, but I’m busy and not working on 1Remote for a few days.

But I can't get how it works from your description, can you give a simple screen recording?

**Comment by VShawn** [comment]
here is my test. I recording on the primary screen. 

As you can see, I move a explorer to the second window, and click restore, and the explorer window is gone.

![1](https://user-images.githubusercontent.com/10143738/221065689-acb67978-acbf-4fac-8ac2-59fed0e9fbfb.gif)

**Comment by VShawn** [comment]
close dead ticket
