### ISSUE TITLE
Unable to change the position of each remote session.

### ISSUE THREAD

**Issue by xieyuqiang** [1Remote/1Remote#356]
It would be much convenient, if the position can be changed by mouse dragging or other operation. 
Now the sequence of remote sessions is determined by their creating times, it's not always the best sequence.

**Comment by VShawn** [comment]
sorry for delay, but I’m busy and not working on 1Remote for a few days.

about this ticket you can make conversation here: https://github.com/1Remote/1Remote/discussions/349

then I will close the ticket.
