### ISSUE TITLE
连接windows 11(22h2 22621.1344)远程桌面，图标是黑框

### ISSUE THREAD

**Issue by lzplzp001** [1Remote/1Remote#372]
0.7.2.6版本连接windows 11(22h2 22621.1344)远程桌面，任务栏图标是黑色的框，不能显示正确的图标。使用windows自带的mstsc.exe，连接是正常的。

**Comment by VShawn** [comment]
能否来个截图，看看是怎么个黑框？

另外是否可以尝试调节一下 performance 到 high

![image](https://user-images.githubusercontent.com/10143738/224595893-9e32e2ec-216f-4127-9f82-7a74d14349e6.png)

**Comment by VShawn** [comment]
![image](https://user-images.githubusercontent.com/10143738/224597051-17550f3f-1625-4193-9f84-0961adb01dbf.png)

因为我本地测试无法复现你所描述的bug
