### ISSUE TITLE
索引超出了数组界限

### ISSUE THREAD

**Issue by Jv0id** [1Remote/1Remote#373]
vnc连接时报错：索引超出了数组界限

**Comment by VShawn** [comment]
能够提供更具体的错误日志么？VNC控件不是我写的，我不熟悉，有日志能够更快定位问题。

**Comment by Jv0id** [comment]
只有以下的日志：
[T:018][15:28:55.572]	`Warning`		[(Execute:0)]	CloseEmptyWindows: 1 Empty Host closed

> 能够提供更具体的错误日志么？VNC控件不是我写的，我不熟悉，有日志能够更快定位问题。

**Comment by Jv0id** [comment]
<img width="610" alt="image" src="https://user-images.githubusercontent.com/35218851/224641557-7f6e0d4a-c649-41ac-bfff-2173a8401e6b.png">

**Comment by VShawn** [comment]
感觉我维护不动这个问题，VncSharp 已经在 2014 年归档了，现在属于没人维护的状态。建议你配置 TightVNC 作为 VNC 的客户端。

配置方法参考：https://github.com/1Remote/1Remote/wiki/%5BProtocol%5D--Protocol-Runners#简体中文

![image](https://user-images.githubusercontent.com/10143738/224656548-f96c4afd-4104-4a10-aa35-71cef399f552.png)

**Comment by Jv0id** [comment]
ok，我晚上试一下。谢谢啦。
