### ISSUE TITLE
checking the return value of the "before script"

### ISSUE THREAD

**Issue by VShawn** [1Remote/1Remote#376]
It's easy to return an exit code from ps1/cmd/bat files. Use "Exit 1" in powershell or "exit /b 1" in batch files. 0 means success, everything else means failure.

Having said this, it would make sense to implement checking the return value of the "before script" in PRemoteM at some rainy day in the future. Till then I can live with the current behavior. 😉

_Originally posted by @MWinhard in https://github.com/1Remote/1Remote/discussions/363#discussioncomment-5228034_

**Comment by MWinhard** [comment]
Just installed version 0.7.2.7 and changed the connect script to fail. The RDP connection is not trying to connect. Instead a MessageBox is shown. Works as expected. 😁

However, in version 0.7.2.7 the script after disconnected is complaining.

![2023-03-16 10_01_48-Script after disconnected](https://user-images.githubusercontent.com/111646687/225566916-65d61fb9-e534-44bf-a4b3-f6b01cba1391.png)

That's my script after disconnected:

`"C:\Program Files\OpenVPN\bin\openvpn-gui.exe" --command disconnect myconnection.ovpn`

It worked flawlessly in version 0.7.2.3. I'm starting a second instance of openvpn-gui.exe just to send a message to the running instance. The second instance returns within a split second.

**Comment by MWinhard** [comment]
The script after disconnected doesn't complain if I wrap it in a *.cmd file.

Perhaps you're waiting for the wrong process id to exit? The process name is not unique in my case.

**Comment by MWinhard** [comment]
The script after disconnected complains, too, if I wrap it in a *.cmd file.

**Comment by VShawn** [comment]
oh I make a mistake on one line.

this one would help

https://github.com/1Remote/1Remote/releases/download/0.7.2.7/PRemoteM-0.7.2.7.zip

**Comment by MWinhard** [comment]
The script after disconnect doesn't complain anymore. 😁
Thank you very much.

-------- Original Message --------
Subject: Re: [1Remote/1Remote] checking the return value of the "before 
script" (Issue #376)
From: VShawn ***@***.***>
To: 1Remote/1Remote ***@***.***>
Cc: Markus Winhard ***@***.***>, Mention ***@***.***>
Date: Donnerstag, 16.03.2023 10:47:42
