### ISSUE TITLE
Alert the breaking change once  breaking update is detected.

### ISSUE THREAD

**Issue by VShawn** [1Remote/1Remote#383]
Since there are many changes between PRM and 1Remote, the APP upgrade may bring some Breaking Changes, so it is necessary to remind the user that the next version of the upgrade may bring risks. 

I'm going to add a simple pop window to alert users to backup data once the next version is `Breaking Change`.

**Comment by majkinetor** [comment]
On the other hand, its prw 1.0 release which means exactly that...

**Comment by 121119834** [comment]
Good
