### ISSUE TITLE
Submenu "Sorting" does disappear when leaving settings area

### ISSUE THREAD

**Issue by Nefti-sama** [1Remote/1Remote#389]
**Describe the bug**
Not every, but most of the time the Sorting submenu does disappear when mousepointer is leaving the area of the settings (?) menu (the one with the 3 lines)

**To Reproduce**
1. Click on the three lines
2. Go to Sorting
3. Try to click on some sort method

**Expected behavior**
Sorting submenu stays there for at least 500ms to allow the mouse to move over the gap

**Screenshots**
![image](https://user-images.githubusercontent.com/65944159/229640035-6b51b71c-fb77-4a33-a6e1-20d6ce68f73d.png)

**Desktop (please complete the following information):**
 - OS: Win10 21H2
 - 1Remote-1.0.0.0-beta.01-net6-x64-nightly-20230403-cbd0db

**Additional context**

**Comment by VShawn** [comment]
thx for your report

This bug is caused by a gap between two menus. When the mouse moves over the gap, it leaves the menu area causing the menu to hide. 

I have always used windowed mode, where there is no gap between menus, so I never noticed this issue.
