### ISSUE TITLE
Tag-filter cant be removed if tag of connection is changed

### ISSUE THREAD

**Issue by Nefti-sama** [1Remote/1Remote#390]
**Describe the bug**
When the connections are filtered by a tag and the tag is changed to another one, the filter on top cannot be removed if there is no connection left using the tag.

**To Reproduce**
1. Create a new connection with a new tag "test1"
2. Left-click on the tag "test1" to filter
3. Edit the connection, remove tag "test1" and add the tag "test2"
4. Try to remove the filter "test1"

**Expected behavior**
It should be possible to remove the filter even if there are no more connections using it (or it should remove itself)

**Screenshots**
![image](https://user-images.githubusercontent.com/65944159/229640811-150aeb25-9518-4b39-b26f-9fef66cdb04e.png)

**Desktop (please complete the following information):**
  - OS: Win10 21H2
  - 1Remote-1.0.0.0-beta.01-net6-x64-nightly-20230403-cbd0db

**Comment by VShawn** [comment]
reproduce successfully :)

![image](https://user-images.githubusercontent.com/10143738/229754530-f514b346-6321-462a-babb-fbca6d5b220c.png)
