### ISSUE TITLE
Drives appears on remote desktop even when "Drives" is unchecked in RDP settings.

### ISSUE THREAD

**Issue by karnasw** [1Remote/1Remote#394]
Drives appears on remote desktop even when "Drives" is unchecked in RDP settings.

1. Go to RDP
2. Click on connection settings
3. Scroll down to Advantage
4. Uncheck Drives

Drives shouldn't appear in RDP, but they appear.

 - OS: Windows 11 Pro 22H2 22621.1555
 - 1Remote-1.0.0.0-beta.01-net6-x64-nightly-20230409-f9c775

**Comment by VShawn** [comment]
bug confirm THX for the report
