### ISSUE TITLE
Intrusive MySql Server connection error

### ISSUE THREAD

**Issue by majkinetor** [1Remote/1Remote#395]
**Describe the bug**

When remote database becomes unavailable for any reason, there is this error:

![image](https://user-images.githubusercontent.com/85767/234472411-9ff5cbc1-d759-47b3-b24a-502309ffb0c0.png)

**Expected behavior**
There should be no intrusion, especially since the error can resolve on its own. It seems that 1RM needs some form of internal Log viewer wiht marker for ciritical errors, warnings, currently erroring etc.

**Additional context**
This happens when VPN goes down to my company. Also when Windows is locked, after some time, I am always greeted with this message. VPN log is unremarkable but that is besides the point, the error is intrusive and constant.

**Comment by VShawn** [comment]
I only checked the MySQL connection once during startup, but it should be changed to check the connection before any data operation. Additionally, I was lazy and applied the SQLite connection program to MySQL, which now I realize is problematic. I need to redesign this part.

**Comment by majkinetor** [comment]
> I only checked the MySQL connection once during startup

Wait what ?
This message happens while 1RM is already running in the background. When do you check for remote changes? On activation?

BTW, I think this should be redesigned to support "storing backend" so that new backends could be added later: PostgreSQL, JSON file or whatever. It makes sense that this should be apstracted via some nice Interface.

**Comment by majkinetor** [comment]
>  "storing backend"

How the connections are stored and where :) 

So we can add more store backend in the future, like git (great for team sharing without hassle of installing db) or simple JSON file or whatever. 

But OK, you say you already designed it that way...

**Comment by majkinetor** [comment]
OK, so we need then some internal log instead of intrusive popups? Or what are your thoughts?

**Comment by VShawn** [comment]
I've remove the alert so you will not get the popups when 1RM is running in the background.

**Comment by majkinetor** [comment]
Just an update. 

Today I don't see the remote database. 

<details><summary>details</summary> 

![image](https://user-images.githubusercontent.com/85767/235292866-a8283957-0562-4b17-93d6-474eba1af95c.png)
</details>


I went on Edit -> Test and it said Success, on the back, it blocked here:

<details><summary>details</summary>

![image](https://user-images.githubusercontent.com/85767/235292896-0e0b05f9-a138-457b-a855-2bfe16e47c90.png) </details>

**Comment by VShawn** [comment]
> Just an update. 
> 
> 
> 
> Today I don't see the remote database. 
> 
> 
> 
> <details><summary>details</summary> 
> 
> 
> 
> ![image](https://user-images.githubusercontent.com/85767/235292866-a8283957-0562-4b17-93d6-474eba1af95c.png)
> 
> </details>
> 
> 
> 
> 
> 
> I went on Edit -> Test and it said Success, on the back, it blocked here:
> 
> 
> 
> <details><summary>details</summary>
> 
> 
> 
> ![image](https://user-images.githubusercontent.com/85767/235292896-0e0b05f9-a138-457b-a855-2bfe16e47c90.png) </details>
> 
> 
> 
> On escape it goes back with it and ALT M stopped working
> 
> 
> 
> <details><summary>details</summary> 
> 
> 
> 
> ![image](https://user-images.githubusercontent.com/85767/235293239-45b176c8-1ed7-499d-9c16-1c95173a9485.png)
> 
> 
> 
> </details>
> 
> 

I think these were fixed after https://github.com/1Remote/1Remote/commit/930a8c04589794192bb4fa614be44ee59ed5666b

**Comment by VShawn** [comment]
![image](https://user-images.githubusercontent.com/10143738/235565197-879b5a12-b13e-4f66-9d32-4492da1246e1.png)

here is how 1RM works with db offline now. I think this ticket is donw, you can get the latest nighly build to try it.

**Comment by majkinetor** [comment]
I have a better proposition - UX lacks this way, as you never know when it will magically reapear, in 4 minutes and 59 seconds or in 1s.

1. PRM should always show remote db "section". If the remote database is unrechable, it should show do one of the following:
    2.  Hide all items in it and show 'Reconnect now'  button/option instead
    3. Or better, show all items, becuase the fact that db is not accessible doesn't mean connection is and since you have all the data in local cache it can still be used even without remote db
        4. In this case show "remote db section entry" with aditional option, like reconnect button
1. One can manually reconnecct at any time, but PRM will still try its own automatic reconnection periodically. 


![image](https://user-images.githubusercontent.com/85767/236241337-e28ad435-45ce-4b90-a5cf-c1329397422d.png)

**Comment by VShawn** [comment]
a reconnect button is what I was going to do next, thanks to your blueprint I will follow your approach now : )

**Comment by VShawn** [comment]
https://user-images.githubusercontent.com/10143738/236653315-411ef96e-1d06-4a44-b2b3-5e02b18ba4ef.mp4

I made the view, is that ok?

**Comment by majkinetor** [comment]
Yeah, it looks nice. 

With the large list you might not be able to see the group since it will be out of the view (which is what will happen all the time as nobody uses this who doesn't have a lot of them), did you make some UX on affected connections? At least edit's Save button should be disabled with adequate tooltip.

**Comment by VShawn** [comment]
> did you make some UX on affected connections

No not yet. The icon can be gray if database offline.

> At least edit's Save button should be disabled with adequate tooltip. 

sure thing

**Comment by VShawn** [comment]
https://user-images.githubusercontent.com/10143738/236819470-5db60368-3161-48de-afe8-2b139d067801.mp4

manually reconnect is work now

**Comment by majkinetor** [comment]
Looks good, but I wouldn't show reconnect if connection is OK, only if its not OK, because it seems iritating that some numbers are ticking and everything is fine.

**Comment by VShawn** [comment]
it still WIP now, i did not create the display style for it yet, ticking will be hidden then if it connected.

**Comment by VShawn** [comment]
I think most tasks of this ticket is done

check list:

[x] reconnect button
[x] tip fot next auto reconnect
[x] do not show tip for connected db
[x] tip globalization
[ ] gray the item in the dissconnected db? not sure for this, IMO Large grey block is ugly
[x] not allow edit items when db is dissconnected
[x] always show the group even there is 0 item in the db

https://github.com/1Remote/1Remote/assets/10143738/deba299d-4808-4434-b6f2-ce730d028e57

**Comment by majkinetor** [comment]
>  gray the item in the dissconnected db? not sure for this, IMO Large grey block is ugly

How come items are still available upon disconnection, based on our discussion on #400. 

But yes, large gray block is ugly. The problem is you may have a long list and database _is not pinned at the top while you scroll_ so as soon as it goes out of screen you don't see status any more. You don't see status in launcher too (if its available there). Maybe something else is less intrusive like italic font for connection ...

But OK, that can be done later, this is good enough for now, lets call it a day.

**Comment by majkinetor** [comment]
OK, not sure I understand your local cache problem then since it is already cached, just not in the accessible way :)

**Comment by VShawn** [comment]
I think the main difference between us is that I believe that user must connect to MySQL at list once before they can use the data stored there, while you believe that it should be possible to use cached data from MySQL even if a connection hasn't been established since startup. Is that correct?

**Comment by majkinetor** [comment]
I just noted that it could be possible that someone can send you the cached data, if that is what you mean. But anybody can do that NOW trivially easy:

1. Run new portable version of 1RM
2. Connect to remote database
3. Select all, copy to local database
4. Send your local database to anybody

3-5 minutes of work tops.

**Comment by majkinetor** [comment]
OK, bulk duplicate is not possible now (it probalby should be), but export is there. Its even faster. I just exported my company database within 5 seconds.

**Comment by majkinetor** [comment]
There is a problem with current UX, the dissapearing/appearing message moves other icons :) So if you want to hunt for invisible + you may have hard time doing that.

**Comment by VShawn** [comment]
>  I thought you should disable Save button within connection editor.This also makes it strange as you may not notice why it doesn't work. 

Form this point, disable save button directly is not a good choice, since user may not know why the button is disabled. I would like to add a disconnected icon asize save button and do not disabled it.

![image](https://github.com/1Remote/1Remote/assets/10143738/21f7790b-56ab-40bc-941a-c9324bfc4c92)

**Comment by VShawn** [comment]
> I scroll a bit and KnowIT is out of screen

You want a fix group header?

not sure for that, if the group header of the system's native control does not support fix on top, it may be necessary to completely customize a control. I have no enough experience in this aspect.

**Comment by majkinetor** [comment]
> You want a fix group header?

Anything to inform us there is disconnect really. Here are some options, and you see what is easiest for you

1. Name Italic <details><summary>details</summary> 
    ![image](https://github.com/1Remote/1Remote/assets/85767/0327d3a7-b110-4030-af45-e6f6f7dcc758) </details>
1. Name color <details><summary>details</summary> 
    ![image](https://github.com/1Remote/1Remote/assets/85767/b95895ce-4acd-4c4c-98c6-91f9abfde31b)</details>
1. Icon everywhere <details><summary>details</summary> 
![image](https://github.com/1Remote/1Remote/assets/85767/960b14a0-0ba0-4778-83b8-30544d96e589)
</details>

Option 2 seems with least intrusion, not sure how visible it is. 1. kinda looks bad? 3. Looks OK, maybe a bit spammy? Maybe some less intrusive icon or just unicode text: <details><summary>details</summary> ![image](https://github.com/1Remote/1Remote/assets/85767/931e403a-b1a8-4ff5-a36e-e0bff6bf23b2)</details>

**Comment by majkinetor** [comment]
I see you replaced checkbox on latest version:

![image](https://github.com/1Remote/1Remote/assets/85767/2d6671ec-3db9-4bd3-a2cd-9a5e9d5af265)

With Save icon we can consider this matter closed (although Launcher is left out but it was never a topic and I consider that minor hinderance)

**Comment by majkinetor** [comment]
Actually, after more tests, it still doesn't work correctly:

1. I disabled VPN and restarted the 1RM
2. Naturally, RAM is gone and with it my connections 👎 
3. 1RM started to count
4. After it refreshed, there were still no connections
5. I had to manually click the reconnect to show them 

![Animation](https://github.com/1Remote/1Remote/assets/85767/29089b03-1ba2-41f5-9f5a-93c98d5bfd37)

**Comment by VShawn** [comment]
> Naturally, RAM is gone and with it my connections 👎

I can not reproduce this maybe because I tested it by close MySQL since I don't have a VPN?

https://github.com/1Remote/1Remote/assets/10143738/e2651ef3-773f-4740-80b1-7fcc32c426b1



> After it refreshed, there were still no connections https://github.com/1Remote/1Remote/labels/bug

finally find it a UI bug, the counting down is 5min not 60s. I mistakenly set the UI to display seconds only, so it will automatically reconnect only after 5 timers of 60 seconds counting down have passed.

**Comment by VShawn** [comment]
Oh?  `Naturally, RAM is gone and with it my connections` is fix now ?

**Comment by VShawn** [comment]
Things are getting a bit strange. I didn't encounter the bug you mentioned while testing 1RM. I recorded a complete 5mi screen capture, which you can take a look. 

But manual connect button is not working on my end.

https://github.com/1Remote/1Remote/assets/10143738/1b5c6bf8-6143-4d23-a376-56eeb4a77e32



I think it may be due to VPN that I am unable to reproduce the bug. I tried simulating network disconnection by turning the MySQL service on and off, but I couldn't test the situation where the VPN client was opened like you because I don't have an available VPN.

**Comment by majkinetor** [comment]
You can't argue with the screenshot :) And it clearly was working before (talking about the icon).

**Comment by VShawn** [comment]
![image](https://github.com/1Remote/1Remote/assets/10143738/326a4c14-8c2c-429e-b053-d19676896a9b)

i think this is the reason.

**Comment by VShawn** [comment]
@majkinetor can you test it again? i shorten the reconect time to 60s to make it easier to test.

**Comment by majkinetor** [comment]
Sure, later when I come home. U should put timer setings in json config.

**Comment by majkinetor** [comment]
It works now, apart from connections gone when restarted, but you said you want it that way.

One thing seems buggy tho - it rechecks on 10s when OK, but on 60s when not ok

![image](https://github.com/1Remote/1Remote/assets/85767/541a80e0-4305-450a-bf1a-28855b9012e5)

**Comment by majkinetor** [comment]
Another thing is buggy in this version - clicking on database name doesnt always show/hide database as before. It works like this. 

1. Click once, it is hidden
2. Subsequent clicks do nothing _for some time_

**Comment by VShawn** [comment]
> One thing seems buggy tho - it rechecks on 10s when OK, but on 60s when not ok

That's 2 different settings, I will then make it configurable


> Another thing is buggy in this version - clicking on database name doesnt always show/hide database as before.

this is still WIP I found the expander dose not work after ordered by connection name desc, I accidentally pushed the code to Git while it half way done.

**Comment by majkinetor** [comment]
Sort doesn't influence it.

**Comment by VShawn** [comment]
> Sort doesn't influence it.

It does in previous version

![1](https://github.com/1Remote/1Remote/assets/10143738/db976cc8-ab84-4dcf-a8a5-9391eede3ebd)

> Its overkill to have 2 settings IMO.

You need to set a short time for checking data updates and a longer time for the database reconnection retry wait time. Trying to reconnect to the database every 10 seconds is overkill IMO

**Comment by majkinetor** [comment]
I didn't know the one is for data updates, I was thinking its also for availability. Yeah, that needs another timer.

> Anyway, these two settings can only be changed by eidt the json file at this moment.

And it should IMO stay that way, we don't need advanced options in the configuration. We could add a button to open json like for example vscode or SumatraPDF or windows terminal.
