### ISSUE TITLE
Setup repository branches

### ISSUE THREAD

**Issue by majkinetor** [1Remote/1Remote#409]
1. [x] Rename `1Remote_dev` to `main`
2. [x] Remove outdated branches
3. [x] Set default branch to `main` in GH General options
4. [x] Change any CI references to outdated branch, if they exist (Actions etc...)

---
Discussed in https://github.com/1Remote/1Remote/discussions/408

**Comment by VShawn** [comment]
I'm working on #395 now, and will handle this after #395 is closed

**Comment by VShawn** [comment]
it's done
