### ISSUE TITLE
Empty database after update

### ISSUE THREAD

**Issue by majkinetor** [1Remote/1Remote#411]
1. I took nightly archive
2. Turned off 1RM, copied the archive content over it, overwrite all
3. I started 1RM and empty database
    4. Database is shown in options as ./1remote.db
    5. I browse for database again 
    6. Now the full path is shown and it works.
    7. I go to global options again, and its exactly the same ./1remote.db path as before

**Comment by majkinetor** [comment]
This happened again but without installing:

1. 1 opened 1remotedb in Dbeaver to edit stuff by hand
1. 1RM didn't show edited changes (and it should as far as I remember, this was for sync) nor it shown that database is locked (wanted to test this latest feature)
1. After restart there was no db, I had to repeat above process again.

**Comment by VShawn** [comment]
This happened when 1RM start with minimize, still searching why this happen
