### ISSUE TITLE
Intrusive availability detection screens

### ISSUE THREAD

**Issue by majkinetor** [1Remote/1Remote#420]
Availability detection occupies center part of the screen, is on top, and there is no way to minimize it or terminate it once started. When troubleshooting server disconnection this leads to bad user experience that I just witnessed. Also there is popup at the end that you must OK.

Possible solutions:

- Not making it on top, or putting MUCH smaller window in the screen corner (next to tray for example) 
- Remove separate popup, make OK button integral part of the first window (and allow ESC)
- Or best, remove multiple popups and keep single one, add new availability tests to it and put it in the corner of the screen on top but allow it to be minimized

<details><summary>details</summary>

![image](https://github.com/1Remote/1Remote/assets/85767/6315bc5e-91fb-4afd-953a-0f0a0e6bb212)

Use this instead:

```
| Availability detection      x _ |
|        Server     Result
|    1. Server 1     error      [⟳]  (red color)
|    2. Server 2     ok         [⟳]   (green color)
|    3. Server 3     3...2...   [⟳]    (no color)
| Total 3, 1 ok 1 error 1 running

```

In single run mode this window should autoclose if test is OK (same as now) and stay open on error. In bulk mode it should not close automatically. 

This will go nicely with bulk testing we are plannning to do.
</details>

**Comment by VShawn** [comment]
You found the place where I was being lazy during development :)

**Comment by majkinetor** [comment]
> You found the place where I was being lazy during development :)

I always do 😄 , somehow I detect bugs in few seconds always.

> The point is, I don't want this popup to show in the taskbar, so the only way to remind people is to keep this window always on top. Otherwise, it might fall into background and no one would notice it.

Just keep a small toaster next to a tray, I think that would be OK even with _on top_ window. Here is more detailed mockup:

![image](https://github.com/1Remote/1Remote/assets/85767/2e8444da-b747-41b9-a838-d7a4f5dcc43d)


>  Perhaps adding the ability to drag the window (yes, I was being lazy here too LOL) could solve the problem

It should be on good spot to start with, user shouldn't generally mess with it. Tray is perfect option for that IMO and it should be small anyway, currently its too big

**Comment by VShawn** [comment]
![image](https://github.com/1Remote/1Remote/assets/10143738/20acf540-03b4-4ed9-b745-11bd066c90c3)

is this ok?

**Comment by majkinetor** [comment]
Some comments

- Numbers
For example in title - `Availability test (2.4)`. Means 2 OK, 4 ERR. We could add * if there are pending (2.4*).  If all are pending then we could show (*)
- I can't see on screenshot as there are no failed ones, but it will be failed icon X. I would add option when hovering it to show redo icon for that server.
- There is enough space to show connetion name, otherwise, it will be hard to know which connection is it. Alternativelly, clicking on server can focus connection in main window


![image](https://github.com/1Remote/1Remote/assets/85767/877811f8-0824-4534-834c-e7358766fa5d)

**Comment by VShawn** [comment]
> For example in title - Availability test    ok: 1  err: 2

this is none use here, this view is for available test before connection start, once any connect success, I will kill other ping tasks and close this pop and start connection, so user will not see any err connection.

I will take other comments, It may takes about two days to achieve all UI effects:)

**Comment by majkinetor** [comment]
You should never close this window if there is any error, in any case. 

> This design make sense when address manual selectior is implemented.

But user can still run tag or use multi connect in which case behavior should be the same - close it if all is good, leave it open otherwise.

**Comment by VShawn** [comment]
1. it make sense providing independent detection windows for each connection. This is just an automatic address switcher, not a address sniffer, If the connection is success, this window will automatically close within 1 second instead of requiring manual closing. Closing in 1 second means it cannot be used to display the ping status of the next connection.
2. I don't want import another window control here for this small feature. The current design is the simple: exit automatically on success, stay on failure. The design you provided is complex: on failure -> check if there is the same error message in the window -> if not, create a new one -> if yes, overwrite it; On success -> check if there are further ping requirements. If not, close window(or hide window?); if yes, wait for it.
3. yes minimize button just for hide the window while close button is for cancel ping task.
