### ISSUE TITLE
Virus detected (maybe false positive)

### ISSUE THREAD

**Issue by Wikiphil** [1Remote/1Remote#422]
**Describe the bug**
1Remote.exe is catched by Trend Micro EDR or Microsoft Defender

**To Reproduce**
Unzip the nightly build and start from the folder.

**Expected behavior**
Just starting the 

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Windows 11 Pro
 - 1Remote-1.0.0.0-beta.03-net6-x64-nightly-20230523-fe2b87

**Comment by Wikiphil** [comment]
Just to let you know, PRemoteM vers 0.7.2.8 doesn't have the same issue.

**Comment by majkinetor** [comment]
Its not maybe false positive, it is false positive. Exe is created by the GitHub CI/CD and it never touches our machines.

**Comment by Wikiphil** [comment]
When I start the EXE, it tries to access Explorer, may be that where the is catched.

**Comment by VShawn** [comment]
It does not make sense that accessing explorer will be treated as a virus. 

How should the program read configuration files from explorer in this case?

Note: 1Remote accesses explorer.exe directly only when the user needs to open Explorer. When the program starts, it only reads configuration and data from the file system.

![image](https://github.com/1Remote/1Remote/assets/10143738/f3f09f9f-06eb-4588-a4de-a17a558e7650)

**Comment by Wikiphil** [comment]
Sorry, not a Virus, it's reported by EDR. And then DCS erased the 1Remote.exe file.

![image](https://github.com/1Remote/1Remote/assets/84292480/3069afeb-45ca-4cc3-973f-d4cbee2f2327)

**Comment by majkinetor** [comment]
Closing this since there is nothing we can do
