### ISSUE TITLE
In mstsc mode, return to window mode in full screen, and the bottom of the window will become larger

### ISSUE THREAD

**Issue by iijang** [1Remote/1Remote#434]
**Describe the bug**
In mstsc mode, return to window mode in full screen, and the bottom of the window will become larger.

**To Reproduce**
1. Create a new rdp connection and configure it in mstsc mode
2. Full screen window after rdp connection
3. Cancel full screen and return to windowed mode
4. Repeat steps 2 and 3

**Expected behavior**
Every time you return to windowed mode, the bottom will get a little bigger, causing you to need to resize the window every time

**Comment by VShawn** [comment]
For better understanding, can you provide a screenshot?

**Comment by VShawn** [comment]
It turn out to be a bug of mstsc.exe. It reproduce when I start a connection from Mstsc UI.
