### ISSUE TITLE
App stuck when click the info button on RDP connectiuon bar on Win11

### ISSUE THREAD

**Issue by zhj9709** [1Remote/1Remote#437]
**Describe the bug**
Win 11上使用1Remote全屏后查看连接信息后软件卡住，几秒后软件自动关闭。

**To Reproduce**
1. 使用非mstsc模式
2. 全屏
3. 查看连接信息

**Expected behavior**
点击查看连接信息是与mstsc模式一样可以正常查看连接信息

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Win 11
 - 1Remote

**Comment by zhj9709** [comment]
补充一下，目前我在win10上测试没有这种情况，可能是因为win11上远程桌面版本较高，可以展开看到更多的信息
![image](https://github.com/1Remote/1Remote/assets/13991774/68566f42-aa4c-4c4d-b995-78f3f74f8ff0)

**Comment by VShawn** [comment]
maybe my Win11 is old, there's no further detail like yours when I clik the info button.

![image](https://github.com/1Remote/1Remote/assets/10143738/298be893-f2c2-4168-b71d-4376db3c070a)

I will ttest again after I update win11 to latest.

**Comment by VShawn** [comment]
似乎是由于最新版本 Win11 上点击信息按钮后，会对RDP的父窗口进行操作（可能只能操作WinForm而1Remote是WPF），导致父窗口崩溃。

目前没有找到确定的问题点和解决方案。

**Comment by VShawn** [comment]
目前证实使用 winform 作为 UI 框架启动 RDP 时，在win11 上点击信息按钮不会导致崩溃。

![image](https://github.com/1Remote/1Remote/assets/10143738/08fc3373-696d-4bbd-a2ac-8472e91e4f5f)

因此很有可能是 WPF 和 win11 在信息按钮上冲突，我准备先把 win11 上的信息按钮隐藏掉以避免程序的崩溃。

**Comment by VShawn** [comment]
I have currently disabled the information button for Win11, but I still haven't found the cause of the issue.

**Comment by VShawn** [comment]
This issue has made progress at https://github.com/1Remote/1Remote/issues/559.
