### ISSUE TITLE
Dynamic resolution function does not work with XRDP remote desktop environment.

### ISSUE THREAD

**Issue by MmDawN** [1Remote/1Remote#440]
**Describe the bug**
When using 1Remote to connect to the XRDP remote desktop ( Ubuntu 22.04 LTS with Gnome 42.5 and XRDP  0.9.17), no matter how to adjust the client window size, the dynamic resolution function does not work. However, when I use the Remote Desktop App in the Microsoft Store to connect this XRDP Remote Desktop, the Dynamic Resolution feature is available.

**To Reproduce**
1. Build a XRDP remote desktop environment
2. Connect it with 1Remote
3. Adjust the client window size

**Expected behavior**
I hope dynamic resolution function works with XRDP remote desktop environment.

**Screenshots**
![image](https://github.com/1Remote/1Remote/assets/40926229/0f0b9653-2e3f-4b9f-945c-200f9a41fa57)

**Desktop (please complete the following information):**
 - OS: Win 11 Pro 22H2
 - PRemoteM Version 1.0.0-beta.04

**Comment by VShawn** [comment]
THX for reporting, I realized this bug when testing #358 last week, and currently fix has not been found. As a workaround, you can connect to this server using the mstsc mode.

![image](https://github.com/1Remote/1Remote/assets/10143738/cb5f045c-66fd-4dfd-89d5-81e391e15800)

**Comment by VShawn** [comment]
Hi According to the results of my investigation

RDP on Ubuntu 22.04 may not support dynamic resolution, you have to edit the grub file to change the resolution.

https://askubuntu.com/questions/1431696/ubuntu-22-04-rdp-client-host-resolution-mismatch

https://www.youtube.com/watch?v=l8YSB9ewFLY
