### ISSUE TITLE
能不能给设置加一个取消按钮，每次看设置而不保存设置的时候，我都是直接退出软件，怕误保存，所以开发者可以采纳么？

### ISSUE THREAD

**Issue by hktkqwe123** [1Remote/1Remote#442]
能不能给设置加一个取消按钮，每次看设置而不保存设置的时候，我都是直接退出软件，怕误保存，所以开发者可以采纳么？

**Comment by VShawn** [comment]
事实上，这个保存按钮大多数时候并没有保存的作用，它仅仅是个返回按钮。

也就是除了runner以外的任意设置被修改后，直接就保存到配置文件了。
