### ISSUE TITLE
If icon is selected from local program, its too small

### ISSUE THREAD

**Issue by majkinetor** [1Remote/1Remote#444]
1. First (big) icon is when I go to Music Brainz Picard folder and created shortcut to Picard.exe
2. Second (small) icon is when I do the same from 1Remote using _Upload_ button in connection configuration and then I create desktop shortcut using latest option #439 

![image](https://github.com/1Remote/1Remote/assets/85767/2131ed46-7e79-4abd-8e38-7d4c2ab672b7)

Its also small in the list:

![image](https://github.com/1Remote/1Remote/assets/85767/1fc1e66f-f21b-4b38-b2cd-886668ad4b19)

**Comment by VShawn** [comment]
You gotta adjust the icon size yourself when uploading it. We can't decide the size of the icon for our user.


https://github.com/1Remote/1Remote/assets/10143738/535534cf-6503-44b2-8682-e339121b2b79


![image](https://github.com/1Remote/1Remote/assets/10143738/1961bbe3-b648-458b-8a1b-e4e89d8d1338)

**Comment by majkinetor** [comment]
That doesn't change the icon here on the desktop, only in the list:

![image](https://github.com/1Remote/1Remote/assets/85767/657a94c5-c69d-4030-9f2b-ea6823cb4b5c)

**Comment by VShawn** [comment]
Maybe caused by the icon cache not being updated. 

I have replaced the icon with the Win2019 icon, but the desktop shortcut still shows the previous icon.

![image](https://github.com/1Remote/1Remote/assets/10143738/d075b53c-c73b-4122-ad46-98a7fdfe348c)

**Comment by majkinetor** [comment]
The cache problem is certainly there, but that has nothing to do with 1RM, it happens with other apps too.

This is specific to 1RM, it initially shows icon that is smaller. Here I take random icons from Program Files that I never used before:

![Animation2](https://github.com/1Remote/1Remote/assets/85767/3a7d812b-746b-4107-87d8-af35f0d961c9)

**Comment by VShawn** [comment]
Then this is actually a bug in the icon selector, and I have been testing whether creating shortcuts has bug.

**Comment by VShawn** [comment]
I fixed it
