### ISSUE TITLE
can't exit options without saving

### ISSUE THREAD

**Issue by Gameniti** [1Remote/1Remote#446]
**Describe the bug**
When opening the options there is no way to exit them without saving or closing the window

**To Reproduce**
1. Go to the hamburger menu
2. Click on options
3. Try to exit options

**Expected behavior**
Some way to exit them without saving or closing the window. Something simple like 'cancel'.

**Desktop (please complete the following information):**
 - OS: Win10 Pro 22H2
 - PRemoteM Version 0.7.2.8

**Comment by VShawn** [comment]
In fact, the save button is a "placebo" that 1RM immediately saves the changes to the configuration file after you modify any setting. 

This design originates from Microsoft's system settings, where in Windows system settings, any modification is instantly saved and implemented.

**Comment by Gameniti** [comment]
That's bad design imo. Not the instant save thing but that there is no feedback.

If you want to keep this instant save style maybe make a small pop-up that says "saved" if you change some settings and change the "save" button to "close" - because that's what it currently does.

Otherwise, change it so that you don't instant-save the settings and only save it when you press the "save" button.

**Comment by VShawn** [comment]
well Thx for advice, and label "Save" has been changed to "Back" in 1Remote Version.

![image](https://github.com/1Remote/1Remote/assets/10143738/36cf9f47-a42c-445d-b041-63a1f2e20bdd)
