### ISSUE TITLE
打开第二个标签远程桌面，然后关闭第一个标签就没有响应了

### ISSUE THREAD

**Issue by aliciz** [1Remote/1Remote#454]
首先打开第一个标签远程桌面，

再打开第二个标签远程桌面，在连接的瞬间，关闭第一个标签软件就没有响应了。

**Comment by VShawn** [comment]
请问没有响应后是需要手动结束进程还是会自动退出？

能不能提供视频截图以便我尝试复现这个我问题

**Comment by aliciz** [comment]
我又试了一会，好像也不是每次出现，这里没法发截图，效果就是窗口标题栏显示：PRemoteM （未响应）。 底下得窗体整个变灰白色，鼠标变成圆圈一直转，等了几分钟都是这样，只能自己关闭掉了。

**Comment by VShawn** [comment]
感谢反馈，那我自己考虑一下故障的原因。

**Comment by VShawn** [comment]
尝试修复了下并发锁的逻辑，不确定能否修复这个问题
