### ISSUE TITLE
Open the program prompts can not find the database stored in the RSA private key file path

### ISSUE THREAD

**Issue by i911900kf** [1Remote/1Remote#456]
Open the program prompts can not find the database stored in the RSA private key file path

**Comment by i911900kf** [comment]
I did delete my rsa secret key file by mistake, which caused the program to be unusable, how do I fix it?

**Comment by VShawn** [comment]
sorry if you delete your rsa secret key I can't help to fix your data. you need to rebuild the whole database. 

I have abandoned RSA encryption in the latest version. I suggest you upgrade to the latest version.
