### ISSUE TITLE
Database: Permission to read denied!Please check your password of the file

### ISSUE THREAD

**Issue by Hohenbostler** [1Remote/1Remote#458]
**Describe the bug**
My Database is stored on my NAS over around 1 Year without Problem. Yesterday i´ve created a new connection  in P remote. After this i´ll get the error Message: Database: Permission to read denied!Please check your password of the file

**To Reproduce**
1. Open P Remote.
2. Just getting the Error.

**Desktop (please complete the following information):**
Windows 11

![grafik](https://github.com/1Remote/1Remote/assets/42488069/058ed281-56e9-41b7-958b-694ab405b643)

I´ve tried to copy the Database to a local Storage but the problem is the same. How can i unlock the Database ?

**Comment by majkinetor** [comment]
Have you restarted the computer :) ?

Something is probably locking the file.

**Comment by Hohenbostler** [comment]
Yes the NAS is restarted and both computer which are using the Database.

**Comment by majkinetor** [comment]
Install unlocker and see what is locking the file. We don't have a password. Maybe the file is corrupted. I hope you have a backup.

**Comment by Hohenbostler** [comment]
Hi, 

thx for your reply. That doenst work. The Error is the same. i Just also copy the database and rename it. But the Error is the same. 
And i can just rename it if the database is not blocked.

**Comment by majkinetor** [comment]
Yes, that means its not locked. It looks like it is corrupted. Can you open the database in some tool, such as dbeaver?

**Comment by Hohenbostler** [comment]
Yes with dbeaver i can it open

**Comment by majkinetor** [comment]
Hm... thats strange. Maybe @VShawn can say more but I suggest you switch to 1remote.

**Comment by Hohenbostler** [comment]
ok but with 1Remote i have to make everything new right ?

**Comment by majkinetor** [comment]
No, you can export database from PRemoteM and import it in the 1Remote (which now might be a problem if you can't revert to the previously working PRemoteM database)

**Comment by majkinetor** [comment]
BTW, you can try removing the connection you added using dbeaver if for some reason it is about it and you don't have a backup...

**Comment by Hohenbostler** [comment]
> 

No Dbeaver is not connected to the database

**Comment by VShawn** [comment]
i am not sure but u set a private key for your database？

**Comment by Hohenbostler** [comment]
> 

no not that i know. Can i see it with dbeaver if there is a private key ?

**Comment by VShawn** [comment]
you can see all info but the password, password is encrypted by private key

**Comment by Hohenbostler** [comment]
> 

ok thx. So i look with Dbeaver and i find this entry in the DB.
So i think there is an private key set ? 

![grafik](https://github.com/1Remote/1Remote/assets/42488069/2cab196f-1166-4762-9195-fd2347c8793b)


Did i have an chance to disable or clear it ?

**Comment by VShawn** [comment]
Why does your database query result have garbled characters?

But I now believe that this issue is unrelated to the private key. Can you check if your database file has write permissions(is readonly)? This warning pops up when the database cannot be written.

**Comment by Hohenbostler** [comment]
The Database is not readonly . There is no checkbox set

**Comment by VShawn** [comment]
Sorry due to the outdated code of PRemoteM, I took some time to investigate and find that this alert only shows when PRemoteM detects that it lacks permission to write to the database file OR fail to read the database, it displays this error.

here 

https://github.com/1Remote/1Remote/blob/735070dc5bb429ae5223f6d6fb073c4de483b4cc/Ui/Model/PrmContext.cs#L55C22-L59

or here:

https://github.com/1Remote/1Remote/blob/735070dc5bb429ae5223f6d6fb073c4de483b4cc/Ui/Model/PrmContext.cs#L82

so plz check PRemote log, to see if any error log related to sqlite. 

I think it's possible that your database file is corrupted(since garbled characters shows), leading to a read error, which in turn is being mistakenly interpreted by this imperfect error detection program as the database being locked and unable be read.

**Comment by Hohenbostler** [comment]
Hello sorry but i can´t read an error log. So in the attachmend you see the newst error from premote with the database.

If you want i can send you the original database private ( if there is an option to do this. )
[PRemoteM.log_20230721.md](https://github.com/1Remote/1Remote/files/12124993/PRemoteM.log_20230721.md)

**Comment by VShawn** [comment]
[T:022][15:20:27.351]	`Error`		[PrmContext.cs(InitSqliteDb:62)]	
> code = Corrupt (11), message = System.Data.SQLite.SQLiteException (0x800007EF): database disk image is malformed
database disk image is malformed

The log says: database disk image is malformed.

It seems that the data is corrupted. I hope you have enabled versioning in your Synology, otherwise your data may be lost.

**Comment by Hohenbostler** [comment]
Hey , 

ok i have older versions. So i could usw this. Thanks for your Help ..
