### ISSUE TITLE
zoom in remote for HDPI client monitor

### ISSUE THREAD

**Issue by shamork** [1Remote/1Remote#459]
**Is your feature request related to a problem? Please describe.**
NO

**Describe the solution you'd like**
I use a 2k monitor with a 150% scale HDPI settting。
When I connectted to the remote server, fonts and window UI controls(e.g. buttons) in the remote server is very small.

**Describe alternatives you've considered**
I Need a feature like https://howto.hyonix.com/article/fix-remote-desktop-dpi-scaling-issues-in-windows/

The behavior is: 
client monitor resolution: 1.5x  with a 150% scale HDPI settting, but everything is resize to 1.5x size (HDPI)
remote server monitor resolution: 1x, and sacle to 1.5x size, which will be blurred, but the size is bigger
It's like the client HDPI setting turns to a resize to the remote, if the remote does not support HDPI.

**Additional context**
NO

**Comment by shamork** [comment]
When I configured mstsc follow https://howto.hyonix.com/article/fix-remote-desktop-dpi-scaling-issues-in-windows/, then use mstsc mode, it works as expected.

**Comment by VShawn** [comment]
Sorry for the late reply, I have been traveling recently and haven't been able to attend to my GitHub messages. Annnnd gongratulations on resolving the issue :)
