### ISSUE TITLE
可以考虑改成单文件的便携版

### ISSUE THREAD

**Issue by Tendx** [1Remote/1Remote#460]
存储用的sqlite可以换成litedb或者json文件，这样改成单文件版本会很清爽

**Comment by VShawn** [comment]
> > 感谢反馈，目前sqlite已经是单文件数据库了，换成litedb差异也不大。
> > 为了数据同步和本地化配置的考虑，软件设置和数据是分开存储的。
> > 并且exe无法完全封装为一个单独文件，有些dll没法打包到一起。
> > 话说用 json 作为数据源，总觉得哪里怪怪的。
> 
> 在项目文件 csproj 里面配置该属性打包
> 
> ```
> <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
> ```

![image](https://github.com/1Remote/1Remote/assets/10143738/cbaaf4d6-fafd-4b42-9685-c39229f930cc)

感谢，增加这个参数后，sqlit的库也被打包到一起了👍👍

![image](https://github.com/1Remote/1Remote/assets/10143738/fd7072fa-f8fc-4f4a-b9cd-11c966e978e1)
