### ISSUE TITLE
链接ubuntu 试用密钥登录

### ISSUE THREAD

**Issue by xiao1314wang** [1Remote/1Remote#462]
链接腾讯云的  ubuntu系统 使用 密钥链接  报错 
![image](https://github.com/1Remote/1Remote/assets/39484593/5b7a00e1-6a7f-4a39-8b61-1a610e6f32cd)
然后就无法访问了
![image](https://github.com/1Remote/1Remote/assets/39484593/3de42a46-7b61-412f-9631-bb3f631a9ce2)
链接sftp可以使用

**Comment by VShawn** [comment]
确认一下使用的私钥格式，如图 SSH 只支持 putty 私钥

![image](https://github.com/1Remote/1Remote/assets/10143738/e38511fb-06ae-435d-a088-eb3e668207e1)

而SFTP仅支持 OpenSSH 私钥

![image](https://github.com/1Remote/1Remote/assets/10143738/de19bc24-7b76-4a0a-b114-0641866691ed)

**Comment by VShawn** [comment]
close this ticket because it has been inactive for long.
