### ISSUE TITLE
远程桌面最大化设置不方便

### ISSUE THREAD

**Issue by fanhua1550** [1Remote/1Remote#465]
设置连接后最大化桌面不方便，只有一个全屏设置。另外出现过保存配置永远不跳到远程连接列表界面。

**Comment by VShawn** [comment]
没有理解你的意思，能够具体展开讲讲是哪里不方便，你觉得应该怎样才方便么？

**Comment by VShawn** [comment]
close this ticket because it has been inactive for long.
