### ISSUE TITLE
使用vnc远程时无法使用粘贴将本地文字复制到远程

### ISSUE THREAD

**Issue by yefansky** [1Remote/1Remote#469]
使用vnc远程时无法使用粘贴将本地文字复制到远程
且键盘输入会变成乱码

**Comment by VShawn** [comment]
这是个已知问题，内置的VNC就是这样的，只能输入英文，切到中文输入会乱码。而且不能复制粘贴。
但没办法，VNC客户端的开发从2019年开始就废弃了：https://github.com/humphd/VncSharp，我个人没有足够能力去重启这个项目。

因此我建议你集成第三方VNC客户端，比如说 TightVNC，添加第三方客户端的方法可以参考使用文档中 Runner 那部分。

如此就可以支持中文输入和复制粘贴了：

https://github.com/1Remote/1Remote/assets/10143738/1910c8af-5780-4cf1-8791-ff09a6367d2d
