### ISSUE TITLE
建议优化

### ISSUE THREAD

**Issue by TianSen-Git** [1Remote/1Remote#470]
可不可以给这些机器增加一些自定义分组。
![Snipaste_2023-08-05_16-09-49](https://github.com/1Remote/1Remote/assets/52436304/aeb836bf-4ac6-4e91-bbe3-cf7d295d4067)

```[tasklist]
### Tasks
```

**Comment by VShawn** [comment]
我们这边的分组是以 tag 形式实现的，你可以把tag固定在顶端实现分组筛选

![image](https://github.com/1Remote/1Remote/assets/10143738/495d265a-8160-4280-b853-7ec9a996db91)
