### ISSUE TITLE
能连接窗口都在一个界面

### ISSUE THREAD

**Issue by fanhua1550** [1Remote/1Remote#473]
希望有开关可以选择远程连接显示在新窗口还是原窗口，
另外还有个建议就是希望可以直接选择窗口最大化还是全屏这些。

**Comment by VShawn** [comment]
> 有开关可以选择远程连接显示在新窗口还是原窗口

这个以前有，但考虑到用的人少且一个人不够维护太多特性，就去除了，以后应该也不会再加回来。

> 直接选择窗口最大化还是全屏

同理，这个功能可以做也考虑过要不要做，但需要比较复杂的逻辑判断控制来使每个协议都支持全屏，一个人懒得维护太多特性，所以没做。

P.S. 现在 RDP 是支持直接进入全屏的，其他协议不支持。

**Comment by zrlhk** [comment]
现在连接维护  单独一个窗口，真没必要
多个连接都已经一个窗口中分tab了，连接维护不能做一个tab吗？
感觉分离有点多余

**Comment by VShawn** [comment]
@zrlhk 最大的原因是我喜欢这样，仅此而已。如果你喜欢全部在一个tab，可考虑使用 mRemoteNG，我最初也是使用 mRemoteNG的。
