### ISSUE TITLE
问一下如何能让连接历史以及设置等数据文件保存在软件根目录？第一次用时这个设置项是灰色的无法使用！

### ISSUE THREAD

**Issue by hktkqwe123** [1Remote/1Remote#474]
问一下如何能让连接历史、记住的主机、账户、密码以及设置等数据文件保存在软件根目录？第一次用时这个设置项是灰色的无法使用！
有相关的功能么？还是说这个一开始的设置选项是假的还没写出来？
重装系统数据全部丢失了。每次还要重新填写

**Comment by VShawn** [comment]
文件夹下有个 FORCE_INTO_APPDATA_MODE 文件，重命名为 FORCE_INTO_PORTABLE_MODE 后，就是便携模式，所有数据保存在 exe 同目录。
