### ISSUE TITLE
create SSH Tunnel

### ISSUE THREAD

**Issue by BurtGummer** [1Remote/1Remote#483]
Hello,

is there a way to setup a ssh tunnel in PRemoteM 0.7.2.8 like in putty -> Connection -> SSH -> Tunnels?

Works, sorry: import a kitty session works great with tunnel.

**Comment by BurtGummer** [comment]
closed

**Comment by VShawn** [comment]
I am not a user of tunnel. Could you tell me how you use tunnel through kitty session? Maybe we should document your method for future reference.

**Comment by BurtGummer** [comment]
Sure. 

1. download and start Kitty portable
2. enter a hostname and a name in "Saved Sessions/New Folder" 
3. klick "Connection" -> "SSH" -> "Tunnels"
4. enter a source port, for example 777
5. enter a destination, for example "192.168.1.2:80" - a webinterface that is reachable from the host we connect to
6. klick "Add"
7. go to "Session" and klick "Save (d)"

Now there is a new file in

..\kitty-portable-win32-0.74.4.13-36\data\config\Sessions\

this file we import in PRemoteM under SSH -> Kitty Session in a new SSH-Connection. Enter the same hostname, username and password in PRemoteM.

Thats it. If the connection successfully connected, the remote webinterface is available on my local computer if I enter localhost:777 in the Browser.
