### ISSUE TITLE
Srollbar for Tags

### ISSUE THREAD

**Issue by ej0815de** [1Remote/1Remote#485]
It would be a good feature to implement a scrollbar at the register tags.

If you use many TAGs it is not possible to see the TAG at the bottom, because there is no scrollbar.

**Comment by majkinetor** [comment]
Are you using 1Remote or PRemoteM ?

**Comment by VShawn** [comment]
err What do you mean “TAG at the bottom”？can you give a screen shoot？

**Comment by ej0815de** [comment]
i deleted some of my tags an now they are all visible in the window.

**Comment by VShawn** [comment]
oh that's improved in 1Remote

![image](https://github.com/1Remote/1Remote/assets/10143738/4baa31ac-7f32-47d2-8231-76da3101cbce)

AND PRemote has been archived now

**Comment by majkinetor** [comment]
Please switch to 1Remote.
