### ISSUE TITLE
使用串口遇到点问题 

### ISSUE THREAD

**Issue by fengbo1029** [1Remote/1Remote#486]
问题1：登录到网络设备使用命令行 无法删除输入错误的命令  只能回车重新输入
问题2：串口连接时候可否使用下拉的方式进行选择，而不是直接输入名称进行连接？
问题3：命令行里面数字都是黑白色  能否对有些字体增加色彩（比如下方的ip地址等）

问题1解决方法已经找到了 这样设置之后就可以进行删除了
（参考地址：https://blog.csdn.net/Pipcie/article/details/104954603）
![) A43Q)K`HR L IFZ3NVB)R](https://github.com/1Remote/1Remote/assets/99636954/4c0806fb-2553-448f-ad2d-ecb28f5e71de)

![image](https://github.com/1Remote/1Remote/assets/99636954/43406d09-590f-477f-9661-338778e04649)
![image](https://github.com/1Remote/1Remote/assets/99636954/61f6b44e-f07e-4c6e-9683-1c8645c52957)

**Comment by VShawn** [comment]
已经加上了

![Uploading image.png…]()
