### ISSUE TITLE
Teams sharing freezes, when i am switching tabs.

### ISSUE THREAD

**Issue by ThoHolit** [1Remote/1Remote#487]
I am not shure if it is a porblem with 1remote or Microsoft Teams, but since about 3 month, i have the following problem.
I have 1remote open with 2-more Session to Servers openend in Tabs, when i have a tema session and share the 1remote window, the screen freezes for all members of the meeting, when i switch to another tab in 1remote. This worked in earlier times.

**To Reproduce**
1. Open 1remote and open 2 or more Session in the same Window ( one Tab for each session)
2. Join a Teams Meeting and Share the 1Remote Window
3. Switch the Tabs in 1Remote then the Screen sharing freezes.

**Desktop (please complete the following information):**
 - OS: Win11 22H2 (Build 22621.2134)
 - pRemote latest Version and 1Remote nigthly (13.08.2023)
 - Microsoft Teams regular or preview

**Comment by VShawn** [comment]
When you don't have Teams running, is everything normal?
