### ISSUE TITLE
手动进行排序功能建议

### ISSUE THREAD

**Issue by fengbo1029** [1Remote/1Remote#490]
手动进行排序的时候，拖动对应的主机名称 拖动过程 动画效果不明显，建议增加一下拖动的效果

**Comment by VShawn** [comment]
道理我也懂，但UI这块我是半路出家全靠自学，好看的效果good to have，但我个人短时间内是弄不出来。所以我会优先关注更正重要的功能修改. 如果有 UI 大佬能支援界面部分就好了
