### ISSUE TITLE
mouse over window from notes ignores line breaks

### ISSUE THREAD

**Issue by andy1463** [1Remote/1Remote#491]
If I add some notes for a RDP connection, line breaks will shown correctly in edit mode.
In the mouse over view of the list however line breaks will be ignored and the text will be shown without them, which makes it sometimes confusing

you can see it on the following files:
![linebreak_ok](https://github.com/1Remote/1Remote/assets/128373669/c37941a2-36f6-4ed9-8a24-5d196b5fc095)

![linebreak_overview](https://github.com/1Remote/1Remote/assets/128373669/e9a276dd-45b7-4cf6-ba44-ca62ce5bfed7)

tested on Windows 10

Thank you and best regards

**Comment by majkinetor** [comment]
This is markdown, it behaves correctly.
