### ISSUE TITLE
Name cut off in overview list

### ISSUE THREAD

**Issue by andy1463** [1Remote/1Remote#492]
If the name of a RDP connection is a bit longer it will be cut off in the list, even there is a lot of space between the name and the next column. For similar entries it is sometimes confusing to pick the right connection.

The name should be displayed till the beginning of the next column.

![name_cut_off](https://github.com/1Remote/1Remote/assets/128373669/a8a662a0-7cba-4d2c-b78e-7c9d8e0d974c)

Tested on Windows 10

Thank you

**Comment by VShawn** [comment]
Yes, I have limited the length of the name. I don't want the name to be too long or have line breaks because it won't fit properly in the launcher.

**Comment by VShawn** [comment]
close because of #505
