### ISSUE TITLE
建议真加复制标签功能

### ISSUE THREAD

**Issue by fengbo1029** [1Remote/1Remote#494]
在使用ssh连接Linux的时候，经常会使用到复制当前连接 希望能够增加。目前xsehll和MobaXterm有这个功能
![image](https://github.com/1Remote/1Remote/assets/99636954/11af5806-1b15-488f-9427-4cce8b3394be)
![image](https://github.com/1Remote/1Remote/assets/99636954/53a978f6-6829-4cab-92e8-bfee2bbb65a3)

**Comment by VShawn** [comment]
复制出来的有什么特殊用处呢？比如我通过 alt + m 把这个 ssh 再打开一次似乎是完全一样的效果。

**Comment by VShawn** [comment]
close inactive ticket
