### ISSUE TITLE
SFTP folder size incorrectly displayed as zero

### ISSUE THREAD

**Issue by kaixinol** [1Remote/1Remote#495]
**Describe the bug**
SFTP folder size incorrectly displayed as zero

**To Reproduce**
![image](https://github.com/1Remote/1Remote/assets/100816732/ebcd0072-491b-4cc6-96cc-0acbd96af7ae)

**Expected behavior**
Request not to display any data of size zero

**Screenshots**
*see above*

**Desktop (please complete the following information):**
 - OS: Win11 22H2
 - PRemoteM Version 1.0.0-BETA-06

**Additional context**

**Comment by VShawn** [comment]
hi I fix it.
