### ISSUE TITLE
最新版的1remote串口连接问题

### ISSUE THREAD

**Issue by fengbo1029** [1Remote/1Remote#496]
你好我使用8.25更新的1remote ，今天使用串口连接的时候  依然不能进行删除输入错误的命令。希望能够优化！
还有就是串口连接的那个比特率 可以多增加几个 非常感谢
![image](https://github.com/1Remote/1Remote/assets/99636954/7351efef-16be-4ca3-be5c-5851f0751f8f)

**Comment by VShawn** [comment]
https://github.com/1Remote/1Remote/blob/main/Ui/Utils/KiTTY/IKittyConnectable.cs#L77C59-L79

实际上已经正确设置了 BackspaceIsDelete 和 LinuxFunctionKeys

![image](https://github.com/1Remote/1Remote/assets/10143738/4638bcf2-9633-409c-a56d-540071fe2054)

**Comment by fengbo1029** [comment]
实际测试还是不能使用！！！
对了 使用ssh连接到Linux  vi编辑配置文件的时候经常卡死   需要重新推出才能编辑

**Comment by fengbo1029** [comment]
> 看来没有测试环境，强行新增一个协议还是有点勉强，如果体验太差，我还是考虑删除串口连接功能了。
> 
> 我偶尔用VI编辑没有遇到过卡死的情况，是不是要编辑大文件？

如何这个串口功能取消，那就太可惜了（我打算用1remote来替代现在的MobaXterm 一直期盼的串口功能）。配置文件不大 大概100kb , 我遇到过很多次了

**Comment by VShawn** [comment]
但不好用的半成品，宁愿不搞，太影响用户体验了。

**Comment by fengbo1029** [comment]
> 姑且又修改了一版，没经过测试，依旧不确定功能是否正常。

好的 我测试下
