### ISSUE TITLE
tags-tab not displayed

### ISSUE THREAD

**Issue by BurtGummer** [1Remote/1Remote#501]
Download version 0.7.2.8, using portable mode. I open an existing PRemoteM.db with some entries and multiple tags, but there are no tags dislayed. I have to edit a connection/server and save them, then the "tags"-tab will dislayed.

And the tags I select to show as tab does not save to the PRemoteM.db or is not imported.

**Comment by VShawn** [comment]
Hey friend, I suggest you update to 1Remote because PRemoteM is no longer maintained, and even if there are bugs, they won't be fixed anymore.

**Comment by BurtGummer** [comment]
Hello,
no no, its the up2date Version from https://github.com/1Remote/1Remote/releases/tag/0.7.2.8
but the file called "PRemoteM.db".

**Comment by VShawn** [comment]
> up2date Version from https://github.com/1Remote/1Remote/releases/tag/0.7.2.8

yes that's the PRemoteM

I'm currently developing 1REMOTE, and the updates are being released in the Nightly preview:

https://github.com/1Remote/1Remote/releases/tag/Nightly

**Comment by majkinetor** [comment]
Pinned tags are not imported when you switch from PRemoteM to 1Remote, but you should have _Tags_ tab where you can pin them again.
