### ISSUE TITLE
1REMOTE's portable installation package is much larger compared to REMOTE.

### ISSUE THREAD

**Issue by fengbo1029** [1Remote/1Remote#502]
我之前一直用remote 现在改为1remote ，但是1remote安装包大了很多 是不是增加了新功能的原因哈？对了之前有新的版本升级，打开remote会提示有新版本更新，现在使用1remote不会有新版本更新提示了？

**Comment by VShawn** [comment]
1. 1remote 在 beta6 版本增加了对微软 Windows hello的支持，为此不得不引用了一个 20 MB 的库，详见 https://github.com/1Remote/1Remote/discussions/464#discussioncomment-6610909_
2. 1remote 依然有新版本提示，但要到小版本更新时才会提示，比如说 beat6升到 beta7时。

**Comment by fengbo1029** [comment]
明白  Windows hello这个功能我目前用不到  因为我的电脑我习惯性走的时候锁屏   别人是看不到我设备的登录账户或者密码的

**Comment by VShawn** [comment]
无需担心，功能是默认关闭的，唯一的不好就是软件比以前大了 20mb

**Comment by fengbo1029** [comment]
哈哈 我兄弟我喜欢小的  不喜欢大的
