### ISSUE TITLE
用VPN工具EasyConnect连接客户内网地址，用1Remote不能RDP远程和SSH远程，用PRemoteM 0.7.2.8版本又可以

### ISSUE THREAD

**Issue by vvvvth** [1Remote/1Remote#504]
用VPN工具EasyConnect连接客户内网地址，用1Remote不能RDP远程和SSH远程，用PRemoteM 0.7.2.8版本又可以

**Comment by VShawn** [comment]
额。。有点奇怪，0.7.2.8 和 1.0.0 beat 之间没做过代理方面的修改，不应该出现一个能连另一个不能连的情况。

我这边没有任何 VPN 工具可以测试，所以很抱歉可能帮不到你了。
