### ISSUE TITLE
建议添加窗口可拖动

### ISSUE THREAD

**Issue by xiesibobo** [1Remote/1Remote#505]
远程桌面的窗口不能拖动改变大小，建议添加此项功能，并且可以配置拖动是改变分辨率还是倍数

**Comment by VShawn** [comment]
RDP 可以拖动改变桌面大小啊？

如果是 RDP 到 Ubuntu，那确实没办法，服务器端限制了。

**Comment by xiesibobo** [comment]
嗯嗯，我找了个windows试了一下，确实是。
但是我发现了一个可能算是优化点的地方吧
比如这个图中的灰色部分，我把屏幕分辨率固定后，扩大窗口后我希望能有一个选项是填充满这个窗口
![image](https://github.com/1Remote/1Remote/assets/30513954/c24edd14-d13c-41ec-a929-00fb8ead61f0)
另外，如果我选择自适应的话，ubuntu默认是766*8xx，但是我打开Windows吧窗口拖成2K关闭后再打开ubuntu ubuntu窗口就变成了2K,可能我描述的不清楚，参考rdm的这些选项
![image](https://github.com/1Remote/1Remote/assets/30513954/0fa1002f-d17b-417b-86c0-5a32ee567f8e)

**Comment by VShawn** [comment]
> 比如这个图中的灰色部分，我把屏幕分辨率固定后，扩大窗口后我希望能有一个选项是填充满这个窗口

我以前试图去除这个灰色区域，但不知道是微软提供的组件限制还是他们设计如此，比如当RDP桌面是100X100，而窗口大小是200X200时，这个控件就是不能让RDP桌面也缩放到200X200，一旦窗口超过100X100，就出现灰色边缘了。我目前没办法解决这个。

> 果我选择自适应的话，ubuntu 默认是 766*8xx，但是我打开 Windows 吧窗口拖成 2K 关闭后再打开 ubuntu ubuntu 窗
口就变成了 2K, 可能我描述的不清楚，参考 rdm 的这些选项

我对Linux 桌面版完全不熟悉，请问是如何配置 Linux 的 RDP 服务器，才能让它重连后应用新的分辨率？我用xrdp 的默认配置无法实现这一点。

**Comment by xiesibobo** [comment]
我刚才重新装了个虚拟机确认了一下 装完xrdp不需要额外的配置，打开的时候默认会用当前窗口打开的大小，我的是ubuntu 23.04

**Comment by VShawn** [comment]
moved to #545
