### ISSUE TITLE
建议增加一个自定义换背景的功能

### ISSUE THREAD

**Issue by fengbo1029** [1Remote/1Remote#508]
建议增加一个自定地换背景的功能，ssh连接的时候背景都是黑白色  属实比较单调，希望能增加这个功能

**Comment by VShawn** [comment]
![image](https://github.com/1Remote/1Remote/assets/10143738/6d79f7ef-51cc-4486-b268-fd63c09581fa)

可以更换几个背景，在设置里面可以选几个putty的主题。
