### ISSUE TITLE
Do you plan to support proxy functionality, mainly HTTP proxy?

### ISSUE THREAD

**Issue by iawes** [1Remote/1Remote#509]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by VShawn** [comment]
Hi Are you asking about RDP or SSH proxy? 

But regardless of which one, I personally have never used a proxy to connect, and I don't have a testing environment for the feature either. So currently, there are no plans to support a proxy.

And If you or anyone else intends to add proxy functionality for 1Remote, I would warmly welcome your pull request:)
