### ISSUE TITLE
添加了一个rdp试试，再编辑点确定，提示的啥东东，难道没有一个详细提示？

### ISSUE THREAD

**Issue by fictioner** [1Remote/1Remote#510]
添加了一个rdp试试，再编辑点确定，提示的sequence contains no elements？

**Comment by VShawn** [comment]
可以提供日志看看是什么问题么？

**Comment by VShawn** [comment]
bug 已修复，自测了一下未发现问题，麻烦你更新到最新版本帮助我测试，谢谢。
