### ISSUE TITLE
感觉现在1远程没有以前流畅了

### ISSUE THREAD

**Issue by Hi-360** [1Remote/1Remote#512]
之前一直使用的是Remote，后来更换为1Remote。但是安装包增加了20m以后 感觉没有以前流畅了，这个安装包大小以后还会优化缩小吗？我的笔记本是i5-5200u的

**Comment by VShawn** [comment]
不会优化了，增加的20m是微软的系统库，我没办法优化体积。没以前流畅可能是因为添加的服务器配置多了，现在这个程序的UI绘图性能不太好，我测试过去掉所有动画和图片显示，去掉搜索高亮，就会很流畅。

**Comment by fengbo1029** [comment]
哈哈 看来还需要不断打磨ui啊   号召ui大神一起优化

**Comment by fengbo1029** [comment]
我现在想换回了Remote虽然流畅 但是不支持串口连接    哎
