### ISSUE TITLE
能够像RDM一样创建凭证，然后在连接中引用这个凭证吗？

### ISSUE THREAD

**Issue by chariothy** [1Remote/1Remote#514]
我们公司强制60天换一次密码，如果每个连接中都要手动换密码就太麻烦了。
如果能够保存在一个凭证中，那么只要在凭证中修改密码，就所有的连接都得到更新了。
谢谢！
BTW，非常棒的工具！

**Comment by VShawn** [comment]
soory 不打算做多凭证，但这个APP允许批量编辑，即你可以把公司的所有服务器打上标签“Work”，需要批量修改密码时筛选出Work标签的所有服务器，全选后，点下方的编辑按钮。

![image](https://github.com/1Remote/1Remote/assets/10143738/f9cff6b1-3394-4da1-8d10-0af490452c6d)
