### ISSUE TITLE
RDP关于适应窗口大小，希望有个选项适应窗口保持比例，哪怕是留下灰边

### ISSUE THREAD

**Issue by qishiwobutaihuichengdan** [1Remote/1Remote#518]
RDP关于适应窗口大小，希望有个选项适应窗口保持比例，哪怕是留下灰边，不然比例很怪。
![1696057164113](https://github.com/1Remote/1Remote/assets/105117863/a9633004-9be1-4d7a-a77c-7edbb7848df8)
![1696057180650](https://github.com/1Remote/1Remote/assets/105117863/882d4b5c-d963-49ae-b695-0554187ddf87)

**Comment by VShawn** [comment]
分辨率别选拉伸就行了，其他选项都是保持比例的

![image](https://github.com/1Remote/1Remote/assets/10143738/ab9f5d3f-4c61-4a54-b9e5-8b771afcc4f5)

**Comment by qishiwobutaihuichengdan** [comment]
选不拉伸，小窗口就会只会显示桌面一小部分，
![1696228194058](https://github.com/1Remote/1Remote/assets/105117863/097052dc-3932-4114-9e03-c01563a9bd54)
我更希望是这样，保持比例的适配窗口
![1696228228925](https://github.com/1Remote/1Remote/assets/105117863/411c92ae-bca0-436b-9d57-a102c3943596)

**Comment by qishiwobutaihuichengdan** [comment]
还有需要鼠标操作3d视角，像远程的3d鼠标，我看网上RDP都没有类似的功能，不知道能不能做得出来。

**Comment by VShawn** [comment]
> 还有需要鼠标操作 3d 视角，像远程的 3d 鼠标，我看网上 RDP 都没有类似的功能，不知道能不能做得出来。

基于 RDP 的都做不出来，RDP 鼠标中键的映射只能触发式映射，想3D视角要长按中键的是做不到的。建议你去看一下 nvidia sunshine moonlight 协议，这种窜流协议应该可以解决3D视角的问题。
