### ISSUE TITLE
Can't see database password

### ISSUE THREAD

**Issue by majkinetor** [1Remote/1Remote#520]
**Describe the bug**
Password is not shown once login popup terminates. Probably the focusing issue.

**Screenshots**

<details><summary>details</summary> 

![jafin5](https://github.com/1Remote/1Remote/assets/85767/b3ffe80b-7333-4280-8aab-70b77218f4cf)
</details>

**Desktop (please complete the following information):**
 - OS: Win10
 - 1remote v1.0.0.20230820

**Comment by VShawn** [comment]
I think I've fixed the issue, but hard to remember exactly when I fixed it after a long national holiday.
