### ISSUE TITLE
VNC error : Only versions 3.3, 3.7, and 3.8 of the RFB Protocol are supported

### ISSUE THREAD

**Issue by jhsswl** [1Remote/1Remote#523]
**Describe the bug**
VNC error : Only versions 3.3, 3.7, and 3.8 of the RFB Protocol are supported

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Win10 Pro 2004]
 - PRemoteM Version [e.g. 0.4.6.20071234]
 Version 1.0.0-beta.06

**Additional context**

**Comment by VShawn** [comment]
yes our vnc client comes from an old archived https://github.com/humphd/VncSharp, it do not supported latest RFB Protocol.

you can change to TightVNC by following http://1remote.org/usage/protocol/runner/#customize-your-runner
