### ISSUE TITLE
能否增加一个可视化的窗口

### ISSUE THREAD

**Issue by fengbo1029** [1Remote/1Remote#526]
![image](https://github.com/1Remote/1Remote/assets/99636954/1b310489-93ed-4110-a171-2bf106bff796)

你好楼主能否增加一个可视化操作的界面，方便文件的上传。  特别对于新手来说非常友好，  这个是MobaXterm的界面   想要这样功能  方便文件上传和下载

**Comment by fengbo1029** [comment]
> ![image](https://user-images.githubusercontent.com/99636954/273745277-93f29d24-9b1b-4cee-a6b5-006641240627.png) 你好楼主能否增加一个可视化操作的界面，方便文件的上传 特别对于新手来说很友好 这个是MobaXterm的界面 想要这样功能

**Comment by VShawn** [comment]
受限于 SSH 实现方法，目前无法实现
