### ISSUE TITLE
长时间运行后的响应似乎有问题

### ISSUE THREAD

**Issue by jjj333** [1Remote/1Remote#536]
在运行较长时间后再用alt-M唤起似乎会卡一会儿（几秒钟）才能显示界面，任务栏图标唤醒也是这样。。。

**Comment by VShawn** [comment]
是的，为了降低内存占用，在后台一段时间后会清理所有缓存，因此长时间不用后，打开界面会有一点卡顿，因为要重建缓存。
我最长的放置时间是电脑挂机48h后，再打开会有一瞬间的卡顿，之后就能恢复UI的显示。

但是，你这边要卡几秒是有问题的，我测试一般在1秒内就恢复响应，释放是因为你电脑的配置较低或资源不足？因为我的测试环境都是开发环境，空闲内存比较多，CPU不高只有I5 10400，无独立显卡。

**Comment by jjj333** [comment]
好吧，G4560+机械硬盘只配拥有卡顿。。。

**Comment by jjj333** [comment]
好吧，G4560+机械硬盘只配拥有卡顿。。。

**Comment by VShawn** [comment]
或许我应该提供一个选项，提供自动清理缓存功能的开关。

**Comment by jjj333** [comment]
或者只保留最后一个连接的缓存
