### ISSUE TITLE
Mouse over error in notes

### ISSUE THREAD

**Issue by andy1463** [1Remote/1Remote#538]
**Describe the bug**
Access to notes field only possible from above. If you have a lot connections in the overview list, it is not possible to access the notes for the entries at the bottom of the list. If you try to access the notes field from below notes from the entry above will be opened.

**Expected behavior**
It should be possible to access notes either from above or from below.

**Screenshots**
![1remote-2](https://github.com/1Remote/1Remote/assets/128373669/844ea372-d56d-4b0a-a74e-cc210f170528)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - PRemoteM Version current nightly

**Comment by majkinetor** [comment]
So, do not show tooltip like this

![image](https://github.com/1Remote/1Remote/assets/85767/d49ed48b-2902-45b0-a4b5-c3932a0e59ca)

but like this

![image](https://github.com/1Remote/1Remote/assets/85767/7d9351bd-c413-4887-8666-f1dc3beddd15)
