### ISSUE TITLE
Windows 远程连接过程中，1Remote主程序窗口无法拖动，只能点击缩小

### ISSUE THREAD

**Issue by coolmian** [1Remote/1Remote#539]
**Describe the bug**

**To Reproduce**
随便连接一个远程桌面，在桌面还没显示出来，不断转圈的时候，我想把他拖动到另一个副屏上，发现拖动不了，整个窗口会不停闪烁，无法移动。

**Expected behavior**

**Screenshots**
![image](https://github.com/1Remote/1Remote/assets/36444522/7296c0c8-3413-4ce2-9a60-ef750af20ecf)

**Desktop (please complete the following information):**
 - OS: Windows 10 loT企业版 LTSC 21H2
 - PRemoteM Version 0.7.2.8

**Additional context**

**Comment by filwu8** [comment]
> 额，我这边连接速度很快，几乎没有转两圈的机会。晚些我再想想怎么去复现这个问题，最近比较忙。总之感谢反馈。

补充下，勾选了 /admin 模式以后，就无法合并到一个页面，多个窗口了。

**Comment by coolmian** [comment]
> 额，我这边连接速度很快，几乎没有转两圈的机会。晚些我再想想怎么去复现这个问题，最近比较忙。总之感谢反馈。

尝试连一台连不上的ip，就可以在这个页面转圈很久。

**Comment by VShawn** [comment]
https://github.com/1Remote/1Remote/assets/10143738/67f3ebf0-30f6-4d53-9bcd-a797eddf3749

实测可以拖动，测试版本是最新的nightly

**Comment by VShawn** [comment]
> > 额，我这边连接速度很快，几乎没有转两圈的机会。晚些我再想想怎么去复现这个问题，最近比较忙。总之感谢反馈。
> 
> 补充下，勾选了 /admin 模式以后，就无法合并到一个页面，多个窗口了。

详细说说是什么现象？我没看明白

**Comment by coolmian** [comment]
> 1.mp4 
> 实测可以拖动，测试版本是最新的nightly

先全屏连接一个，然后关掉，这样下次打开连接也是全屏的。全屏的时候是不能拖动的。

**Comment by filwu8** [comment]
就是一个窗口多个远程桌面，如果勾选了 /admin 模式以后，就无法合并到一个页面多个窗口了。

VShawn ***@***.***>于2023年10月28日 周六15:29写道：

**Comment by VShawn** [comment]
> > 1.mp4
> > 实测可以拖动，测试版本是最新的 nightly
> 
> 先全屏连接一个，然后关掉，这样下次打开连接也是全屏的。全屏的时候是不能拖动的。

要不你试一下 1remote 的 nightly build？因为改了蛮多东西了，premotem 已经不再继续维护了

**Comment by filwu8** [comment]
就比如说 Chrome 浏览器那种 [将标签移至另一个窗口]

[合并到一个标签页]这样的功能

比如同时开了七八个虚拟机，有些在一个窗口，有些是单独全屏，这时候这个功能就好好用了

VShawn ***@***.***>于2023年10月29日 周日09:51写道：

**Comment by VShawn** [comment]
> 就是一个窗口多个远程桌面，如果勾选了 /admin 模式以后，就无法合并到一个页面多个窗口了。

这个晚一些测试

> 就比如说 Chrome 浏览器那种 [将标签移至另一个窗口]

我理解不是把标签拖出去就到另一个窗口了么？你没说我都不知道还有一个 `将标签移至另一个窗口` 按钮

**Comment by filwu8** [comment]
像这样


年10月29日 周日10:03写道：

**Comment by coolmian** [comment]
> 要不你试一下 1remote 的 nightly build？因为改了蛮多东西了，premotem 已经不再继续维护了

nightly build 没有这个问题了，谢谢。

**Comment by VShawn** [comment]
> nightly build 没有这个问题了，谢谢。

ok 感谢反馈

> 就是一个窗口多个远程桌面，如果勾选了 /admin 模式以后，就无法合并到一个页面多个窗口了。

实测没有发现这个问题。下面这两个do都勾选了 `/admin`

![image](https://github.com/1Remote/1Remote/assets/10143738/f7d8ebbb-f04b-4e81-8992-da566a7dd3d3)
