### ISSUE TITLE
高分辨率机器连接低分辨率机器，无法全屏

### ISSUE THREAD

**Issue by da1234cao** [1Remote/1Remote#542]
**Describe the bug**

高分辨率机器连接低分辨率机器，无法全屏。

高分辨率机器：win11系统；分辨率为2560*1440。
低分辨率机器：Ubuntu 22.04.3 LTS; 分辨率1920*1080；设置-共享，开启远程桌面。

无法拖拉放大

![image](https://github.com/1Remote/1Remote/assets/47857039/9b29fd12-8eb0-4b82-a635-04a2ce2a34d7)

**已尝试**

尝试修改这里的分辨率，并没有有效的结果。

![image](https://github.com/1Remote/1Remote/assets/47857039/161ea32a-e350-469d-a9f2-0698bcccb97e)

**期望**

高分辨的显示器上，可以全屏显示低分辨率机器的屏幕。

原理上似乎无法实现。

**Comment by VShawn** [comment]
这个不是分辨率的问题 Linux 的 RDP 协议是第三方实现的，比微软的 RDP 少了一些功能，在显示功能上有阉割（比如不支持动态调整分辨率）。你如果尝试远程到一台 1080p 的 Windows 电脑时，是可以全屏的。

**Comment by meteor1113** [comment]
#1030
