### ISSUE TITLE
1Remote的多账号可以多开吗?

### ISSUE THREAD

**Issue by weili0677** [1Remote/1Remote#543]
**Is your enhancement related to a problem? Please describe.**
比如一台服务器，我有2个连接账号：administrator和test，添加了test为第2个账号，如果连接了第1个账号后，想再打开test这个连接就没响应。。也许1Remote只是支持1次打开一个相同的连接窗口？
**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
Add any other context or screenshots about the enhancement here.

**Comment by VShawn** [comment]
这个软件只是对微软RDP的封装，而RDP是否可以多看是取决于系统，即个人版Windows不支持多账号同时登陆，后面的账号会把前面的踢下去。而Windows server则支持多人同时登陆到服务器。
