### ISSUE TITLE
远程连接的时候遇到一个严重的问题

### ISSUE THREAD

**Issue by fengbo1029** [1Remote/1Remote#547]
发现的一个bug 严重影响使用体验  ，远程连接的时候不能全屏  还有报错  详细看录屏
系统是win10 ltsb 2016

https://github.com/1Remote/1Remote/assets/99636954/d5e50a0f-25a8-4d47-8462-4f2dbea9d143

**Comment by VShawn** [comment]
录屏是黑的，我的网络问题么？

**Comment by fengbo1029** [comment]
> 录屏是黑的，我的网络问题么？

视频下载下来可以正常查看  哈哈  不知道是不是我录屏软件的问题

**Comment by VShawn** [comment]
下载可以看，在线看是黑屏的

**Comment by fengbo1029** [comment]
好的  我一开始电脑是2016ltsb的  使用贼流畅  但是使用1远程  发现存在bug果断换了系统   如果可以的话  我还想再换回去


| |
njfb1029
|
|
***@***.***
|
---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2023年11月3日 10:00 |
| 收件人 | ***@***.***> |
| 抄送人 | Wind ***@***.***> ,
***@***.***> |
| 主题 | Re: [1Remote/1Remote] 远程连接的时候遇到一个严重的问题 (Issue #547) |

下载可以看，在线看是黑屏的

**Comment by VShawn** [comment]
意思是在 2016ltsb 系统上运行 1Remote 去远程其他电脑，必发这个问题么？

**Comment by fengbo1029** [comment]
对的   


| |
njfb1029
|
|
***@***.***
|
---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2023年11月3日 11:42 |
| 收件人 | ***@***.***> |
| 抄送人 | Wind ***@***.***> ,
***@***.***> |
| 主题 | Re: [1Remote/1Remote] 远程连接的时候遇到一个严重的问题 (Issue #547) |

意思是在 2016ltsb 系统上运行 1Remote 去远程其他电脑，必发这个问题么？

**Comment by fengbo1029** [comment]
我在我的个人电脑上  还有公司的华为云桌面上都是win10 ltsb  必出现这个问题
| |
njfb1029
|
|
***@***.***
|
---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2023年11月3日 11:42 |
| 收件人 | ***@***.***> |
| 抄送人 | Wind ***@***.***> ,
***@***.***> |
| 主题 | Re: [1Remote/1Remote] 远程连接的时候遇到一个严重的问题 (Issue #547) |

意思是在 2016ltsb 系统上运行 1Remote 去远程其他电脑，必发这个问题么？
