### ISSUE TITLE
Optimize the display content of Windows Hello window

### ISSUE THREAD

**Issue by sparrowhe** [1Remote/1Remote#552]
When "Windows credentials verification is required to view passwors" is enabled, Windows Hello window will pop up when checking password. However applications calling for verification are not displayed correctly, it just "a application", and it may cause misunderstanding

Goal: Display "1Remote needs to verify your identity" instead of "**a application** needs ..."

Screenshot:

![image](https://github.com/1Remote/1Remote/assets/26871028/2876e562-0f5d-4c50-ba5b-5e264f8761b8)

I tried to find the solution but I failed. This is a possible exprience improvement.

**Comment by VShawn** [comment]
sounds reasonable

FYI, we can custom the message by using [`UserConsentVerifier.RequestVerificationAsync`](https://learn.microsoft.com/en-us/uwp/api/windows.security.credentials.ui.userconsentverifier.requestverificationasync?view=winrt-22621).

![image](https://github.com/1Remote/1Remote/assets/10143738/f0a46429-6b13-4e62-b033-dc3203981d77)

I need to go and check if this api works with `fingerprint identification` and `facial recognition`
