### ISSUE TITLE
I can't Add / Import Connections (Button not working)

### ISSUE THREAD

**Issue by stetze88** [1Remote/1Remote#557]
Nothing happens if i click on the buttons under add.

Version 1.0.0-beta.07 (Recent build)
![Screenshot 2023-11-08 082009](https://github.com/1Remote/1Remote/assets/73733823/ab7a60db-94e2-4ed7-8718-47d242727223)

Windows 11 23H2

**Comment by stetze88** [comment]
Fixt in latest Release ([1Remote-1.0.0.0-beta.07-net6-x64-nightly-20231108-5996f5.zip](https://github.com/1Remote/1Remote/releases/download/Nightly/1Remote-1.0.0.0-beta.07-net6-x64-nightly-20231108-5996f5.zip))

**Comment by VShawn** [comment]
yes, I fixed it in https://github.com/1Remote/1Remote/commit/5996f5af0b76105f61f39cfc275b0fdfa533eb3c
