### ISSUE TITLE
View blurred on external monitor without mstsc mode(solved  by drive update)

### ISSUE THREAD

**Issue by andy1463** [1Remote/1Remote#558]
**Describe the bug**
If a RDP connection is opened on an external monitor the view is blurred if you open it without mstsc mode. As soon as mstsc mode is checked the view is sharp and clear.

**Expected behavior**
View should also be sharf and clear without mstsc mode

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - current nightly
 - Same result on different notebooks with different external monitors
 -  Monitor connected via HDMI
 -  tested resolution: Full HD

**Comment by VShawn** [comment]
![image](https://github.com/1Remote/1Remote/assets/10143738/6a5dc73a-3351-4aee-8262-350bd8e29f24)

As you can see it works as expect on me(4k 150% scale + 4k 150% scale). everything sharp and clear.


And if I change to 4k 150% scale + 4k 200% scale (2 screens with different scale factors) 1Remote will be forced into mstsc mode to adapt the 2 different scale factors

**Comment by andy1463** [comment]
Sorry for late response. I was out of office last week. I found out that there was a general driver issue causing that problem on several machines. A driver update solved the issue.
