### ISSUE TITLE
Preview RDP File button not responding

### ISSUE THREAD

**Issue by sparrowhe** [1Remote/1Remote#560]
**Describe the bug**
![image](https://github.com/1Remote/1Remote/assets/26871028/b72c462d-7998-4f34-8e81-4e2e550441dd)
As shown in the picture, there is no response after pressing the button in the picture above.

**To Reproduce**
1. Go any RDP connection's edit page
2. Click on 'Preview RDP'
3. No responding

**Expected behavior**
Show preview of RDP file

**Desktop (please complete the following information):**
 - OS: Win11 Business 22H2
 - 1RM net6-x64-nightly-20231108-5996f5

**Comment by sparrowhe** [comment]
Related: https://github.com/1Remote/1Remote/blob/5996f5af0b76105f61f39cfc275b0fdfa533eb3c/Ui/View/Editor/Forms/RdpFormView.xaml.cs#L103

**Comment by VShawn** [comment]
thing goes wrong after refactor
