### ISSUE TITLE
无法使用IPV6地址访问SSH，访问RDP可以

### ISSUE THREAD

**Issue by sanrentai** [1Remote/1Remote#561]
**Describe the bug**
无法使用IPV6地址访问SSH，访问RDP可以
**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: WIN11
 - PRemoteM Version 7.2.8

**Additional context**

**Comment by sanrentai** [comment]
把IPV6的地址，用域名解析以后，可以正常使用ssh

**Comment by VShawn** [comment]
ipv6需要加特殊命令，使用APP协议进行配置。

![image](https://github.com/1Remote/1Remote/assets/10143738/54500d61-08d8-4bae-9026-68a32b62c59f)

原理见：https://documentation.help/PuTTY/using-cmdline-ipversion.html

**Comment by VShawn** [comment]
https://github.com/cyd01/KiTTY/issues/43#issuecomment-524049956

根据这个回答。IPv6用方括号括起来就可以了，能帮我测试一下么？我这里没有Ipv6可以测试

**Comment by sanrentai** [comment]
> [cyd01/KiTTY#43 (comment)](https://github.com/cyd01/KiTTY/issues/43#issuecomment-524049956)
> 
> 根据这个回答。IPv6用方括号括起来就可以了，能帮我测试一下么？我这里没有Ipv6可以测试

这样可以
