### ISSUE TITLE
已启动状态下无法通过任务栏或开始菜单打开主窗口

### ISSUE THREAD

**Issue by lqblln** [1Remote/1Remote#562]
**Describe the bug**
已启动（通知区域有图标）但未打开主窗口的状态下，通过任务栏或开始菜单的程序图标无法打开主窗口，旧的PRemoteM无此问题。

**Expected behavior**
只要主窗口未打开，通过任务栏或开始菜单的程序图标始终能打开主窗口。

**Desktop (please complete the following information):**
 - OS: Windows 11 22H2 22621.2506
 - PRemoteM Version 1.0.0-beta.07 2023-11-12 （微软商店版）

**Comment by VShawn** [comment]
问题点已找到
