### ISSUE TITLE
SSH Private Key cannot be modified in UI

### ISSUE THREAD

**Issue by LazuliKao** [1Remote/1Remote#565]
更新后私钥改不了力，修好了，已提交Pull Request，望采纳
https://github.com/1Remote/1Remote/pull/564

Solution:
DataContext of `SshFormView.xaml` has already been changed to an instance of SshFormViewModel, the previous one (Protocol.SSH) in `New` property. detail ref to pr

不知道别处有没有遗漏的小问题

**Comment by VShawn** [comment]
good job
