### ISSUE TITLE
这个APP是不是会被Windows自动安装？

### ISSUE THREAD

**Issue by SudoShutdownNow** [1Remote/1Remote#566]
今天启动电脑后，突然弹出了这个APP的界面，而我之前从未手动安装过。查看文件发现是微软store版本，创建时间是今天早晨6:11，那会我还没有起床，不可能是我手动安装的。
想问下有其他朋友遇到相同情况吗？还是我电脑中病毒了？想想怪恐怖的。

**Comment by VShawn** [comment]
理论上没有自动安装的可能性。

现在微软商店发布的时候，连允许强制更新的选项都没有，别说安装了。
