### ISSUE TITLE
RDP自动重连后屏幕缩小

### ISSUE THREAD

**Issue by ihorn** [1Remote/1Remote#568]
长时间远程无动作，被对方主动断掉（断掉之前的提示语：会话空闲超出了其时间限制。注销会在两分钟之内开始。要继续会话，请按任何键）。
premote会自动重连，但是显示的屏幕缩小至原来的1/4大小左右（应用是全屏的，对方服务器的桌面缩小在中间、可点可用，桌面四周黑屏）。

**Comment by VShawn** [comment]
感谢反馈，并且我觉得其中的“自动重连”也是不合适的，这种情况应该让用户选择是否重连才对。

**Comment by ihorn** [comment]
可以加两个配置参数：
1、是否自动重连
2、是否保持活动（后台发送数据，模拟动作）

**Comment by VShawn** [comment]
不会再增加配置了，配置太多会增加用户心智负担，我打算就做成断链后显示黑屏，并提供一个按钮可以重连。

**Comment by VShawn** [comment]
在前两次提交中已经修复了这个问题，忘记关联 issue 了
