### ISSUE TITLE
希望能支持代理连接RDP

### ISSUE THREAD

**Issue by czxinc** [1Remote/1Remote#569]
公司的网络需要代理才能访问互联网，但是RDP默认不走系统代理。FreeRDP是支持使用代理连接的，命令如下：
`wfreerdp.exe /v:<远程桌面地址>:<远程桌面端口> /proxy:<代理地址>:<代理端口>`
希望能支持代理连接RDP，谢谢。

**Comment by filwu8** [comment]
你可以自建一个反向代理，可以用这个工具，https://github.com/fatedier/frp
已经我都已经用这个方案稳定跑了好几年了

**Comment by czxinc** [comment]
> 你可以自建一个反向代理，可以用这个工具，https://github.com/fatedier/frp 已经我都已经用这个方案稳定跑了好几年了

我就是在用这个的，在要控制的电脑上建立了反向代理暴露到互联网。是公司的电脑需要控制那台电脑，而公司需要挂代理才能访问互联网

**Comment by filwu8** [comment]
> > 你可以自建一个反向代理，可以用这个工具，https://github.com/fatedier/frp 已经我都已经用这个方案稳定跑了好几年了
> 
> 我就是在用这个的，在要控制的电脑上建立了反向代理暴露到互联网。是公司的电脑需要控制那台电脑，而公司需要挂代理才能访问互联网

还可以在你的电脑上搞个Nginx 做正向代理端口转发，也是一个解决思路

**Comment by VShawn** [comment]
已经有好几个人提这个需求了，然而 RDP 默认就没有 proxy 功能，加起来很麻烦，相对于1Remote里面要内置一个反向代理模块。

所以这个功能一直没有做是因为开发起来很麻烦，而我个人又完全用不到。放着等有缘人来个 PR 或者我什么时候很闲了就会跟进开发。

**Comment by VShawn** [comment]
@czxinc 

现在你可以尝试使用最新nightly 版本中的 APP protocol 启动 freerdp，进而实现代理功能。

如图：

![image](https://github.com/1Remote/1Remote/assets/10143738/36ff79fd-ef80-4253-b232-5170d2fe56c3)
