### ISSUE TITLE
关于名称太长被隐藏掉，导致无法看到后半部分问题

### ISSUE THREAD

**Issue by filwu8** [1Remote/1Remote#570]
比如这样，太长的名称被隐藏

![1700630641977](https://github.com/1Remote/1Remote/assets/54697960/743593ed-b110-4ce4-acac-d9ccfb556747)

**Comment by filwu8** [comment]
功能改进建议参考
1、加鼠标悬停
2、下面增加进度条
3、自动缩进铺满整行

**Comment by VShawn** [comment]
进行了 UI 的优化，把旁边空白的区域利用上了，也添加了 tooltips，能一定程度上缓解问题。

水平滚动条我还是不想做，因为不好看。

建议还是把名字搞短一点
