### ISSUE TITLE
Unable to download 

### ISSUE THREAD

**Issue by gfhdhytghd** [1Remote/1Remote#573]
when I tried to download, I got this:
Please check back later
Error 1027
 This website has been temporarily rate limited

You cannot access this site because the owner has reached their plan limits. Check back later once traffic has gone down.

If you are owner of this website, prevent this from happening again by upgrading your plan on the Cloudflare Workers dashboard.

Learn more about this issue →

**Comment by majkinetor** [comment]
When you try to download from site 1remote.org ?

It redirects to Github releases, so that can't possibly happen.

**Comment by gfhdhytghd** [comment]
on the "nightly release" page ,when I click on "下载", it goes t that page, when I click on the package name, it start download.
