### ISSUE TITLE
开机启动的1Remote和手动运行的1Remote，存在并存问题

### ISSUE THREAD

**Issue by aoaostar** [1Remote/1Remote#576]
**Describe the bug**
开机启动了一个1Remote，如果再次打开一个1Remote，会有两个1Remote同时运行，如果打开第三个则不会启动

**Screenshots**
![1701047959721](https://github.com/1Remote/1Remote/assets/86001674/e5108709-645b-4771-bfc7-7bcb51791b8d)

**Desktop (please complete the following information):**
 - OS: Win11
 - PRemoteM Version 0.7.2.8

**Comment by VShawn** [comment]
奇怪实测未能复现

**Comment by VShawn** [comment]
不过，PRemoteM 属于归档版本了，就算you BUG 也不会再继续修复了。可以考虑升级到 1Remote 版本。
