### ISSUE TITLE
有计划支持在 MacOS 上安装使用吗

### ISSUE THREAD

**Issue by rysinal** [1Remote/1Remote#580]

**Comment by VShawn** [comment]
sorry 没有计划，我的 mac 只有 8G，只是上网本用途，无法用于开发。mac下我用微软官方的远程桌面应用。

**Comment by filwu8** [comment]
> sorry 没有计划，我的 mac 只有 8G，只是上网本用途，无法用于开发。mac下我用微软官方的远程桌面应用。

但是macbook上微软官方的没你的好用，特别是账号管理方面，没有导入导出，不过微软官方的凑合凑合也就习惯了。
macbook上的微软的凭据，还是储存在统一的账号管理系统里的，还不容易倒入导入，安全级别是高了，但是方便性大幅下降
