### ISSUE TITLE
SFTP "edit file"-functionality

### ISSUE THREAD

**Issue by DrBrumm** [1Remote/1Remote#581]
**Is your enhancement related to a problem? Please describe.**
Please consider to implement the WinSCP functionality, to automatically upload files aufter changing them. SFTP an linux machines is mainly used, to change config files. Currently, the files are downloaded to temp as writeprotected, so I can only view them, but even, if I change that in the temp file to then change the  file itself and save it, it does not get uploaded. 

**Describe the solution you'd like**
Download files as writable. Check if the filedate changes, if so, upload them and overwrite on the remote machine.

**Comment by VShawn** [comment]
Hi, only the basic functionality will be supported in our internal SFTP client. I dont have much time and it's unnecessary to build a self-made powerful SFTP client.

If you wonder a `WinSCP functionality` plz just use WinSCPM.

you can launch WinSCP with 1Remote by `protocol runner` or `app protocol` :)

`protocol runner`: http://1remote.org/usage/protocol/runner/

`app protocol`: 

![image](https://github.com/1Remote/1Remote/assets/10143738/9ec9b5ab-c6a0-41ee-a9da-49f06fca0e3a)

work smoothly 👍

![image](https://github.com/1Remote/1Remote/assets/10143738/19df8b91-3287-4a91-a398-8efc796b0992)
