### ISSUE TITLE
批量打开或单个关闭虚拟机会概率性丢失标签

### ISSUE THREAD

**Issue by sibyl2116** [1Remote/1Remote#583]
**所有虚拟机处于已开机未登录状态**

1. 勾选6个Windows虚拟机
2. 选择下方的连接按钮
3. 上方标签在逐个打开每个虚拟机，此时可以看到6个
4. 等到所有虚拟机加载完毕后，标签会有接近1/3的概率只剩下5个，随机消失一个

**所有虚拟机处于已登录过状态**
重复上方步骤，标签丢失概率会下降很多

同样的，当有6个标签打开时，如果关闭其中一个，会有概率性丢失另一个标签

**Comment by VShawn** [comment]
如果只有4台服务器能复现嘛？我只有4台机器能同时开机

**Comment by sibyl2116** [comment]
> 如果只有4台服务器能复现嘛？我只有4台机器能同时开机

刚好系统更新，我尝试了5次开机未登录状态下6台机的批量打开，这个现象暂时没有重复。
我先关闭问题，等以后如果重现，则再重开问题。
