### ISSUE TITLE
ALT+tab组合键无法切换到其他窗口

### ISSUE THREAD

**Issue by 915354482** [1Remote/1Remote#585]
**描述错误**

使用ALT+tab组合键无法切换到其他窗口，需要连续按两次该组合键才会进行一次窗口切换。

**问题复现**

1.打开1remote

2.用默认SSH启动器连接到任意linux的会话

3.按一次ALT+tab组合键

**预期行为**

按一次ALT+tab组合键窗口未发生切换
连续按两次ALT+tab组合键窗口会切换一次

**版本信息**

-操作系统：win11

-PRemoteM版本：1.0.0-beta.07

**Comment by VShawn** [comment]
感谢反馈，但这不算bug来的，软件方案决定了这就是一个特性：

1Remote 通过启动 kitty.exe 子进程并用 1Remote 窗口包裹住 kitty 实现 SSH，所以你使用 SSH 时焦点其实是在 kitty 上而不是在 1Remote 上，按下 alt tab 后，焦点仅仅是从 kitty 转移回到了 1Remote，所以你才感觉没有切换窗口。可以通过长按 alt 再按 tab 来解决这个问题。

可能可以通过系统hook住alt tab来解决这个问题，但我觉得hook行为太具有侵略性，所以不会实施。
