### ISSUE TITLE
Is this legal?

### ISSUE THREAD

**Issue by stetze** [1Remote/1Remote#593]
Remote Desktop Management Software | Security Internet Develop
https://apps.microsoft.com/detail/9N1MF40Q02P0?hl=de-DE&gl=US
 
![image](https://github.com/1Remote/1Remote/assets/73733823/1a4b8754-1751-41a8-8107-fa6e885739d7)

**Comment by majkinetor** [comment]
I expected this.

If there is no source code, its not legal.

**Comment by VShawn** [comment]
There are shameless people in the world.

ANd we are essentially powerless in this regard.

**Comment by majkinetor** [comment]
I reported it to MS via store reporting feature, but I don't expect anything will change. 

Well, it is expected, it is a proof software is good :).

**Comment by VShawn** [comment]
Microsoft Store will not take any action. I reported this app months ago.
