### ISSUE TITLE
VNC password input problem

### ISSUE THREAD

**Issue by ElvenGo** [1Remote/1Remote#594]
Version 1.0.0-beta.07
Built at:2024-01-04T00:34:34.366

When I use the 1Remote as a VNC client login the Redhat Linux6.9.

When entering the VNC login password, pressing any key value will be converted to a character, including Shift, Enter, Backspace, and so on.

**Comment by VShawn** [comment]
The built-in VNC client does not support input method. When the input method is enabled, any input will be converted into characters. This is the reason for my ticket #549.

![image](https://github.com/1Remote/1Remote/assets/10143738/207baf7e-b09d-4306-8afe-f775140055cb)
