### ISSUE TITLE
Not able to print from RDP

### ISSUE THREAD

**Issue by kpetersen6925** [1Remote/1Remote#597]
**Describe the bug**
Not able to print from RDP. Have Printers enabled in the RDP settings. As well as have a program called TSPRint installed.

**To Reproduce**
1. Access RDP
2. Open a PDF
3. Try to print
4. Does not print

**Expected behavior**
Be able to print using tsprint

**Screenshots**
![image](https://github.com/1Remote/1Remote/assets/89929383/5139234b-f4a0-4ecd-9de7-97d19113c8c8)

![image](https://github.com/1Remote/1Remote/assets/89929383/96218182-6687-4765-94d5-e7e7d9b5ba1e)

**Desktop (please complete the following information):**
 - OS: Windows 11 22H2
 - PRemoteM Version 0.7.2.8

**Additional context**

**Comment by kpetersen6925** [comment]
It will print if mstsc mode is enabled though.

**Comment by VShawn** [comment]
It maybe be some printer parameters were incorrectly set when the RDP started, but I'm sorry I cannot fix the issue since I do not have a physical printer.
