### ISSUE TITLE
 Runner for VNC  ``` {   "$type": "ExternalRunner",   "Params": {},   "ExePath": "C:\\Program Files\\WindowsApps\\16536Shawn.V.Workshop.PRemoteM_1.0.92.0_neutral__c5279amkf5zgy\\Ui\\1Remote.exe",   "IsExeExisted": true,   "Arguments": "%1RM_HOSTNAME%::%1RM_PORT% -password=%1RM_PASSWORD% -scale=auto",   "RunWithHosting": true,   "EnvironmentVariables": [     {       "Key": "VNC_PASSWORD",       "Value": "%1RM_PASSWORD%"     }   ],   "Name": "TightVNC",   "OwnerProtocolName": "VNC" } ```

### ISSUE THREAD

**Issue by dannyglaze83** [1Remote/1Remote#600]
**Download link of the external app form its official website**

Give the runner's official website link here.

**Copy your runner config here**

Steps to get config

1. Open Options of App
2. Go to `Protocol` page
3. Select the runner you want to share
4. Click the share button next to the delete button.
5. Back to here and  `Ctrl` + `V`

**Screenshot**
(optional)

Give some screenshots when the runner is running if you are so kind.

**Additional context**
Add any other context about the runner here.

**Comment by VShawn** [comment]
well I think it is an invalid configuration sice it has `"ExePath": "C:\\Program Files\\WindowsApps\\16536Shawn.V.Workshop.PRemoteM_1.0.92.0_neutral__c5279amkf5zgy\\Ui\\1Remote.exe"`. Please revise your ticket. @dannyglaze83
