### ISSUE TITLE
alt + m 快速启动功能优化建议

### ISSUE THREAD

**Issue by aacc668** [1Remote/1Remote#606]
问题描述：
当使用快捷键打开已经打开的 RDP 连接时，会导致重复连接 RDP 服务，在界面上表现为出现"你已断开连接，因为已与远程计算机建立了另外一个连接"的提示。
![image](https://github.com/1Remote/1Remote/assets/74100166/1a8d81e4-5613-4e6d-9df8-fc5a1d9022b0)

期望的改进：
希望通过优化操作行为，当已经存在连接时，不再进行重复连接，而是直接打开已存在的标签页。

附加信息：
操作系统：Windows11
客户端版本：1.0.0-beta.07 built at:2023-11-23T19:15:30.138

**Comment by VShawn** [comment]
“当已经存在连接时，不再进行重复连接，而是直接打开已存在的标签页。”这个功能从0.1测试版就有了。

我刚才实测了以下，在最新版本下，这个功能也是正常的。

可以描述一下如何复现你描述的问题么？

测试录屏：
![recording](https://github.com/1Remote/1Remote/assets/10143738/02b17b1e-06da-4b4f-abd6-b00b93bb600e)

**Comment by aacc668** [comment]
![EasyGIF-1706933812876](https://github.com/1Remote/1Remote/assets/74100166/82082337-aee0-4c13-bac7-e428bfad04de)
感谢回复，GIF为我操作的全流程，下载渠道Microsoft Store

**Comment by aacc668** [comment]
我尝试了下使用Releases 里的这个构建版本，没有重复连接问题。1Remote-1.0.0.0-beta.07-net6-x64-nightly-20240131-6155b4.zip
Microsoft Store下载的版本才有重复连接问题

**Comment by VShawn** [comment]
哦哦，微软商店的软件更新是全手动的很麻烦，所以有段时间没更新了。等我有空了就构建一版上去更新。

**Comment by aacc668** [comment]
好的非常感谢
