### ISSUE TITLE
memory leak after long time RDP connection

### ISSUE THREAD

**Issue by ihorn** [1Remote/1Remote#607]
**Describe the bug**
长时间运行（有一个远程桌面保持连接），大约3-5天，内存占用达到16G空间。
具体数据可见图片。
![PixPin_2024-01-31_10-01-50](https://github.com/1Remote/1Remote/assets/17956055/33dca32f-a030-49d3-8c8c-d67160fb5cac)

**Comment by ihorn** [comment]
rdp 没有启动mstsc模式

**Comment by VShawn** [comment]
挂机12小时后，两台测试机器都没有复现内存泄漏，继续观察

![image](https://github.com/1Remote/1Remote/assets/10143738/7934b989-ca3d-40e7-ad49-f422afb4aed7)

![image](https://github.com/1Remote/1Remote/assets/10143738/4ed8b582-f56f-4baa-962d-7c2662dafd43)
