### ISSUE TITLE
批量编辑功能希望能够添加修改协议的功能啊！也希望可以支持批量导入SSH服务器信息功能！

### ISSUE THREAD

**Issue by coinlist-whale** [1Remote/1Remote#608]
**Is your enhancement related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
Add any other context or screenshots about the enhancement here.

**Comment by VShawn** [comment]
1. 批量编辑修改协议有风险，可能会有字段冲突，所以没加这个功能。
2. SSH 有办法可以批量导入，你照着这个csv填ssh的信息，再点从 mRemoteNG csv 导入就行了。

[import_csv_demo.csv](https://github.com/1Remote/1Remote/files/14138810/import_csv_demo.csv)
