### ISSUE TITLE
1.0.0 BETA: Apps are not running

### ISSUE THREAD

**Issue by t-ru** [1Remote/1Remote#612]
Apps are not running.

To Reproduce
1. Create a connectiion with type "app".
2. Exe path: cmd.exe
3. Execute the connection
4. Tray Message: Availability detection: We are not able to connect to...

If I create a App with parameters and i click to test... all is working fine. If I try to execute the saved connection... ERROR

Affected versions
All versions since switch from PRemote to 1Remote

**Comment by majkinetor** [comment]
I confirm this doesn't work both with name and full path.
