### ISSUE TITLE
1.0.0 BETA: Custom SFP Runners not working

### ISSUE THREAD

**Issue by t-ru** [1Remote/1Remote#614]
Password, Private Key and Username are not correctly passed to WinSCP runners.

**Configured SFTP Runner**
Delivered WinSCP Runner... unchanged.

**To Reproduce**
1. Create SFTP Connection with Runner WinSCP
2. Test... all is working fine.
3. Close 1Remote
4. Exit the 1Remote tray icon
5. Open 1 Remote

Test Connection... Error Message from WinSCP...  Host "value of %1RM_USERNAME%" does not exist.
Edit Connection... Do not make any changes. Exit edit mode with cancel.
Test Connection... all is working fine.

**Affected versions**
All versions since switch from PRemote to 1Remote

**Comment by VShawn** [comment]
thx for alert, I found that when the `Hosting` option is not checked, the custom runner will have issues, I did not test the case `Hosting = FALSE` after development is completed, BUT.. 

i FIXed it now.

![image](https://github.com/1Remote/1Remote/assets/10143738/18e43188-daf4-41f0-9feb-9d3f7fb381ac)



But the error I encountered here did not prompt Host `Host "value of %1RM_USERNAME%" does not exist.`, but another error, so please check if the problem you encountered has been resolved.
