### ISSUE TITLE
1.0.0 BETA Build 20240220-0d35db creates wrong json

### ISSUE THREAD

**Issue by t-ru** [1Remote/1Remote#615]
**Describe the bug**
Creating SSH Runner with UI resulting in wrong SSH.json

**To Reproduce**
SSH Runner "Plink on Windows Terminal" created.

exe path: wt.exe

Login with pw: -w 1 new-tab --title \"%1RM_HOSTNAME%\" --suppressApplicationTitle plink -ssh %1RM_HOSTNAME% -P %1RM_PORT% -%SSH_VERSION% -C -X -no-antispoof -l %1RM_USERNAME% -pw %1RM_PASSWORD%

Login witjh private key: -w 1 new-tab --title \"%1RM_HOSTNAME%\" --suppressApplicationTitle plink -ssh %1RM_HOSTNAME% -P %1RM_PORT% -%SSH_VERSION% -C -X -no-antispoof -l %1RM_USERNAME% -i %1RM_PRIVATE_KEY_PATH%

Result:

![image](https://github.com/1Remote/1Remote/assets/3688520/cc32b692-344b-4a95-80f1-118ea13567c1)

.... red is wrong 

All runners affected.

**Comment by VShawn** [comment]
sorry Where is the wrong? I couldn't find the mistake. Value in the two `ArgumentsForPrivateKey` seem to be the same. Please help me identify where the `wrong json` is.


FYI: The two `ArgumentsForPrivateKey` is a technical debt left over from the upgrade of PRM to 1RM. `Params` will be removed after the official version is released.
