### ISSUE TITLE
sftp window support local files 

### ISSUE THREAD

**Issue by caoguosong** [1Remote/1Remote#619]
可否在sftp窗口中增加本地文件的分栏内容，类似winscp和bitvise ssh client的sftp window（个人觉得这个体验最好，比winscp还好）

然后就可以增加拖拽、远程编辑等功能。

**Comment by VShawn** [comment]
抱歉，尽管最初计划是要做本地文件分栏的，但最终我发现我没有足够的时间去雕琢一个完善的SFTP客户端，这个功能对我而言工作量太大了。所以我现在自己是将 winscp 嵌入到 1Remote 中使用。
