### ISSUE TITLE
希望增加主题根据系统主题切换

### ISSUE THREAD

**Issue by YanZhiwei** [1Remote/1Remote#620]
类似office软件，Windows是切换深色主题的时候，主题也能跟着切换
![image](https://github.com/1Remote/1Remote/assets/7938690/5fddbd75-aa0b-4893-bcae-d5178bf6e8f0)

**Comment by VShawn** [comment]
之前忘记回复了，不想做这个功能的原因是，这个小功能要引入UWP的一系列库，使程序的体积再增加几十兆，我个人这方面有点洁癖，所以不想加入体积很大的库。
