### ISSUE TITLE
是否可以增加分组功能？

### ISSUE THREAD

**Issue by stardance** [1Remote/1Remote#621]
目前软件的所有远程项目都是以列表形式排列的，如果远程项目过多，查询起来会比较麻烦，看起来也比较凌乱。
    如果有分组功能，可以大大提高查找远程项目的速率，视觉上也比较和谐。

**Comment by VShawn** [comment]
![image](https://github.com/1Remote/1Remote/assets/10143738/002eeb56-b426-4ee1-b648-0ce28151f7ae)

目前已有分组功能。
