### ISSUE TITLE
串口功能最新版彻底不能使用了   

### ISSUE THREAD

**Issue by Hi-360** [1Remote/1Remote#623]
2024.02.20串口功能还能使用，现在最新更新的已经不能使用了 。我的系统环境是win10     在win11上一直都不能使用串口功能· 希望楼主能够尽快修复  现在1remote已经是主力工具了
![image](https://github.com/1Remote/1Remote/assets/99636954/2e15f2a1-4516-45bb-a9b4-ef2aa969b08a)

**Comment by VShawn** [comment]
奇怪了，今年以来串口协议相关的代码完全没有动过。

不过事实上我正在考虑移除串口协议，以后所有串口协议需求用户可以通过APP协议自行实现。

**Comment by Hi-360** [comment]
> 奇怪了，今年以来串口协议相关的代码完全没有动过。
> 
> 不过事实上我正在考虑移除串口协议，以后所有串口协议需求用户可以通过APP协议自行实现。

我也觉得很奇怪

**Comment by Hi-360** [comment]
这个问题  最近更新的版本中修复了吗？

**Comment by VShawn** [comment]
没有改，没有调试环境，无法修复。

**Comment by Hi-360** [comment]
已经好了   串口也能正常使用了  感谢作者







| |
njfb1029
|
|
***@***.***
|
---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年3月27日 14:58 |
| 收件人 | ***@***.***> |
| 抄送人 | Wu ***@***.***>,
***@***.***> |
| 主题 | Re: [1Remote/1Remote] 串口功能最新版彻底不能使用了 (Issue #623) |

Closed #623 as completed via b183078.
