### ISSUE TITLE
所有RDP条目突然全部消失（数据库路径在非系统盘）／加入自定义显示本地分区

### ISSUE THREAD

**Issue by ubean2018** [1Remote/1Remote#626]
版本：store版，1.0.0 beta 07
系统：Win10 22H2 19045.3208（只用与局域网RDP）
所有加入的RDP条目突然全部消失，一个不剩（数据库路径在非系统盘）。

共享到远程的本地磁盘勾选后，所有的分区都显示出来了。
希望如微软远程桌面一样，可以自定义选择需要显示的分区。
![image](https://github.com/1Remote/1Remote/assets/39214887/3e16ecae-bd22-413b-8ef8-d3813791f498)

**Comment by VShawn** [comment]
> 所有加入的 RDP 条目突然全部消失，一个不剩

这个问题比较严重，检查一下几种可能：
- 数据库路径是不是发生了篡改？
- 数据库文件路径是不是被删掉了？（查看数据库的创建时间是否和1Remote的安装时间匹配）

> 希望如微软远程桌面一样，可以自定义选择需要显示的分区。

以前尝试过要实现这个功能，但实现起来太麻烦了，要通过系统API读取磁盘的ID再连接到RDP上，折腾到一半就懒得做了，以后估计也不会再增加了，除非有人PR这个功能出来。

**Comment by ubean2018** [comment]
> > 所有加入的 RDP 条目突然全部消失，一个不剩
> 
> 这个问题比较严重，检查一下几种可能：
> 
> * 数据库路径是不是发生了篡改？
> * 数据库文件路径是不是被删掉了？（查看数据库的创建时间是否和1Remote的安装时间匹配）
> * 打开数据库文件看看表里面的数据又几条。
谢谢回复 :-)
因默认数据库在系统盘，我导入需要的RDP项目后，将数据库复制到E盘，并改了路径。
记得软件是常驻后台使用的，当时alt-m发现没有条目，打开主窗口，发现全部消失，看了E盘1Remote.db的修改时间是当时发生的时间。
如果下次遇到，我再按你的方法检查。

**Comment by ubean2018** [comment]
> > 所有加入的 RDP 条目突然全部消失，一个不剩
> 
> 这个问题比较严重，检查一下几种可能：
> 
> * 数据库路径是不是发生了篡改？
> * 数据库文件路径是不是被删掉了？（查看数据库的创建时间是否和1Remote的安装时间匹配）
> * 打开数据库文件看看表里面的数据又几条。
> 
> > 希望如微软远程桌面一样，可以自定义选择需要显示的分区。
> 
> 以前尝试过要实现这个功能，但实现起来太麻烦了，要通过系统API读取磁盘的ID再连接到RDP上，折腾到一半就懒得做了，以后估计也不会再增加了，除非有人PR这个功能出来。

谢谢回复 :-)
因默认数据库在系统盘，我导入需要的RDP项目后，将数据库复制到E盘，并改了路径。
记得软件是常驻后台使用的，当时alt-m发现没有条目，打开主窗口，发现全部消失，看了E盘1Remote.db的修改时间是当时发生的时间。
如果下次遇到，我再按你的方法检查。

**Comment by VShawn** [comment]
暂时关闭
