### ISSUE TITLE
Minimalize window caption bar option

### ISSUE THREAD

**Issue by tj57** [1Remote/1Remote#628]
I propose adding a minimization option in config for windows caption bar, eg. Use minimalized caption bar
In main/config window can be same as now, but in connection window can be two choices
What do you think ?

Like this
![image](https://github.com/1Remote/1Remote/assets/20434907/4ef5d8fb-e042-4719-9e60-72009f9b3ad9)

**Comment by VShawn** [comment]
Why do we need a minimize button next to the title? I don't see the benefit of doing that. The button will only occupy the space of the title bar.
