### ISSUE TITLE
Suggestion: setting to prevent locking of a remote session/desktop

### ISSUE THREAD

**Issue by rafi-d** [1Remote/1Remote#629]
Hi,
This is just an idea take from M$ Remote Desktop app...:
Add an option to prevent inactivity  timeout/lock  of your remote PC session(s).  This is how it looks in M$ app store app:
![image](https://github.com/1Remote/1Remote/assets/2458280/1051c9f6-c38a-4539-ad47-f12688009e5d)

This will make accessing PCs easier/faster if they will not time out on you and lock

Thanks

**Comment by VShawn** [comment]
well I haven't found the docs on how to implement this feature at the moment. The ticket will be continue to make progress once I find further information.

**Comment by VShawn** [comment]
can't find any solution for change time out setting of the server over RDP. I will close the ticket for now.
