### ISSUE TITLE
Add Wake On LAN capability for a PC connected over LAN (optionally also remote)

### ISSUE THREAD

**Issue by rafi-d** [1Remote/1Remote#630]
We find ourselves in situation where the remote is down for some reason. This can be due to sleep or shutdown.

As a solution - we can use the WOL feature to it's MAC address.  I think this can be useful here , as it is implemented in TeamViewer as well.

To implement - you need the MAC address, which the app  can find automatically during the connection. It can also be entered manually (less convenient, but possible) . 

I suggest to add this to the context menu of a OC, as well as to it's setting - as an edit-field that will be populated automatically.

This will work on LAN connections (same subnet). On a remote connection - it will work only through an already connected PC on the same subnet (can be deduced from it's local IP) , so - is a bit more complicated, but possible.

Thanks!

**Comment by VShawn** [comment]
The built-in WOL feature is currently not in the plan.

But you can adding WOL by following:  https://github.com/1Remote/1Remote/discussions/365
