### ISSUE TITLE
3.16发布的1remote无法连接到ssh

### ISSUE THREAD

**Issue by Hi-360** [1Remote/1Remote#631]
![image](https://github.com/1Remote/1Remote/assets/99636954/bd3c2e13-7409-46c6-b5c0-3639d8e903da)
楼主遇到一个bug  这个版本无法试用ssh连接到linux系统，前面的还可以连接   希望能够进行修复。我使用其他的远程工具可以正常连接

**Comment by VShawn** [comment]
别闹。我天天用着 SSH 呢

**Comment by VShawn** [comment]
感觉是你电脑环境出问题了，串口也用不了。

**Comment by Hi-360** [comment]
> 感觉是你电脑环境出问题了，串口也用不了。

你说的和这个问题引起了我的深思  我来把系统重装看看

**Comment by Hi-360** [comment]
我刚才电脑系统重装了   rdp可以用  但是ssh依然没法用  表示很无奈

**Comment by VShawn** [comment]
![image](https://github.com/1Remote/1Remote/assets/10143738/6b8477fc-ab98-4140-8b2b-2e22d09c2da4)

你先直接启动这个kitty看能不能用ssh吧，1Remote 也只是调用了这个程序而已。

用命令

`kitty_portable_1Remote.exe -ssh 192.168.1.123 -P 22 -l root -pw password -2`

可以直接启动SSH。

**Comment by Hi-360** [comment]
> ![image](https://private-user-images.githubusercontent.com/10143738/316747144-6b8477fc-ab98-4140-8b2b-2e22d09c2da4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE0MzQzMDYsIm5iZiI6MTcxMTQzNDAwNiwicGF0aCI6Ii8xMDE0MzczOC8zMTY3NDcxNDQtNmI4NDc3ZmMtYWI5OC00MTQwLThiMmItMmUyMmQwOWMyZGE0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI2VDA2MjAwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdkYTJkM2RiYTEzNTc2ZWI2MGY0YzRmNWY5ZTBmZWRlYzc3ODFhYjg4ZmVlMTlmMWMxOWEzZDBiOTE4YmVhZDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.pvS-ZoYduwjPd_s8ZVmjY2Eb7o7jKdbdplveFh-sUVE)
> 
> 你先直接启动这个kitty看能不能用ssh吧，1Remote 也只是调用了这个程序而已。
> 
> 用命令
> 
> `kitty_portable_1Remote.exe -ssh 192.168.1.123 -P 22 -l root -pw password -2`
> 
> 可以直接启动SSH。

ssh可以连接上去 

https://github.com/1Remote/1Remote/assets/99636954/0956d4e9-554a-4c48-aed4-3d6527474167

**Comment by VShawn** [comment]
那通过 1Remote 连接是什么样子的呢？有截图么

**Comment by Hi-360** [comment]
![image](https://github.com/1Remote/1Remote/assets/99636954/497415bf-730e-4fef-975d-3523da2cee5c)
这个样子

**Comment by wyx176** [comment]
> ![image](https://private-user-images.githubusercontent.com/99636954/316781575-497415bf-730e-4fef-975d-3523da2cee5c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE0NzkyNTEsIm5iZiI6MTcxMTQ3ODk1MSwicGF0aCI6Ii85OTYzNjk1NC8zMTY3ODE1NzUtNDk3NDE1YmYtNzMwZS00ZmVmLTk3NWQtMzUyM2RhMmNlZTVjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI2VDE4NDkxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRhZWJhOTIxMDE0MjJjMzMxOTk3ZTA5YzNjYTY3NmYwZWU5YmYzMzkxODRiM2FhMTk0NjlmYjVhN2ZhNmQ2MzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.vTI6UOpDH4vHnKUPhGC2OgZQBFN3nb1PPqH6D_qq0yQ) 这个样子

巧了 我也是这样子的 但sftp连接是正常的

**Comment by sunven** [comment]
> ![image](https://private-user-images.githubusercontent.com/99636954/316781575-497415bf-730e-4fef-975d-3523da2cee5c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE1MDM5MjIsIm5iZiI6MTcxMTUwMzYyMiwicGF0aCI6Ii85OTYzNjk1NC8zMTY3ODE1NzUtNDk3NDE1YmYtNzMwZS00ZmVmLTk3NWQtMzUyM2RhMmNlZTVjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI3VDAxNDAyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcwZjgyYmExNzFkOTdiMTdiODcxYjlhNmExOTA1MDc3MmQwNDU0NzIyNzg3Yjg2MWM5Nzk1OGVhYjYzMzEzOTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.W2eVWCLBgxGlDoVPBsjuwh_c9Bw5MjXP_gC-i-puwLg) 这个样子

choco 安装的 1.0.0.20240316，sftp正常，ssh一样连不上

**Comment by VShawn** [comment]
> > ![image](https://private-user-images.githubusercontent.com/99636954/316781575-497415bf-730e-4fef-975d-3523da2cee5c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE1MDM5MjIsIm5iZiI6MTcxMTUwMzYyMiwicGF0aCI6Ii85OTYzNjk1NC8zMTY3ODE1NzUtNDk3NDE1YmYtNzMwZS00ZmVmLTk3NWQtMzUyM2RhMmNlZTVjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI3VDAxNDAyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcwZjgyYmExNzFkOTdiMTdiODcxYjlhNmExOTA1MDc3MmQwNDU0NzIyNzg3Yjg2MWM5Nzk1OGVhYjYzMzEzOTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.W2eVWCLBgxGlDoVPBsjuwh_c9Bw5MjXP_gC-i-puwLg) 这个样子
> 
> choco 安装的 1.0.0.20240316，sftp正常，ssh一样连不上
> 
> 1Remote\kitty 目录是空的，和这个有关？

应该和这个有关，我手动删除了 Kitty 目录，终于复现了这个问题，感谢提供了关键信息。

**Comment by Hi-360** [comment]
> > > ![image](https://private-user-images.githubusercontent.com/99636954/316781575-497415bf-730e-4fef-975d-3523da2cee5c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE1MDM5MjIsIm5iZiI6MTcxMTUwMzYyMiwicGF0aCI6Ii85OTYzNjk1NC8zMTY3ODE1NzUtNDk3NDE1YmYtNzMwZS00ZmVmLTk3NWQtMzUyM2RhMmNlZTVjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI3VDAxNDAyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcwZjgyYmExNzFkOTdiMTdiODcxYjlhNmExOTA1MDc3MmQwNDU0NzIyNzg3Yjg2MWM5Nzk1OGVhYjYzMzEzOTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.W2eVWCLBgxGlDoVPBsjuwh_c9Bw5MjXP_gC-i-puwLg) 这个样子
> > 
> > 
> > choco 安装的 1.0.0.20240316，sftp正常，ssh一样连不上
> > 1Remote\kitty 目录是空的，和这个有关？
> 
> 应该和这个有关，我手动删除了 Kitty 目录，终于复现了这个问题，感谢提供了关键信息。

我重新下载3.16号发布的1remote 发现kitty目录确实是空的

**Comment by VShawn** [comment]
应该修好了。

**Comment by Hi-360** [comment]
可以正常ssh了  串口也能使用了


| |
njfb1029
|
|
***@***.***
|
---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年3月27日 15:25 |
| 收件人 | ***@***.***> |
| 抄送人 | Wu ***@***.***>,
***@***.***> |
| 主题 | Re: [1Remote/1Remote] 3.16发布的1remote无法连接到ssh (Issue #631) |

应该修好了。
