### ISSUE TITLE
希望launcher窗口可以支持SSH和FTP等配置的快速切换；希望支持窗口分屏；

### ISSUE THREAD

**Issue by JerryRun** [1Remote/1Remote#633]

**Comment by VShawn** [comment]
配置的快速切换是指？



![image](https://github.com/1Remote/1Remote/assets/10143738/6a849a76-f75c-4da4-95c5-b203783958ad)

**Comment by JerryRun** [comment]
您好，我添加配置的时候默认选中的是SSH，这里显示的也就是默认协议，如果想打开一个SFTP的窗口，还需要进配置页面把默认配置改成SFTP，我想能不能这里可以支持切换协议，又不影响默认的，谢谢！


| |
chenshujun7x
|
|
***@***.***
|
---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年3月28日 09:38 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***>,
***@***.***> |
| 主题 | Re: [1Remote/1Remote] 希望launcher窗口可以支持SSH和FTP等配置的快速切换；希望支持窗口分屏； (Issue #633) |

配置的快速切换是指？

image.png (view on web)

**Comment by qq8554650** [comment]
这也是我需要的
1、连接ssh，不一定需要sftp
2、如果需要，希望有按钮或快捷键直接打开（对标xshell）

**Comment by XUE-SHUAI** [comment]
连接ssh的时候，有个按钮直接打开sftp用户传文件

**Comment by qq8554650** [comment]
> 连接ssh的时候，有个按钮直接打开sftp用户传文件
夜版找到了，谢谢。
