### ISSUE TITLE
分辨率设置需要优化

### ISSUE THREAD

**Issue by ssliuan** [1Remote/1Remote#634]
我使用的笔记本电脑屏幕分辨率为3000*2000，放大200%显示。远程桌面设置为屏幕分辨率时分辨率过高，显示内容无法看清。设置为固定分辨率时，只会显示在屏幕中间一小块不能自动拉伸还是看不清。无法好好使用。
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Win10 Pro 2004]
 - PRemoteM Version [e.g. 0.4.6.20071234]

**Additional context**

**Comment by VShawn** [comment]
![image](https://github.com/1Remote/1Remote/assets/10143738/32edfcbe-9d7a-44e3-abe0-59fe62eb5f58)

自动缩放没有生效么？

![image](https://github.com/1Remote/1Remote/assets/10143738/08107b2b-644d-48da-a390-6d73034f7907)

手动设定缩放系数为 200% 呢？




P.S. 不支持Win7 Win2008

**Comment by ssliuan** [comment]
哪可能是我服务器比较老了，好几台机器还是Windows server 2008 R2。













在 2024-03-28 09:36:15，"VShawn" ***@***.***> 写道：

image.png (view on web)

自动缩放没有生效么？

image.png (view on web)

手动设定缩放系数为 200% 呢？

P.S. 不支持Win7 Win2008

**Comment by VShawn** [comment]
那没办法，Win2008系统不支持这个功能。
