### ISSUE TITLE
希望增加一个启动软件时的密码保护功能保护安全 

### ISSUE THREAD

**Issue by qiaoba1024** [1Remote/1Remote#636]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by VShawn** [comment]
1Remote 不会提供启动密码功能，请在离开电脑时将 Windows 锁定以保证系统安全。

同时勾选安全选项将进一步加强安全性。

![image](https://github.com/1Remote/1Remote/assets/10143738/b38331a3-e96e-4276-b17b-b4627056c357)
