### ISSUE TITLE
Ping IPv6 failed

### ISSUE THREAD

**Issue by SongzqInChina** [1Remote/1Remote#637]
IPv6：网络联通性检查时会误报可以联通的IPv6地址无法连接
![屏幕截图 2024-03-27 211132](https://github.com/1Remote/1Remote/assets/142714722/c4afab0d-5189-4448-a6fa-a7d55dd44f4f)
![屏幕截图 2024-03-27 211212](https://github.com/1Remote/1Remote/assets/142714722/91c2d588-e627-48b7-bc07-ead1215676ea)

**Comment by VShawn** [comment]
可能是当前ping方法不支持ipv6，因为我也没测试过，我自己这边没有任何ipv6的环境，要等什么时候给我升级了ipv6才能往下推进了。

**Comment by ZiXia1** [comment]
> 可能是当前ping方法不支持ipv6，因为我也没测试过，我自己这边没有任何ipv6的环境，要等什么时候给我升级了ipv6才能往下推进了。

可以尝试用手机移动网络开热点给电脑看看能否拥有IPv6
