### ISSUE TITLE
增加同步操作功能

### ISSUE THREAD

**Issue by KennyLeung** [1Remote/1Remote#638]
我的局域网内有50台win10虚拟机，经常要执行相同的任务，需要一台一台去操作，重复的动作，效率非常低，每天无意义耗费生命。考虑过写脚本自动化执行，但任务每天有变化，写脚本的速度跟不上任务变化的速度。如果能够实现我只操作一台虚拟机，其余49台虚拟机自动跟随我的操作执行，即把我的操作过程的键盘和鼠标动作复制给其余49台，那将大大提升效率。

**Comment by VShawn** [comment]
本程序致力于解决个人远程控制的统筹问题，并非运维群控程序，因此不提供批量操作功能，这种需求建议改用专业的运维工具，甚至一些课堂群控工具也能满足你的这个需求。

**Comment by KennyLeung** [comment]
> 本程序致力于解决个人远程控制的统筹问题，并非运维群控程序，因此不提供批量操作功能，这种需求建议改用专业的运维工具，甚至一些课堂群控工具也能满足你的这个需求。

感谢回复。
我是用于测试新开发或改动过的网页。50台虚拟机安装了不同类型、不同版本的浏览器。我的任务是尽可能快速地发现网页的兼容性问题。
我熟悉python，对.net略懂皮毛，打算自行修改你这个程序。如果可能，请告知修改的方向或线索，谢谢。

**Comment by VShawn** [comment]
> 尽可能快速地发现网页的兼容性问题。

那你应该通过脚本解决这个问题。

1. 写个 host，host 可以A打开本机浏览器，访问指定网页，B接收外部发来的任务，C系统截图，D发送鼠标移动。
2. 写个 server 负责分发任务，具体说就是告诉host要测试哪些网址。
3. host 在 50 台机器上部署，配置好打开不同浏览器的方法
4. server 发布要测试的网址，比如说 50 个 url + 每个url的鼠标移动参数
5. 各个 host 接收到 50 个url 后，依次根据配置打开url移动鼠标并截图（可能需要gif截图），截图发回 server机。
6. 半小时后你上server机的截图文件夹，审查各个截图。

感觉按键精灵就能完成大部分工作。

**Comment by VShawn** [comment]
> 不知道通过截获MSTSCLib的控件发往虚拟机的通信内容，然后把这些内容转发给其它虚拟机是否可行。

应该是可行的，我似乎见过基于RDP的群体控制系统，但现在找不到在哪了，而且那个是闭源的商业APP。
