### ISSUE TITLE
不支持sudo rz和sudo sz命令

### ISSUE THREAD

**Issue by Leeee1998** [1Remote/1Remote#639]
1. 目前不支持sudo rz和sudo sz命令，如果支持这个命令的话上传和下载文件就方便了。
2. 背景字体的颜色稍微看起来有点费劲，需要调整下字体颜色。

**Comment by VShawn** [comment]
遗憾 RZ 和 SZ 我无能为力，调用的是KITTY，如果KITTY不支持我也没办法给你加这个功能。

字体可以在这里改主题

![image](https://github.com/1Remote/1Remote/assets/10143738/c62da880-2b14-4b3d-abac-f3a322cfe5f4)
