### ISSUE TITLE
Add Grouping

### ISSUE THREAD

**Issue by CrazyBebop** [1Remote/1Remote#641]
This program is awesome! Thanks for the hard work!

I think this should be a nice feature to have, to be able to make groups within the main window, so you can separate by personal, work, etc.

**Comment by majkinetor** [comment]
You should use tags.

**Comment by VShawn** [comment]
Maybe I should have given more tips for the tag system... There are a lot of requests for groups

**Comment by majkinetor** [comment]
@VShawn yeah, definitelly documentation problem
