### ISSUE TITLE
I can't use the FTP via WinSCP

### ISSUE THREAD

**Issue by RendongGG** [1Remote/1Remote#642]
I can use WinSCP to connect to the ftp service.
![20240329151955](https://github.com/1Remote/1Remote/assets/16473195/55b30e0a-9edf-4788-9009-084baf9d3ca1)

This software cannot connect to the FTP service.
ls: arithmetic operation resulted in an overflow

![20240329152048](https://github.com/1Remote/1Remote/assets/16473195/5d0d0d48-43e5-45e6-ae55-760d1efa21f4)
![20240329152846](https://github.com/1Remote/1Remote/assets/16473195/fbbfe782-3eb9-4f2e-9905-b3e58c833736)

**Comment by VShawn** [comment]
maybe you're not set winscp as the runner of FTP?  the screenshoot you gave is the internal FTP runner

**Comment by RendongGG** [comment]
It‘s FTP, not SFTP .
Winscp is supported by both, but 1Remote  is not.

**Comment by VShawn** [comment]
of couse we do support FTP via WinSCP

![image](https://github.com/1Remote/1Remote/assets/10143738/04e1d5b8-02e0-4f2f-8bce-c1c84c399651)
