### ISSUE TITLE
希望增加SSH窗口右键菜单时候能快捷链接SFTP

### ISSUE THREAD

**Issue by wyx176** [1Remote/1Remote#643]
虽然在配时候能够选连接时候同时打开sftp 

但有时候sftp又用不着

希望能够在ssh口右键tab选项中增加一个打开sftp的选项

![image](https://github.com/1Remote/1Remote/assets/32320103/e1da5501-f114-422c-85cb-6caae69675c7)

**Comment by VShawn** [comment]
完成
