### ISSUE TITLE
请问VNC怎么全屏

### ISSUE THREAD

**Issue by jingouwangzi** [1Remote/1Remote#644]
linux机器上安装vnc server，然后连接之后没有全屏选项，只能最大化窗口。请问能否设置全屏？

**Comment by VShawn** [comment]
内置的VNC客户端不支持设置全屏

你可以改用TightVNC，注意不要勾选hosting

![image](https://github.com/1Remote/1Remote/assets/10143738/1000f686-6fd3-489f-a6ce-4fc1168583f2)

![image](https://github.com/1Remote/1Remote/assets/10143738/8c444f2d-e57d-45ea-93a9-28a1da180172)
