### ISSUE TITLE
有mysql连接配置时候协议那块的配置能不能也同步到数据库中

### ISSUE THREAD

**Issue by wyx176** [1Remote/1Remote#646]
1、协议这块不用实时同步，可以在首次配置连接数据库时候同步一次，或者在协议那边增加一个同步协议配置的按钮，一般情况下同公司的人用的管理软件基本都是差不多的，命令行参数基本都一样。

2、不然在新电脑或者给其他人时候都要给他们重新弄一次，很麻烦，，exe路径那一项无所谓，其他人同步了，只要让改成他们电脑本地有的就行了。

![image](https://github.com/1Remote/1Remote/assets/32320103/04771ed6-b083-496c-bee2-53a40d75ee85)

**Comment by VShawn** [comment]
协议配置不准备做任何同步功能

> 不然在新电脑或者给其他人时候都要给他们重新弄一次，很麻烦

公司环境下通过域控组策略，统一下发1Remote及其配置，同时同步安装vncview.exe，通过组策略安装的exe都有统一的路径，每个用户不必修改成自己的路径。
