### ISSUE TITLE
Release the keyboard when mouse leaves the remote desktop window

### ISSUE THREAD

**Issue by ElvenGo** [1Remote/1Remote#648]
It is recommended that when the mouse pointer leaves the remote desktop, release the mouse to return to the local host.

**Comment by VShawn** [comment]
oh? sorry I didn't quite understand how it works. When the mouse pointer leaves the remote desktop, is it in a pressed state? Is that why we have to `release the mouse` to return to the local host?

**Comment by majkinetor** [comment]
I initially thought this too, but testing it now, I can't see what the problem is about.

**Comment by ElvenGo** [comment]
Sorry, maybe I didn't make it clear enough.
I want the keyboard to be released when I move the mouse pointer back the taskbar on the local host.
Currently I have to click the mouse to release the keyboard from the remote host.

![20240415172520](https://github.com/1Remote/1Remote/assets/127948851/207ca7df-477f-4433-9f73-ea8e6d898120)

**Comment by majkinetor** [comment]
What is the purpose of it, is it clicking the local taskbar that inconvenient ?

**Comment by ElvenGo** [comment]
Yes, it's a little inconvenient.
When I move the mouse away from the remote host, I get used to using keyboard shortcuts to operate programs while the keyboard is still on the remote host.
The localhost task bar is often full, and clicking on the localhost task bar will switch to the clicked program, which is very inconvenient.
So, I want the keyboard to be released from the remote host when the mouse cursor moves to the local host.

Just a suggestion.

MobaXterm does just that.

**Comment by VShawn** [comment]
it's kinda late, but I finally wrapped it up. download the nightly build and let me know if it's looking good.
