### ISSUE TITLE
如果能集成支持安卓的adb连接和scrcpy投屏就完美了，集万千宠爱于一身。

### ISSUE THREAD

**Issue by out278** [1Remote/1Remote#649]
如果能集成支持安卓的adb连接和scrcpy投屏就完美了

**Is your enhancement related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
Add any other context or screenshots about the enhancement here.

**Comment by VShawn** [comment]
别想了，作者我没有Android手机，不可能做出来的。[doge]
你可以尝试自己加然后PR进来。
