### ISSUE TITLE
最近遇到的两个问题:一个直接导致卡死，另一个导致连不上

### ISSUE THREAD

**Issue by leezm** [1Remote/1Remote#653]
**Describe the bug**
第一个问题,在远程winserver2016时(原始版,未安装任何补丁,安装补丁后的没问题),会一直黑屏,然后失去响应,过一会整个exe爆掉
第二个问题,我从pdf中复制出来的ip,直接创建副本,然后粘贴ip,然后右下角一直提示地址不可用,，肉眼看都是正常的,必须删除后手输才行

**To Reproduce**
直接按照上述指定条件连接就能复现

**Expected behavior**

**Screenshots**
第一个问题，程序会直接爆掉,用自带的会直接报出如下的错误,希望程序能优化下,遇到这种也直接报错
![image](https://github.com/1Remote/1Remote/assets/24444492/321652af-be1d-4c1e-b09d-f76609ffbd40)
第二个问题，可能是有啥特殊字符,导致觉得ip不合规,但是复制过来肉眼实在看不出,希望这个也能优化一下

**Desktop (please complete the following information):**
 OS: [e.g. Win11 23H2]
 PRemoteM Version 商店版1.0.0-beta.07

**Additional context**

**Comment by VShawn** [comment]
第一个问题是专门修改过忽略掉CredSSP加密提示的，当时win10上没有发现会黑屏卡死，可能是win11会出这个问题。（win11上1remote问题挺多的，而且都找不到原因）。

我后续会添加一个选项，运行定制是否忽略CredSSP加密提示。


对问题二无能为力，因为要考虑到远程地址可以输入ip、域名、内网机器名称，我也不知道哪些字符是合规的。

**Comment by leezm** [comment]
> 第一个问题是专门修改过忽略掉CredSSP加密提示的，当时win10上没有发现会黑屏卡死，可能是win11会出这个问题。（win11上1remote问题挺多的，而且都找不到原因）。
> 
> 我后续会添加一个选项，运行定制是否忽略CredSSP加密提示。
> 
> 对问题二无能为力，因为要考虑到远程地址可以输入ip、域名、内网机器名称，我也不知道哪些字符是合规的。

第一问题,用win11自带的mstsc又是好的,会提示错误的,所以感觉很奇怪😂

**Comment by VShawn** [comment]
查了一圈开始不确定是不是 CredSSP 的问题了，可以帮做个测试么？ @leezm 

下载最新版程序，导出一个 rdp 文件，然后双击文件看是否会提示错误。

![image](https://github.com/1Remote/1Remote/assets/10143738/560dd798-96bd-4ca7-8280-2b158b1b6f85)

然后再用记事本打开这个rdp文件，增加一行

`enablecredsspsupport:i:1`

再测试一次是否能够连接成功。

**Comment by leezm** [comment]
> 查了一圈开始不确定是不是 CredSSP 的问题了，可以帮做个测试么？ @leezm
> 
> 下载最新版程序，导出一个 rdp 文件，然后双击文件看是否会提示错误。
> 
> ![image](https://private-user-images.githubusercontent.com/10143738/337859451-560dd798-96bd-4ca7-8280-2b158b1b6f85.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc4MzMxMTMsIm5iZiI6MTcxNzgzMjgxMywicGF0aCI6Ii8xMDE0MzczOC8zMzc4NTk0NTEtNTYwZGQ3OTgtOTZiZC00Y2E3LTgyODAtMmIxNThiMWI2Zjg1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA4VDA3NDY1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQzZGE2YjE0NzMxOGMyMDJiNzQyZjIyNzAzODZkOWZhZjc3NjAxYTY4ODAyOTEyMjFiZWQwNjQ5ZTY5NDdiMGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.FS6vpLxRTF5ezuF1I4YXoDunvcNxLjfWWHEP8oZft6M)
> 
> 然后再用记事本打开这个rdp文件，增加一行
> 
> `enablecredsspsupport:i:1`
> 
> 再测试一次是否能够连接成功。

抱歉啊,手头没有初始版的2016了.都是打了补丁的了,下次遇到的话我留意下吧...

**Comment by VShawn** [comment]
好的。介于目前没有测试环境，这个ticket暂时关闭了。
