### ISSUE TITLE
Sftp program：Long wait time to start download

### ISSUE THREAD

**Issue by caoguosong** [1Remote/1Remote#654]
服务器环境：centos7.9

客户端环境：win10

sftp窗口中，右键选择文件--保存到--选择文件夹--保存，

然后大概需要等待10+秒，才开始下载或者提示文件已存在。

请帮忙看看是什么问题。

谢谢！

**Comment by caoguosong** [comment]
上传文件也是一样的问题，要等10秒左右才能开始或者提示存在同名文件

**Comment by VShawn** [comment]
can not confirm the bug


https://github.com/1Remote/1Remote/assets/10143738/bd0b7bc7-7dcb-426a-9579-29219b87ce22
