### ISSUE TITLE
建议非全屏时可以隐藏标签栏

### ISSUE THREAD

**Issue by mingjinglyh** [1Remote/1Remote#657]
现在的版本，如果把窗口最大化（非全屏），在远程桌面里面使用最大化的浏览器等窗口时，想关闭浏览器的标签时，容易误点1Remote的标签按钮，建议1Remote非全屏时可以隐藏标签栏

**Comment by VShawn** [comment]
隐藏标签栏不太现实，可以添加一个选项，把按钮放在左侧，和远程桌面中程序的关闭按钮位置错开。
