### ISSUE TITLE
现在只能点击列头来排序，要是能手动拖移排序 或者能定义顺序号  就完美了

### ISSUE THREAD

**Issue by Sanhuaitang** [1Remote/1Remote#661]
软件已经非常好用了，感谢！
希望能更方便管理，比如 添加IP列  、能有分组功能、 能手动拖移排序 或者能定义顺序号
图标能从app的exe读取就更好了

**Comment by VShawn** [comment]
![image](https://github.com/1Remote/1Remote/assets/10143738/ac336539-d619-4a6d-8ed0-7add989090a7)

可以拖动排序
