### ISSUE TITLE
在不同dpi的双显示器下分辨率不正确

### ISSUE THREAD

**Issue by lqblln** [1Remote/1Remote#666]
**Describe the bug**
程序界面只会在程序启动时按主显示器的dpi设置进行正确缩放，而当将窗口移动到另一个dpi不同的显示器上后，程序会对整个界面按两个显示器dpi的比例进行整体放大或缩小，导致远程画面尺寸错误，且画面模糊。

**To Reproduce**
1. 准备双显示器，将主显示器的dpi缩放设置为125%，将副显示器设置为200%。
2. 彻底重新启动计算机和1Remote
3. 设置远程会话的分辨率为1000*1000（固定，不拉伸）
4. 连接到远程会话
5. 将窗口拖动到主显示器上，此时会话窗口的大小为1000*1000，且画面清晰
6. 将窗口拖动到副显示器上，此时会话窗口的大小为1600*1600，且画面模糊，远程会话的实际分辨率并未变化（推测窗口按2/1.25的比例被放大）

**Expected behavior**
在副显示器上，会话窗口大小与主显示器保持一致，副显示器上的窗口不再被错误缩放。

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 11 企业版 24H2 build 26100.560
 - PRemoteM Version 1.0.0-beta.07 20240228 （微软商店版）

**Additional context**

**Comment by VShawn** [comment]
这个应该是RDP的限制，我尝试过多种方法，都无法做到拖动窗口到另一个显示器时，自动感知DPI变化，而调整桌面分辨率。官方的那个远程桌面似乎可以做到，不知道里面加了什么魔法。

> 同时还发现分辨率选项中带（拉伸）的选项只能缩小而不能放大会话窗口，感觉应该也是个 bug？

这个也是 RDP 的限制，只能缩小，不能放大。
