### ISSUE TITLE
remoteapp 的托盘图标

### ISSUE THREAD

**Issue by cadem** [1Remote/1Remote#670]
我的这个问题不是1remote的问题，只是想找人交流一下。

我的问题是remoteapp托盘图标显示的问题。当我把[RemoteApp Tool](http://www.kimknight.net/remoteapptool)生成的rdp文件和1remote混合用（也就是连同一个机器上的同一个app，比如飞书，有时用rdp，有时用1remote），在有些时候（我也不确定是什么规律），remote机器上的app的托盘图标有时会出现在本机的托盘里。但是当我只用1remote时，托盘图标从来没出现过。

我觉得托盘图标不显示，应该是mstsc的bug（有时出现，有时不出现），1remote也是调用的mstsc。但是我想知道有没有办法让remoteapp的托盘图标稳定出现？

**Comment by VShawn** [comment]
没有遇到过，我之前用QQ，没有出现过托盘图标不显示的情况。
