### ISSUE TITLE
增加通过SSH访问Linux系统时直接访问sftp

### ISSUE THREAD

**Issue by ZhouDante** [1Remote/1Remote#672]
访问sftp：
通过ssh登陆服务器后，在左侧或右侧显示文件夹及文件

sftp修改文件：
当登录系统后，可直接在sftp栏位中直接修改配置文件
![sftp](https://github.com/1Remote/1Remote/assets/171394651/051dbdff-069d-411a-88d4-d99c48a3ab35)

**Comment by VShawn** [comment]
这个提议之前已经被提出来过了，简单来说就是仿照 mobaxterm 的 SSH 界面，实现同时 SSH 和 SFTP。

其中难点有2：

- 1Remote 的 SSH 基于第三方 exe，所以做不到 mobaxterm 那样，ssh cd 进入某个目录，SFTP 也跟着进入那个目录。
- 界面上目前完全不支持左右分屏，于是这部分得花挺大精力进行重新。

今年由于个人原因，空闲时间不足，因此近期内我都没有空对这个项目进行大的升级，于是估计在一年内我都不会进行这个功能的开发，如果有人有兴趣增加这个功能，我很欢迎PR。
