### ISSUE TITLE
May I have a proxy choice to connect the remote servers?

### ISSUE THREAD

**Issue by 404notfound-xxx** [1Remote/1Remote#675]
**Is your enhancement related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
Add any other context or screenshots about the enhancement here.

**Comment by VShawn** [comment]
Sorry, currently I have no plan for proxy or tunnel. SSH tunnel may be added in the future, but not now. I’m busy this year have no enough time to add new features.

**Comment by VShawn** [comment]
BTW feel free to submit a PR if you can DIY

**Comment by 404notfound-xxx** [comment]
Firstly,thank you for your reply.Thank you for providing this useful tool. I will try to add proxy functions and submit PR when I have time. I look forward to this software getting better.
