### ISSUE TITLE
[feature requst] Add option to disable "Ask for user / password" pop up

### ISSUE THREAD

**Issue by olfolfolf** [1Remote/1Remote#676]
We use 1remote in a team (shared DB on OneDrive).
In newer versions of 1remote, a "Ask for user / password" pop up appears when username and password is empty in the database (we save the connection without user / password because of our sharing approach).

Now we have two options:
1) Leave SSH runner as it is - we have to enter the password two times. First time in the new pop up and second time in the embedded putty window.

2) Add -pw %1RM_PASSWORD% to the runner. That's kinda ugly, because now you can see the password f.e. in Task Manager (see attached screenshot):
![2024-06-10 13_30_30-Task-Manager](https://github.com/1Remote/1Remote/assets/36164676/87df6109-efbe-4161-8d4b-d8bee2b2899a)

Feature request: option to disable the new pop up to get the old behavior, only one user / password dialog without showing the password in Task Manager / command line.

**Comment by VShawn** [comment]
> we have to enter the password two times

Can you describe how to reproduce it? I found that I only need to enter the password once.


https://github.com/1Remote/1Remote/assets/10143738/2d75d87a-e44a-4cf3-8da7-3b553f7c1ecb

> Add -pw %1RM_PASSWORD% to the runner. That's kinda ugly, because now you can see the password f.e. in Task Manager

well we are not able to hide password from Task Manager since we choose KiTTY as SSH client(we need some KiTTY's features). 

beacuse:

https://stackoverflow.com/questions/71084301/securely-pass-password-to-putty-process-on-start

https://github.com/cyd01/KiTTY/issues/502

**Comment by olfolfolf** [comment]
> Can you describe how to reproduce it? I found that I only need to enter the password once.
Remove -pw option from the SSH runner (we use PuttyNG because of some issues with kitty, f.e. #499 ).
Then you get the pop up, but you have to enter the password in Putty.

> well we are not able to hide password from Task Manager since we choose KiTTY as SSH client(we need some KiTTY's features).
I know, that's why we don't want to use -pw. 
That's why I asked if you could make the new pop up dialog switchable.

Br,

**Comment by Kry5ta1** [comment]
我同样遇到了这个问题。
![image](https://github.com/1Remote/1Remote/assets/95294949/f19a6727-9ceb-4383-9fff-508da440d517)
我在内网中远程我的windows电脑，并且被远程电脑启用了 空密码登录行为，这让我只需要输入用户名即可远程连接。
但是在新版本中，尝试连接过后我会遇到：
![image](https://github.com/1Remote/1Remote/assets/95294949/8e9f12c5-d7a8-4c26-b2cd-873b9ee6b3e5)
这里我点击确定后没有任何反应，我只能尝试随便输入几个字符（因为我实际上是没有密码的）
![image](https://github.com/1Remote/1Remote/assets/95294949/45c69ebe-94e3-40d4-a19b-13dec3f8e45d)
我需要在弹出的windows凭据界面再次点击确定才能远程成功。

以前的版本不会出现这样的行为，像这样的空密码远程，直接点击就可以连接了。
建议：是否只在凭据出现错误的时候才进行刚才的输入框。并且允许空密码的直接连接。

**Comment by VShawn** [comment]
@Kry5ta1 Ahhhh I see what you need, I didn't expect it can login without a password.

**Comment by VShawn** [comment]
done :)

**Comment by olfolfolf** [comment]
Thanks, that's how I had imagined it :-)
