### ISSUE TITLE
[BUG] About repeated software opening problems

### ISSUE THREAD

**Issue by yanceysong** [1Remote/1Remote#680]
**Describe the bug**
About repeated software opening problems

**To Reproduce**
When the software is opened and saved in the system taskbar, when I double-click the desktop software icon, it will appear another icon in the taskbar, and both ICONS can open the software

**Expected behavior**

**Screenshots**

**info:**
 - OS: [e.g. Microsoft Windows 10 Pro]
 - PRemoteM Version 0.7.2.8

**Additional context**
null

**Comment by VShawn** [comment]
well..

 Version 0.7.2.8 is not supported, plz update to version 1.0.0.beta
