### ISSUE TITLE
feature request:  add options to set `EnableAutoReconnect` to False

### ISSUE THREAD

**Issue by zipv** [1Remote/1Remote#681]
由于经常使用代理网络进行连接，不希望在网络断开后，软件自动尝试通过本地实际网络进行重连。希望能增加一个类似RemoteNG的功能，即在网络断开时，可以设置自动重连的次数或者选择不自动重连。这样能够更好地保护我的连接安全性，避免不必要的本地网络连接。
期盼此功能能在未来的版本中得到实现。

**Comment by VShawn** [comment]
我考虑通过添加自定义附属配置的方式把各种没有在UI显示出来的小配置给整合到一起，但暂无计划何时启动开发。

**Comment by VShawn** [comment]
hi now you can disable the AutoReconnect by `EnableAutoReconnect:i:0`

![image](https://github.com/user-attachments/assets/78d92586-a763-42cc-95d6-a234bebfb15c)

**Comment by ifzm** [comment]
请问下要怎么设置呢？

**Comment by VShawn** [comment]
![image](https://github.com/user-attachments/assets/ac93b990-f3c7-4628-81ed-287bfa0c8cd0)

在MISC中填入红框中的内容

**Comment by ifzm** [comment]
好的，谢谢
