### ISSUE TITLE
在不同dpi的双显示器下鼠标尺寸不正确

### ISSUE THREAD

**Issue by hlc1209** [1Remote/1Remote#682]
**Describe the bug**
在不同dpi的双显示器下鼠标尺寸不正确。在高DPI显示器上鼠标大小正常，同时在低DPI显示器上鼠标巨大
甚至于在断开外接显示器后，只要不关闭1remote进程，在低DPI内置显示器上鼠标仍然巨大

**To Reproduce**

**Expected behavior**

**Screenshots**
截屏截不出鼠标。如需要我可拍照上传

**Desktop (please complete the following information):**
Win11 23H2 22631.3737
![image](https://github.com/1Remote/1Remote/assets/45445824/d615a9ef-25a7-46f3-b383-ca49346c3e2b)

**Additional context**

**Comment by VShawn** [comment]
不需要拍照上传了，我自己也遇到过这个问题，但过去我研究后发现这似乎是微软RDP本身的问题，一定要重启RDP才能显示正常。
或者说微软没有提供接口来让我来动态设置不同显示器的DPI。

微软自家的似乎可以做到这一点，但那个是微软加了魔法的RDP客户端（意思是魔改过AxRDPlib），而且闭源，以至于我分析不出它到底是如何实现的。

因为解决不了，所以问题暂时关闭。

如果你发现哪个开源远程工具实现了不同显示器的DPI缩放，请告诉我，我会去调研看是如何实现的。

**Comment by hlc1209** [comment]
能否在检测到断开显示器后，自动重连所有RDP？

来解决一部分问题

**Comment by surf5726** [comment]
只有把1Remote.exe的高DPI缩放设置改成系统或系统增强才能在不更改RDP缩放的情况下实现本地缩放，不过代价就是1Remote程序本身变模糊了

**Comment by VShawn** [comment]
```
能否在检测到断开显示器后，自动重连所有RDP？

来解决一部分问题

```

虽然可以用这个方法解决一部分问题，但这个方案太过粗暴，我不实现这个方案。

```
只有把1Remote.exe的高DPI缩放设置改成系统或系统增强才能在不更改RDP缩放的情况下实现本地缩放，不过代价就是1Remote程序本身变模糊了
```

嗯，Windows的DPI缩放一直很迷
