### ISSUE TITLE
远程连接后窗口边缘能自动匹配画面的尺寸吗？如图。

### ISSUE THREAD

**Issue by ubean2018** [1Remote/1Remote#683]
你好！
如图。
远程的桌面分辨率不一，窗口四周有灰色空白，每次得手动调整窗口大小。
希望每次能自动适配窗口大小。
![Snipaste_2024-07-02_16-26-35](https://github.com/1Remote/1Remote/assets/39214887/7abcd684-7129-4b2b-b716-0e4de250e846)

**Comment by VShawn** [comment]
受系统限制，win7 系统不支持分辨率感知，升级到 win8 以上你就会发现能够自动调整分辨率了。
