### ISSUE TITLE
Feature Request - Disable automatic connections to 10+ remote IP's

### ISSUE THREAD

**Issue by Avrution** [1Remote/1Remote#684]
Just discovered this program today when trying to figure out dual monitor support on mremoteng and really love it.  

One big problem though, I don't like all of the remote connections it is making.  Is there a reason so many are needed?  Especially since most of them seem to be to Microsoft.

I see it trying to connect to 10 different IP's.

**Comment by VShawn** [comment]
Hi @Avrution it seems that you are sensitive to the networking behavior of the app. You can eliminate the networking behavior of 1Remote through the following methods :)

# 1Remote will create the following two connections:

## to App Center

Most of the connections are connected to [appcenter.ms](https://appcenter.ms) for analytical purposes, mainly for crash alert to import our app.

![image](https://github.com/1Remote/1Remote/assets/10143738/1de51a20-8583-46ac-a3aa-451aa454482d)

If you don't like it, you can disabled it by remove all refs to [MsAppCenterHelper.cs](https://github.com/1Remote/1Remote/blob/37d2d2f393f466d66b7a3e4e4c4e9666709e9a29/Ui/Utils/MsAppCenterHelper.cs#L24) and build the app yourself

https://github.com/1Remote/1Remote/blob/37d2d2f393f466d66b7a3e4e4c4e9666709e9a29/Ui/Utils/MsAppCenterHelper.cs#L24

## to GitHub

There is another link to access GitHub for checking version updates. 

band VersionHelper can disabed the check.

https://github.com/1Remote/1Remote/blob/37d2d2f393f466d66b7a3e4e4c4e9666709e9a29/Ui/View/AboutPageViewModel.cs#L21-L25

**Comment by Avrution** [comment]
Appreciate the insight into the reason for the connections, but compiling my own is above my pay grade.  😁

Hopeful for a configuration option in the future to disable checks (in the 1Remote.json maybe) or would even pay for a version without telemetry.

Will keep an eye on things.
