### ISSUE TITLE
功能请求：remoteapp添加mstsc模式，以实现更多的自定义参数

### ISSUE THREAD

**Issue by PR2403** [1Remote/1Remote#685]
像RDP里的mstsc模式一样即可，个人主要用于remotefx usb重定向。
感谢开发者。

**Comment by VShawn** [comment]
正好请教如何在 .rpd 文件中配置 remotefx？

**Comment by PR2403** [comment]
https://learn.microsoft.com/zh-cn/azure/virtual-desktop/configure-device-redirections
因为remoteapp没有设备选择的ui，必须手动指定usb设备，以下是我使用的配置，重定向了一个JLINK调试器
usbdevicestoredirect:s:-USB\VID_1BCF&PID_28CC\01.00.00;USB\VID_1366&PID_0105\000601012352
前一个是笔记本的摄像头，没有重定向。后一个就是JLINK

**Comment by PR2403** [comment]
没有问题
