### ISSUE TITLE
修改密码遇到一个问题

### ISSUE THREAD

**Issue by Hi-360** [1Remote/1Remote#689]
设置界面机器的密码已经修改了，登录的时候提示密码错误。只能删除登录信息  重新添加才能成功登录

**Comment by VShawn** [comment]
在最新版试了一下未能复现，请问你那边能稳定复现这个问题吗？并发一下复现问题的操作步骤。

**Comment by Hi-360** [comment]
> 在最新版试了一下未能复现，请问你那边能稳定复现这个问题吗？并发一下复现问题的操作步骤。

我再试下  复现我进行反馈
