### ISSUE TITLE
可以加一个x掉断开连接后远程桌面继续运行的功能吗，要跑一些自动脚本用

### ISSUE THREAD

**Issue by 1399702039** [1Remote/1Remote#691]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by VShawn** [comment]
这个功能需要在服务器端配置，印象中是组策略里面某个选项控制的，请自行搜索如何配置

**Comment by 1399702039** [comment]
> 这个功能需要在服务器端配置，印象中是组策略里面某个选项控制的，请自行搜索如何配置

组策略的选项只能控制远程连接的程序不停止运行，但是只要x掉，远程桌面就会进到锁屏的状态，https://support.smartbear.com/testcomplete/docs/testing-with/running/via-rdp/keeping-computer-unlocked.html，具体可以参照这个文章
