### ISSUE TITLE
Minimum tab size for short RDP names

### ISSUE THREAD

**Issue by alejandro5042** [1Remote/1Remote#692]
**Is your enhancement related to a problem? Please describe.**
When you have a machine name with a short name like "abc", the tab size is very small compared to other machines with longer names. Makes it hard to click on it and not hit the X button to close the tab, accidentally.

**Describe the solution you'd like**
I want a minimum tab size for short names. Something wide, like 12 characters.

**Describe alternatives you've considered**
Try to make the name longer manually, while connecting to a different host. Not as nice.

**Comment by VShawn** [comment]
sounds reasonable
