### ISSUE TITLE
为导入导出设置文件加入加密机制

### ISSUE THREAD

**Issue by SongzqInChina** [1Remote/1Remote#694]
> 在软件的导入导出设置功能中，默认会把IP地址，用户名和密码全部作为原文写入JSON文件中，但是这太不安全了，攻击者很容易拿到用户的信息。

我提供了两个使用加密的解决方法作为参考：
------
## 方法一
1. **处理** 首先使用原来的处理机制将源明文信息转换为JSON字符串格式
2. **加密** 提示用户设置密码，由于某些加密方式的密钥长度限制，可以使用Hash化或其它方法将任意长度的密码转换为固定长度的密钥
3. **验证** 在文件中加入一个特殊的验证值（可以是一个固定字符串，整数等），保证用户的密钥是正确的，如果解密后验证值不匹配，说明密码错误，也可以直接解析JSON表达式时捕获异常，判断用户密码是否正确
4. **加载** 解密后的JSON就可以加载进软件中了
------
## 方法二
1. **设置密码** 提示用户设置密码，按上面提过的方法转换成密钥
2. **加密** 将用户信息（IP地址，用户名，密码）进行加密，并丢弃明文
3. **处理** 将加密后的信息存储为JSON格式
4. **验证** 这个同样可以使用验证值和试错法来解决
6. **加载** （不用我多说了吧）
------
# English

> In the software import and export Settings function, the default IP address, user name and password will be written into the JSON file as the original text, but this is too insecure, attackers can easily get the user's information.
​I offer two solutions that use encryption as a reference:
------
## Method one
1. ** Processing ** First converts the source plaintext information to JSON string format using the original processing mechanism
2. ** Encryption ** Prompts the user to set a password. Due to the key length limitation of some encryption methods, you can use Hash or other methods to convert the password of any length into a fixed length key
3. ** Verification ** Add a special verification value (can be a fixed string, integer, etc.) in the file to ensure that the user's key is correct, if the verification value does not match after decryption, indicating that the password is wrong, you can also directly parse the JSON expression to catch the exception, determine whether the user's password is correct
4. ** Load ** The decrypted JSON can be loaded into the software
------
## Method 2
1. ** Set a password ** Prompts the user to set a password and convert it into a key according to the method mentioned above
2. ** Encryption ** Encrypt the user information (IP address, user name, password) and discard the plaintext
3. ** Processing ** Store the encrypted information in JSON format
4. ** Verification ** This can also be solved using the verification value and trial and error method
6. ** Loading ** (I don't need to say more)

**Comment by SongzqInChina** [comment]
也可以使用Hash验证的方式

**Comment by VShawn** [comment]
我原意是导出的json文件，用户如果需要加密，则自己打zip包加密即可，以尽量减少软件的功能。
