### ISSUE TITLE
FtpClient - Missing Objects/Methods

### ISSUE THREAD

**Issue by GlacierDataworks** [1Remote/1Remote#696]
**Describe the bug**
FtpFileSystemObjectType does not exist.
FtpClient does not contain a definition for UploadFileAsync and DownloadFileAsync

**To Reproduce**
1. Clone repo in Visual Studion 2022
2. Restored NuGet packages
3. Clean and Build solution.

**Expected behavior**
Build without error

**Screenshots**
![image](https://github.com/user-attachments/assets/b7ae32ca-9e2b-406c-9ee3-57763f12ec58)

**Desktop (please complete the following information):**
 - OS: Windows 11 Home edition
 - Visual Studio 2022 Version 17.10.4

**Additional context**
I think the FTPClient needs to be AsyncFtpClient instead of FtpClient, but that doesn't solve all the issues. I'm still working on how to make the async methods run.

Thanks

**Comment by GlacierDataworks** [comment]
Changed _ftp type from FtpClient to AsyncFtpClient.
FtpFileSystemObjectType was renamed to FtpObjectType.
Removed Async from UploadFile and DownloadFile method names.
Now it builds just fine!

**Comment by VShawn** [comment]
maybe you can make a PR for this :)

**Comment by GlacierDataworks** [comment]
I got a good build, but have not tested any of it yet. I'd hate to introduce other bugs because it wasn't tested.

**Comment by GlacierDataworks** [comment]
This is the file that changed.

Pam
