### ISSUE TITLE
隔一段时间没连接，再连的时候就被锁了

### ISSUE THREAD

**Issue by aliciz** [1Remote/1Remote#699]
![cdd539fd6f526f0ce141eb79ca78e620](https://github.com/user-attachments/assets/8e78a667-ef69-4c35-a9d2-4dad2312e7a6)

如图，我远程桌面（win11），公司、家里上班往返，网络相当于断了又连，连了又断吧，一段时间后再去连接的时候就有这个错误了。。

不是很理解，如果重试连接，密码应该是正确的。

**Comment by aliciz** [comment]
版本：
![QQ_1723210469739](https://github.com/user-attachments/assets/f39bbf0f-b183-410c-8dd9-23b412c06ead)

**Comment by VShawn** [comment]
我也不是很理解，您能查看一下当时的系统日志吗？看当时连接重试了多少次，以及是否是密码错误。

**Comment by aliciz** [comment]
![QQ_1723538482275](https://github.com/user-attachments/assets/9bcd927e-dc61-4e56-ae36-085f3066fc5a)
这个能看出是什么吗

**Comment by VShawn** [comment]
看出来确实是多次登陆失败，而且是2秒内多次登陆失败，但登陆失败后在 2024/8/9 21:28:11 和 56秒又有两条登陆成功的日志，说明多次登陆失败当时并没有导致系统锁定。我不是这方面的专家，暂时只看出这些。

![image](https://github.com/user-attachments/assets/dbc3966d-6688-4a3b-a241-2994f3754627)

**Comment by aliciz** [comment]
@VShawn 
![QQ_1723692873866](https://github.com/user-attachments/assets/29c92fab-fd4c-4f5d-ba38-e95a20156fd7)

我把日志清了，远程桌面的这个窗口最小化，等了一会再打开，发现日志是这样的，是不是意味着我每次重连都是一次账号密码验证。。？

**Comment by VShawn** [comment]
并不是这样，比如说我的日志，我很确定我没有重新登陆过，但日志里依然会有登陆记录。正如我所说，我不是这方面的专家，因此不清楚为何总是会有 LOGON 日志出现。

![image](https://github.com/user-attachments/assets/737c0943-038d-4ad9-b3f3-1b25b3333871)

**Comment by VShawn** [comment]
https://github.com/1Remote/1Remote/issues/681#issuecomment-2297742034

现在你可以通过设置直接禁用1Remote的自动重连。
