### ISSUE TITLE
Launcher does not search on #tag while the main interface does

### ISSUE THREAD

**Issue by b-a0** [1Remote/1Remote#700]
**Describe the bug**
When providing a `#tag` to the launcher no filtering is applied and simply all items are returned.

**To Reproduce**
1. Open launcher with keyboard shortcut
2. Type in a tag starting with a # symbol, e.g. `#ssh` 
3. The list of hosts remains the same, no filtering is applied

**Expected behavior**
The list of hosts should be filtered by the launcher such that only hosts with a tag `#ssh` are shown.

**Screenshots**
The main application can filter based on tags and shows the expected hosts that should be returned:
![image](https://github.com/user-attachments/assets/144612d0-5185-4aa6-b93d-8f29186eb191)

The launcher however does not filter the full list for the query `#ssh` and returns all hosts:
![image](https://github.com/user-attachments/assets/5dbeb36b-9761-41db-aea5-8a062e19f02d)

**Desktop (please complete the following information):**
 - OS: Windows 11 version 23H2 build 22631.3880
 - PRemoteM Version 1.0.0-beta.07, built at 2024-07-11T09:29:59.434

**Additional context**
N/A

**Comment by VShawn** [comment]
thx for your report
