### ISSUE TITLE
常规-名称 框内的字体有点模糊

### ISSUE THREAD

**Issue by modelsun** [1Remote/1Remote#702]
**Describe the bug**
点击“编辑” 进入RDP 设置界面，刚进去的时候，常规-名称 框内的字体有点模糊，1~2s后，变得清晰了

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Win11 
 - PRemoteM Version 08-20 最新版本

**Additional context**

**Comment by VShawn** [comment]
1~2s后，变得清晰了...

说明是系统渲染导致的，暂时无解。
