### ISSUE TITLE
[Feature request] 希望提供一个使用 Remote Destop 应用程序替代 mstsc 的选项，来改善 mstsc 存在的性能问题

### ISSUE THREAD

**Issue by sqkkyzx** [1Remote/1Remote#704]
发现使用 Microsoft Store 下载安装的 Microsoft Remote Destop 应用程序来连接，体验比 mstsc 好很多，相同网络环境下，mstsc 进入后鼠标卡住，几乎不可用的情况下，使用 Microsoft Remote Destop 应用程序仍然能较为流畅的操作。

1Remote 似乎是调用了 mstsc ，体验和 mstsc 一致。是否可以提供一个选项，调用最新的远程桌面应用程序来链接？或者是否有人能够提供一些 mstsc 链接的参数优化建议？

**Comment by VShawn** [comment]
Microsoft Remote Destop 应该更新过RDP协议，能够实现MSTSC不支持的功能，不知道其中加了什么魔法。
