### ISSUE TITLE
捐款页面打不开，直接放支付宝或者微信二维码吧

### ISSUE THREAD

**Issue by nicai0609** [1Remote/1Remote#708]
**Is your enhancement related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
Add any other context or screenshots about the enhancement here.

**Comment by VShawn** [comment]
感谢捐赠，似乎是域名解析出问题了，导致页面打不开，没精力修域名，暂时把二维码连接挂出来了。

https://github.com/1Remote/1Remote.github.io/blob/main/source/docs/zh-cn/donate.jpg
