### ISSUE TITLE
 use NET  8 instead of NET 6

### ISSUE THREAD

**Issue by heartacker** [1Remote/1Remote#709]
IN RELEASE PACKAGE

**Comment by VShawn** [comment]
I haven't seen any WPF breakthroughs in `Upgrading from .NET 6 to .NET 8` so I won't be upgrading for now.

**Comment by VShawn** [comment]
one day I will modify the CI script to output both .NET 6 and .NET 8 versions during the CI build.

**Comment by heartacker** [comment]
> one day I will modify the CI script to output both .NET 6 and .NET 8 versions during the CI build.

thanks，

**Comment by heartacker** [comment]
https://learn.microsoft.com/zh-cn/dotnet/desktop/wpf/whats-new/net80?view=netdesktop-9.0#hardware-acceleration
dotnet 8 支持 GPU 加速
dotnet 9 继承 dotnet 8，，并且Aot 支持更好
建议支持 DOTNET 9 版本 的AOT 版本。
