### ISSUE TITLE
可以添加Logout.bat来关闭远程控制，这样就不会锁屏

### ISSUE THREAD

**Issue by 947522985** [1Remote/1Remote#710]
for /f "skip=1 tokens=3" %%s in ('query user %USERNAME%') do (%windir%\System32\tscon.exe %%s /dest:console)

新建txt，把上面复制进去，修改后缀为bat，右键--以管理员身份运行，这样就不会锁屏
![360截图20240907153453004](https://github.com/user-attachments/assets/d4f2d1f2-0c06-4396-9451-19215ab3b194)

**Comment by 947522985** [comment]
有办法添加到软件里吗？

**Comment by VShawn** [comment]
没看错的话，这个脚本是在服务端执行的吧？1Remote 没有权限也没有办法在服务器端执行脚本

**Comment by 947522985** [comment]
![1](https://github.com/user-attachments/assets/daf3bf36-643c-4674-876b-1694848d11ff)
现在是这样使用，不知道有没有更好办法

**Comment by VShawn** [comment]
查了一下，https://superuser.com/a/1704295 这个可能对你有参考
