### ISSUE TITLE
请问是否可以考虑对数据进行更安全加密和保护

### ISSUE THREAD

**Issue by wanvb** [1Remote/1Remote#711]
比如假设主机系统或者其它业务系统网站程序什么的有漏洞，导致主机系统被拿了webshell权限，那此时攻击者只要拷贝走1Remote.db文件。或者通过其它方式无意把1Remote.db文件给泄露了，那所有的服务器全部都完了，这显然是不安全的。
是否可以考虑存入1Remote.db内的服务器密码信息，使用当前机器码进行加密运算，这样就算1Remote.db被拷贝走的情况下，对方机器码不对也使用不了，能最大程度的保护服务器安全性。

同样导出配置的时候，也可以弹出输入框让用户输入一个加密密码，此密码用于加密导出配置中的服务器密码信息，当导入的时候也需要手动输入此密码来还原服务器密码进行导入，提升服务器导出的配置文件安全性。

**Comment by VShawn** [comment]
1. 目前 1Remote.db 中机密数据是加密存储的（然而是通用密码，任何一个 1Remote.exe 都能解密）
2. 之所以没做机器码加密是考虑到我自己要通过sync在多台机器上同步数据库使用。
3. 如果你需求更高级别的加密，可以开启BitLocker，然后自己下载源码，修改加密盐，然后编译自己的 1Remote.exe，这样数据库就算被拷走，别人没有你编译出的 1Remote.exe 也无法解密数据库中的机密。

    https://github.com/1Remote/1Remote/blob/main/Ui/Assert.cs#L24

4. 有计划对导出数据做 zip 加密打包，但目前仍是脑内方案，还没决定什么时候做，主要是今年个人生活上比较忙，空闲时间不够用。
