### ISSUE TITLE
切换为卡片视图时还是纵向排列

### ISSUE THREAD

**Issue by MINIPuffer** [1Remote/1Remote#712]
**Describe the bug**
![image](https://github.com/user-attachments/assets/e45fb48c-d275-4f1d-aa94-800e45358df0)
![image](https://github.com/user-attachments/assets/28821658-4b16-41ab-9744-2f76e749046a)

**Desktop (please complete the following information):**
 - OS: Windows 11 家庭中文版 23H2
 - PRemoteM Version 1.0.0

**Comment by VShawn** [comment]
确实是，由于用卡片视图的用户太少（包括我自己也不用），卡片视图有点年久失修，等下一版本再进行修复。
