### ISSUE TITLE
Support Windows Sandbox

### ISSUE THREAD

**Issue by alejandro5042** [1Remote/1Remote#713]
**Is your feature request related to a problem? Please describe.**
[Windows Sandbox](https://learn.microsoft.com/en-us/windows/security/application-security/application-isolation/windows-sandbox/windows-sandbox-overview) is the easiest way to launch a clean Windows machine for SW testing. It works a lot like remote desktop to a local VM.

**Describe the solution you'd like**
I want a built-in way for 1Remote to launch a Windows Sandbox and host it within 1Remote.

**Describe alternatives you've considered**
Add WindowsSandbox.exe as an "app" in the 1Remote settings, however, it doesn't host the main window. It launches Windows in its own window.

**Additional context**
Windows Sandbox is made by Microsoft and is part of Windows but is not enabled by default. You can enable it from "Turn Windows features on or off".

**Comment by VShawn** [comment]
Sounds good, but after I did a brief search and didn't find a way to embed Windows Sandbox into a application. If you come across a similar program, please let me know :)

**Comment by alejandro5042** [comment]
Curious - could you embed the actual window? Kinda like how you host an app?

**Comment by VShawn** [comment]
![image](https://github.com/user-attachments/assets/f6bddca4-fe19-4b3e-b9e1-9e6bf63334ea)

nope, I could not host the sandbox in my app for now, as the screen shoot shown above
