### ISSUE TITLE
希望能用树状结构管理各个服务器

### ISSUE THREAD

**Issue by hzjackq** [1Remote/1Remote#718]
用列表方式不方便，特别是服务器很多的情况

**Comment by VShawn** [comment]
![image](https://github.com/user-attachments/assets/f77831df-a42f-4524-802c-8b7aa073f519)

![image](https://github.com/user-attachments/assets/97f14a44-5af0-405b-8aae-d99c1beb8a3a)

请尝试通过标签管理服务器，树状UI需要重写数据库结构来形成从属关系，我目前没有精力做这样大的改动。
