### ISSUE TITLE
1Remote SSH Window Z-Order Issue

### ISSUE THREAD

**Issue by Duck15** [1Remote/1Remote#722]
**Describe the bug**
The bug I encountered is: When using non-1Remote embedded features like ssh, it is implemented by embedding other program windows, but embedding other program windows does not respond to raising window priority.

**To Reproduce**
1. Open any SSH/embedded program window.
2. Switch to another program.
3. Place it on top of the SSH/embedded program window, covering it.
4. Click on the original SSH/embedded program window.
5. Observe that the window does not come to the front correctly.

**Expected behavior:**
In clicking on the overlapped window, it should be brought to the front just like a normal window.

**Screenshots**
NO.i dont know how to src it??

**Desktop (please complete the following information):**
 - OS: win10 19044
 - 1remote 1.0.0 store

**Additional context**
In other applications: When embedding other programs into ConEmu, it can still respond to window elevation operations.

**Comment by VShawn** [comment]
Hi U can upload jpg/gif/mp4 by following:

![image](https://github.com/user-attachments/assets/7a9d4424-a9b6-4ab6-9b79-763813ff4610)

**Comment by VShawn** [comment]
can not reproduce close

https://github.com/user-attachments/assets/e09b13a4-b5bd-452e-9ae4-33c8034f0de9
