### ISSUE TITLE
在同一网络下能正常使用，但在不同网络间无法连接

### ISSUE THREAD

**Issue by zhaopluseins** [1Remote/1Remote#723]
非常感谢开发者开发了这么好用的工具。

目前遇到一个问题，即1remote在同一网络下能正常使用，但在不同网络间无法连接。已经排除防火墙的问题，并且测试过，在不同网络间使用系统自带的远程桌面（快速助手，win11和win10）可以连上。

请教该怎么解决，谢谢。

**Comment by VShawn** [comment]
抱歉，从描述中我没有分析出具体是遇到了什么问题，我甚至是第一次听说这个问题。如果你有进一步发现，欢迎分享。

**Comment by VShawn** [comment]
会不会是可访问性检测的问题，你可以把这个选项关掉试试。

![image](https://github.com/user-attachments/assets/0db6e0a1-473d-454d-b447-7afc77a7021e)

**Comment by skczhans** [comment]
信息很少看不出问题

**Comment by zhaopluseins** [comment]
非常感谢您的回复，可能是我网络的问题，我再尝试一下，谢谢

**Comment by VShawn** [comment]
> 使用系统自带的远程桌面（快速助手，win11和win10）可以连上。

既然系统自带的可以连接上，那么是网络问题的可能性就比较小。

**Comment by CV-Devlau** [comment]
> > 使用系统自带的远程桌面（快速助手，win11和win10）可以连上。
> 
> 既然系统自带的可以连接上，那么是网络问题的可能性就比较小。

我也遇到了相同的问题，直接使用 mstsc 可以连接，使用1remote无法连接，勾选启用mstsc模式同样无法连接
