### ISSUE TITLE
ssh连接linux时，如果使用rz命令则窗口出现假死状态

### ISSUE THREAD

**Issue by vista85** [1Remote/1Remote#729]
当linux安装了lrzsz软件包时，意味着ssh可以输入rz进行上传文件到linux上，或者输入sz下载文件到windows本地，
yum install lrzsz

当使用SSH连接到linux后，输入rz会出现假死状态，没有弹出文件选择窗口

[root@Client1 ~]#
[root@Client1 ~]#
[root@Client1 ~]#
[root@Client1 ~]#
[root@Client1 ~]# rz
▒z waiting to receive.**B0100000023be50

**Comment by VShawn** [comment]
请查阅 kitty 如何/是否支持 rz 命令，由于我本人不需要用到这个命令，所以不清楚是否支持。如果不支持，你可以尝试把 1Remote 的 ssh 终端改为 powershell。

**Comment by VShawn** [comment]
sorry 我尝试使用 powershell rz命令， 也是会卡死，上面切换到 powershell 的建议无法解决你的问题。

![image](https://github.com/user-attachments/assets/b4eda709-a3ec-49aa-abc0-908b07c440b4)

**Comment by vista85** [comment]
像主流终端工具，例如SecureCRT，Xshell工具都可以支持这个弹出窗口，希望咱们支持这个功能。

**Comment by VShawn** [comment]
研究了一段时间，觉得这个不是本人能解决的问题，需要有SSH终端开发能力的人来做这个事。于是，本ticket将被无限期搁置。
