### ISSUE TITLE
希望增加一个快速连接功能

### ISSUE THREAD

**Issue by X0Ken** [1Remote/1Remote#738]
在改功能下，仅需要输入协议和ip地址，直接打开远程连接窗口。无需添加配置，再返回界面连接。减少操作步骤

**Comment by VShawn** [comment]
![image](https://github.com/user-attachments/assets/b5143f67-e81f-4f2c-b6ed-e4d763333bfc)

或许是你想要的

**Comment by X0Ken** [comment]
yes
