### ISSUE TITLE
Open the second connection, whole 1Remote app crashed

### ISSUE THREAD

**Issue by toadouyang** [1Remote/1Remote#739]
**Describe the bug**
When open the second connection, whole 1Remote app crashed

**To Reproduce**
1. open a connection such as a RDP connection to a win server
2. open  the second  connection use RDP protocol such as to an another win server
3. app crashed

**Comment by VShawn** [comment]
If possible, please upload the log when it crashed, thank you

**Comment by VShawn** [comment]
close by merge into #740
