### ISSUE TITLE
同时打开多个SSH窗口后，显示不正常

### ISSUE THREAD

**Issue by funbsd** [1Remote/1Remote#742]
选择多个SSH主机，然后点连接，弹出的窗口只有最后一个正常，其它的显示不正常。
![image](https://github.com/user-attachments/assets/329b0252-66b8-4276-a763-e4313e6d4e12)

**Comment by VShawn** [comment]
duplicate with https://github.com/1Remote/1Remote/issues/499

KiTTY显示异常，原作者未做回复，暂时无法修复该问题，可以在1Remote中改为使用 Windows terminal 启动 SSH 来规避该问题。
