### ISSUE TITLE
建议设置RemoteApp默认参数disableremoteappcapscheck:i:0

### ISSUE THREAD

**Issue by funbsd** [1Remote/1Remote#744]
当前默认参数disableremoteappcapscheck:i:1，关闭RemoteApp后，仍在后台运行mstsc.exe，没有断开连接，占用服务器资源。当服务器端主动关闭连接，注销用户时，在客户端会弹出会话已中断的对话框，不友好。
建议改成disableremoteappcapscheck:i:0
![image](https://github.com/user-attachments/assets/6d949aa2-5740-440c-9215-6833943e4dbd)
![image](https://github.com/user-attachments/assets/57e5b6bf-d570-45b9-a00b-5436f64c576c)
![image](https://github.com/user-attachments/assets/78aa3e8b-b203-4de8-b258-529c9aa2f4d5)

**Comment by VShawn** [comment]
sound reasonable.
