### ISSUE TITLE
Do not save the password in the quick connection mode.

### ISSUE THREAD

**Issue by BurmSSS** [1Remote/1Remote#746]
In Quick Connect mode, the program remembers the last login and password, which is not 
good for security. 
There is a problem that the next time you connect via a quick connection, you can view the last password entered.
It would be nice to have a setting to remember the login and password or not.

![image](https://github.com/user-attachments/assets/89e3b9e2-72ea-45f5-bf1b-3879dd4ecb70)

**Comment by majkinetor** [comment]
Why is that a security problem?

**Comment by BurmSSS** [comment]
According to our organization's security policy, passwords cannot be memorized.

**Comment by BurmSSS** [comment]
Since we connect to different clients in our organization, we are not allowed to store connection data. In this regard, it would be nice if IP addresses were not saved during a quick connection.  Since it is probably convenient for other users that the data is saved, this should be done through the settings.

**Comment by majkinetor** [comment]
I see. 

If this is to be done, it should be in the connection settings IMO, as you may want to save latest for some connections and not for others.

**Comment by BurmSSS** [comment]
For saved connections RDP , there is an option “Ask for password when open connect” and it works perfectly. If there was such a setting for Quick Connect, it would be great. And I would also like to have a parameter for the Quick Connect option “Do not save the connection address”

**Comment by VShawn** [comment]
Now we have `remember address` option in the setting and `remember password` option in the popup.

Note `remember password` option shows only when `remember address` option is checked.

![image](https://github.com/user-attachments/assets/c90c5387-8862-4140-95e0-ef4b71a79dfe)

![image](https://github.com/user-attachments/assets/582f5215-875a-4ab4-99a0-9e96ded38685)
