### ISSUE TITLE
组合键（alt+shift、ctrl+shift等）整个程序卡死崩溃

### ISSUE THREAD

**Issue by vanderwals** [1Remote/1Remote#750]
您好，如题
![38660a65410a30e7e3ff29f0fe2286b](https://github.com/user-attachments/assets/89786960-7f77-4c39-ad1a-900d440466a4)

**Comment by vanderwals** [comment]
RDP，均是win10

**Comment by VShawn** [comment]
在开发环境无法复现bug，请提供更多的日志，或屏幕录像，以便定位问题。

P.S. 您提供的日志截图并非是引发bug的原因，这个是在服务器尚未连接完成时调整桌面分辨率会报出的错误，所有用户的RDP连接都会发生这个错误，已经被程序内部处理，不会导致卡死。

![38660a65410a30e7e3ff29f0fe2286b](https://github.com/user-attachments/assets/89786960-7f77-4c39-ad1a-900d440466a4)

**Comment by vanderwals** [comment]
更正一下，发现是我控制端电脑的问题，只有ctrl+alt、shift+alt会卡死。控制端win10。但我更新过系统问题依然存在。
视频链接：

https://github.com/user-attachments/assets/93276f12-1323-47c7-9eeb-541b3922e636


视频中第二次为 shift+alt

版本	Windows 10 专业版
版本号	22H2
安装日期	‎2023/‎10/‎10
操作系统内部版本	19045.5011
体验	Windows Feature Experience Pack 1000.19060.1000.0

**Comment by VShawn** [comment]
感谢你的录屏，但很遗憾我没能分析出卡死的原因，问GPT和搜索社区都没有找到答案。

我个人猜测可能是远程桌面的动态库的兼容性问题，但无法确定，如果你有能力希望你能自己编译本项目用debug模式帮助定位问题，但如果没有C#开发经验的话建议你可以换一个远程工具比如 mRemoteNG，mRemoteNG用的是较老的winfrom开发框架并且它的开发者多，做出的软件兼容性会比这边高。

**Comment by vanderwals** [comment]
![20241107-191722](https://github.com/user-attachments/assets/595b81e5-a91e-4010-b420-3b89ffa4c24b)
尝试了下，发现触发组合按键时，程序卡住，没有任何报错，卡住没法进行任何操作，只能终止运行

**Comment by VShawn** [comment]
那就难整了，说明1Remote的程序就没有故障，应该是在调用的dll中踩到了死循环。首先就怀疑是 MSTSCLib 里面卡死，你可以在卡死的时候点暂停调试按钮，看断点在哪里。

![image](https://github.com/user-attachments/assets/656e347a-323b-47b3-988c-d8601e4583bf)

如果真是在 MSTSCLib 里面，你可以尝试在你本机的 C：\Program Files 或 C:\Windows 里找 AxMSTSCLib.dll MSTSCLib.dll 这两个文件，替换掉 .\1Remote\lib 文件夹里的同名文件再试试。

**Comment by vanderwals** [comment]
作者您好，替换dll文件问题还是存在。您有空看看调试视频，觉得还有什么建议
https://www.bilibili.com/video/BV1nDmmYcEuv/?vd_source=4c54f847b6445922156e94e3d3b8873b

**Comment by VShawn** [comment]
看了视频，没有头绪，从调试过程也看不出是哪里阻塞住了UI线程，建议你先转用其他远程工具比如说 mRemoteNG。

**Comment by VShawn** [comment]
暂无法解决，放入 [Limbo](https://github.com/1Remote/1Remote/milestone/2)
