### ISSUE TITLE
会话连接前的脚本不运行

### ISSUE THREAD

**Issue by wuq5789** [1Remote/1Remote#753]
**Describe the bug**
会话连接前的脚本不运行

**To Reproduce**
1.我要一SSH会话中添加“会话连接前脚本”，内容为ping 127.0.0.1
2. 在1Remonte添加页面测试是正常的。在任务管理器中可以看到ping这个进程
3.但在保存后，，我打开这个SSH会话，查看任务管理器中并没有ping进程在运行

**Expected behavior**
会话运行过程中，任务管理器并无相关脚本的进程。

**Screenshots**
![image](https://github.com/user-attachments/assets/b74b4af3-42d8-4ccd-9c07-f781ab6d957d)

**Desktop (please complete the following information):**
 - OS: win11 企业版
 - PRemoteM Version [e.g. 1.0]

**Additional context**
Add any other context about the problem here.4. 同时我另一个脚本，内容为
5. ssh.exe  -iC:\Users\ROY_xin\OneDrive\PROJECTS\cloudSDP\ssh_cloudSDP -Nf -L 31022:Bhost:22  root@Ahost
6、同样测试正常，但在保存并运行，查看任务管理器中并没有SSH进程在运行

**Comment by VShawn** [comment]
https://github.com/user-attachments/assets/0db1a5f4-419a-461b-be6a-83d4bf32e75a

经测试运行正常。

**Comment by VShawn** [comment]
发现问题了，是相比Win10，Win11中系统的CMD被改成了多标签的终端，于是脚本被执行在终端上，而因此没有被显示出来，实际上脚本是被执行了的。

![image](https://github.com/user-attachments/assets/5403bf50-2e3e-48f1-ae1e-77385f5abdfd)

**Comment by VShawn** [comment]
I think I fixed it


https://github.com/user-attachments/assets/679de829-9cd1-43a9-84fd-0e23668a3f44
