### ISSUE TITLE
全屏时显示滚动条, get scroll bars in full screen mode

### ISSUE THREAD

**Issue by reoLantern** [1Remote/1Remote#754]
全屏连接时，没有正确全屏显示，会显示滚动条。

配置选项：
分辨率：适应窗口大小
客户端屏幕分辨率：2560*1600

使用mstsc.exe全屏连接则没有出现滚动条。

在1Remote中将分辨率修改为【屏幕分辨率】，则会正确全屏，不出现滚动条。只在屏幕分辨率设置为【适应窗口大小】时发生问题。

**Screenshots**
![image](https://github.com/user-attachments/assets/0937d7d2-3adc-4042-bdea-8e9cf4bf91fb)

 - 客户端OS: Win11家庭版
 - 远程桌面主机（被连接端）OS: Win 11 Pro Edu
 - 软件版本：1Remote(Store) 1.0.0 Built at: 2024-09-25T20:35:12.928

**Comment by VShawn** [comment]
能否麻烦你在设置中把日志调为debug

![image](https://github.com/user-attachments/assets/94afb886-1de5-4b90-985f-7d10048a51dd)

然后将【屏幕分辨率】，【适应窗口大小】两种模式都运行一遍

最后把日志文件贴上来。

主要看日志里面这几行在两种模式下的差异

![image](https://github.com/user-attachments/assets/b50f5dff-b184-4e12-841b-b59b37e9ae07)

**Comment by reoLantern** [comment]
这是日志文件，我把ip地址相关的信息用“【】”代替了，应该不影响查看。

先用的适应窗口大小模式（有滚动条），再用的屏幕分辨率模式（无滚动条）。

[1Remote.log_20241110.md](https://github.com/user-attachments/files/17691437/1Remote.log_20241110.md)

**Comment by VShawn** [comment]
```


[T:001][20:43:00.539]	`Debug`		RDP Host: init Display with ScaleFactor = 150, W = 0, H = 0, isReconnecting = False
[T:001][20:43:00.546]	`Debug`		RDP Host: Display init end: RDP.DesktopWidth = 2560, RDP.DesktopHeight = 1600,
[T:001][20:43:03.031]	`Debug`		RDP to FullScreen resize ParentWindow to : W = 1706.66666666667, H = 1066.66666666667, while screen size is 2560 × 1600, ScaleFactor = 150
[T:001][20:43:03.032]	`Debug`		SetRdpResolution needUpdate = True, UpdateSessionDisplaySettings, by: W = 2560 -> 2560, H = 1600 -> 1600, ScaleFactor = 0 -> 150, focus = True






[T:001][20:43:21.739]	`Debug`		RDP Host: init Display with ScaleFactor = 150, W = 0, H = 0, isReconnecting = False
[T:001][20:43:21.739]	`Debug`		RDP Host: Display init end: RDP.DesktopWidth = 2560, RDP.DesktopHeight = 1600,
[T:001][20:43:22.151]	`Debug`		RDP to FullScreen resize ParentWindow to : W = 1706.66666666667, H = 1066.66666666667, while screen size is 2560 × 1600, ScaleFactor = 150
[T:001][20:43:22.152]	`Debug`		SetRdpResolution needUpdate = True, UpdateSessionDisplaySettings, by: W = 2560 -> 2560, H = 1600 -> 1600, ScaleFactor = 0 -> 150, focus = True

```

>> 先用的适应窗口大小模式（有滚动条），再用的屏幕分辨率模式（无滚动条）。

这是你两次连接的日志，可以看到，分辨率设置是一模一样的，然而一个有滚动条一个没有，说明`适应窗口大小模式`设置出的分辨率有问题，比你的桌面稍微大了一丢丢。

目前看只靠日志是分析不出原因了的，我准备去找一台2k分辨率的显示器调到150%缩放尝试复现这个问题。

**Comment by reoLantern** [comment]
感谢。我的屏幕是笔记本电脑自带的分辨率 2560×1600，不是 16:9，不知道是不是这个导致的。另外试了其他几种情况：

1. 系统缩放调整为 125%，显示正常，不会出现滚动条。
2. 外接了一个 2560×1440 的屏幕，做扩展屏，扩展屏缩放为 100%。此时扩展屏显示正常，原屏幕依然会出现滚动条。
3. 扩展屏缩放调整为 150%，依然显示正常，不会出现滚动条。

所以可能和 2560×1600 分辨率、150% 缩放的情况有关？

**Comment by VShawn** [comment]
从目前的测试用例来看，应该是和 `可能和 2560×1600 分辨率、150% 缩放` 情况下，计算出的  W = 1706.66666666667, H = 1066.66666666667 有关。不过我始终不能理解，为什么两种模式下还会有区别：`先用的适应窗口大小模式（有滚动条），再用的屏幕分辨率模式（无滚动条）。`

**Comment by VShawn** [comment]
找了台显示器来，调试后自测通过，问题解决，@reoLantern 劳烦你下载最新的 nightly 版本测试一下。

**Comment by reoLantern** [comment]
nightly版本成功修复了这个问题，感谢！
