### ISSUE TITLE
使用便捷性存在问题

### ISSUE THREAD

**Issue by DoubleH-AT** [1Remote/1Remote#757]
**Is your enhancement related to a problem? Please describe.**
目前快捷键除了ALT+M呼出外，没有其他快捷键的配置说明

**Describe the solution you'd like**
建议提供一个可以自定义快捷键的窗口

**Additional context**
我在使用过程中，还遇到了一下问题，期待着版本更新：
1.在linux用户切换过程中，出现backspace显示^?的问题
2.没有办法切换标签页，在快捷运维中会有很大的问题
3.自定义的runner，案例太少，各种协议常用的软件配置是否都可以提供一个推荐的配置方式，例如：ssh协议中添加SecureCrt时，各种命令行参数的配置
4.列表显示的位置，无法拖拉调节，当小窗口显示时，最后的栏就会被阶段甚至消失
5.是否可以提供一个可选的侧栏，用以显示会话信息，并且能可以树状管理已添加的会话分类
6.会话配置导入，除了json格式外，是否可以考虑兼容xml格式

感谢您的作品，为我的工作提供了很多便捷，以上建议希望对您的创作有帮助

**Comment by VShawn** [comment]
> 目前快捷键除了ALT+M呼出外，没有其他快捷键的配置说明

可现在除了 ALT + M 以外也没有其他可以配置的快捷键了啊，你说的其他快捷键是指。。。？

> 在linux用户切换过程中，出现backspace显示^?的问题 

这个是什么意思？我Linux用的少，不怎么理解，不过大概率是runner也就是Kitty的问题。

> 没有办法切换标签页，在快捷运维中会有很大的问题

以前我有试过做快捷键，但由于焦点在远程桌面上或者焦点在 Runner 进程上，1Remote 进程根本捕获不到快捷键，无法触发切换。之后尝试使用系统全局钩子，被杀毒软件判定为疑似病毒，所以最后切换标签页的快捷键就不了了之了。

> 列表显示的位置，无法拖拉调节，当小窗口显示时，最后的栏就会被阶段甚至消失

这个任务一直挂着呢 #507，改UI实在太烦加上上半年我老去医院没空改。

> 是否可以提供一个可选的侧栏，用以显示会话信息，并且能可以树状管理已添加的会话分类

`侧栏，用以显示会话信息` 具体是要显示什么东西呢？

树状管理参考 #749

> 会话配置导入，除了json格式外，是否可以考虑兼容xml格式

xml 格式是由什么软件导出的？如果有模板其实是可以兼容的。
