### ISSUE TITLE
There is garbage in glossary.csv

### ISSUE THREAD

**Issue by itagagaki** [1Remote/1Remote#759]
There is garbage in glossary.csv
Can we just remove it?

https://github.com/1Remote/1Remote/blob/3c06971548ef52f84c2678a01799ac22e92321ed/Ui/Resources/Languages/glossary.csv?plain=1#L235C1-L270C39

**Comment by VShawn** [comment]
Yes line break is necessary for some text. I once considered using special characters to replace line breaks, but I didn’t adopt this approach as it made usage more cumbersome.

now I prefer https://edit-csv.net, it can handel this csv file well.

![image](https://github.com/user-attachments/assets/aa5c67f6-9020-4df3-9260-1a3b5e83f3b3)

**Comment by itagagaki** [comment]
Ah, okay, I'll try it that way for a while. Thanks for the introduction to the tool. It might be enough, but I'll give it a try it if I come up with another solution.

**Comment by VShawn** [comment]
Hi, since you are the first contributor to completely review the translation process, could you please help add some to the translation README if you have the time?

https://github.com/1Remote/1Remote/blob/main/Ui/Resources/Languages/readme.md

**Comment by itagagaki** [comment]
Sure! I'll write down what I've learned.
