### ISSUE TITLE
作者有没有考虑过增加前置代理，SOCKS5代理之类的

### ISSUE THREAD

**Issue by ice-seal** [1Remote/1Remote#760]
如题，作者有没有考虑过增加前置代理，SOCKS5代理之类的，作用是，比如国外的机器，通过一个线路好的机子搭建代理来拉线路不好的，这样远程就流畅多了

**Comment by VShawn** [comment]
考虑过，问题是我个人没有这样的需求，也没有使用前置代理的经验，所以不懂得如何开发。

**Comment by VShawn** [comment]
如果你有经验和能力，欢迎把功能加上然后PR回来:)
