### ISSUE TITLE
是否可以支持把连接标签页位置更换

### ISSUE THREAD

**Issue by kankanai** [1Remote/1Remote#765]
现在默认是顶部，感觉如果支持放到左侧，放到底部的话更好点，希望可以支持

**Comment by VShawn** [comment]
目前不行，标签页控件是调用第三方的[Dragablz](https://github.com/ButchersBoy/Dragablz)，我没有时间将其改为左侧或底部边栏模式。如果你有需要，可以尝试向Dragablz贡献代码，Dragablz支持配置标签位置后，1Remote 会及时更进更新。
