### ISSUE TITLE
Provide font selection options

### ISSUE THREAD

**Issue by itagagaki** [1Remote/1Remote#772]
I want an option to specify the font used by 1Remote's UI.
The current font 'Microsoft YaHei' also displays Japanese, but the letter shape is probably for simplified Chinese characters and slightly different from the Japanese.

Microsoft YaHei
<img width="36" alt="2024-11-14 12 53 38" src="https://github.com/user-attachments/assets/3f5a523e-9e0e-49bd-8f97-09417807e95e">

Meiryo UI
<img width="36" alt="MeiryoUI" src="https://github.com/user-attachments/assets/baa67651-457a-4269-bb34-a51ff1436920">

Personally, I would be happy to just replace it with Meiryo UI. But it would be nice if users could choose the font of their choice.

**Comment by VShawn** [comment]
![image](https://github.com/user-attachments/assets/cd430e59-181c-4f7c-a2b6-93e37a01369a)


font selection feature is rolling smoothly

**Comment by itagagaki** [comment]
Super!!
