### ISSUE TITLE
"Close All" button isn't working right.

### ISSUE THREAD

**Issue by ndd200** [1Remote/1Remote#775]
问题：右上角关闭按钮失效。

复现步骤（必现）：
1.打开两个以上的远程连接。
2.右上角点“全部关闭”按钮。
3.弹出的确认对话框选“取消”。
4.右上角的“关闭”和“全部关闭”按钮，点击后没有反应。

 - OS: Win11
 - PRemoteM Version 1.0.0 Built at 2024-09-05

**Comment by VShawn** [comment]
thx for the report, I close the ticket now.
