### ISSUE TITLE
“地址可用性检测”不支持IPv6域名或地址

### ISSUE THREAD

**Issue by ndd200** [1Remote/1Remote#776]
问题：“地址可用性检测”不支持IPv6域名或地址。

复现步骤（必现）：
1.新建一个RDP连接（SSH/VNC等估计也一样，但我没有试过）。
2.“连接地址”填写一个IPv6的域名或地址。
3.勾选“连接前检测地址是否可用”选项。
4.保存后，连接此地址，通不过连接检测，导致连接失败。
5.关闭“地址可用性检测”后，可以正常连接IPv6域名或地址。

OS: Win11
PRemoteM Version 1.0.0 Built at 2024-09-05

**Comment by ndd200** [comment]
抱歉，才看到这是已知问题，我重复提交了。

**Comment by VShawn** [comment]
nightly 版本中已经修改了检测方法，但我没有ipv6的测试环境，你可以帮试试。
