### ISSUE TITLE
Labels of buttons in a dialog box

### ISSUE THREAD

**Issue by itagagaki** [1Remote/1Remote#778]
I think Yes(, please) / No(, thank you) is a more appropriate option for this question than OK/Cancel.

![image](https://github.com/user-attachments/assets/f14f3aa6-2c1c-42d7-b85b-fa8f8b630a99)

**Comment by VShawn** [comment]
This is a generic dialog box, and I was being lazy, so didn't give them proper button names :), we can refacing when the time is right.
