### ISSUE TITLE
Icons quality

### ISSUE THREAD

**Issue by kata32** [1Remote/1Remote#781]
This project is great, but I find that connections icon quality is poor. I've created 512x1512 custom icons but when imported they are on very low quality and transparency of png images is not fully supported.

**Comment by majkinetor** [comment]
Not only quality but also a selection - there are  no generic images only logos.

**Comment by VShawn** [comment]
The image picker do needs a refactor. CURRENTLY Imported image will be compressed to 144*144 resolution.
