### ISSUE TITLE
I want to know how to turn off the desktop background in Microsoft Remote Desktop Configuration

### ISSUE THREAD

**Issue by skczhans** [1Remote/1Remote#784]
I occasionally use the built-in remote desktop client, which has some options that I think consume a lot of data. How can I enable these options in 1Remote?
![image](https://github.com/user-attachments/assets/c885c92b-126b-4d9f-a164-b37d5a55d7d7)
@VShawn

**Comment by VShawn** [comment]
This option allows you to turn off all features to improve data transmission

![image](https://github.com/user-attachments/assets/dc4593bb-f520-4be2-b52f-2ef72fa67869)
