### ISSUE TITLE
KiTTY session file selection dialog does not appear

### ISSUE THREAD

**Issue by itagagaki** [1Remote/1Remote#787]
It jumps to `ButtonSelectSessionConfigFile_OnClick` when the Select button is pressed, but is skipped by `if (DataContext is IKittyConnectable pc)`.

**Comment by itagagaki** [comment]
Another issue, but possibly related to this one

The following elements of SshFormView.xaml do not appear to be visible

```
                        <TextBlock Style="{StaticResource EditorRowGridTitle}" Text=""></TextBlock>
                        <TextBlock Style="{StaticResource TextBlockBase}" Text="{DynamicResource 'Supports the OpenSSH format key and Putty-key with WinSCP.'}" Opacity="0.7"></TextBlock>
```

**Comment by VShawn** [comment]
Thanks for testing, another bug caused by refactoring
