### ISSUE TITLE
Add option to "always open in new window"

### ISSUE THREAD

**Issue by odaniel9** [1Remote/1Remote#790]
Please consider adding a configuration option to always open in a new window. It's a nice to have where some connections can default to opening in their own window based on user preference.

Additionally it would also be nice to have the placement of that connection's window persist between uses.

**Comment by VShawn** [comment]
do it later

**Comment by VShawn** [comment]
a checkbox has been added to every protocol to set `"always open in new window"`

however ` placement of that connection's window persist between uses` was not approved due to breaking changes in the setting file.

**Comment by odaniel9** [comment]
Thank you.

Much appreciated!
