### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Cbyto** [1Remote/1Remote#793]
[1Remote_ErrorReport_20241130092950.md](https://github.com/user-attachments/files/17967446/1Remote_ErrorReport_20241130092950.md)
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Win10 Pro 2004]
 - PRemoteM Version [e.g. 0.4.6.20071234]

**Additional context**

**Comment by VShawn** [comment]
Thx reporting, Fixed https://github.com/1Remote/1Remote/issues/693
