### ISSUE TITLE
Dialog appears every time we edit a single letter in the path of the exe

### ISSUE THREAD

**Issue by itagagaki** [1Remote/1Remote#794]
In the App settings, when I try to edit the folder path after specifying an exe that has preset parameters that differ from the current parameter list in the "Exe path" field with drive name and/or folder path, a dialog pops up every time I edit a single character and interferes with the editing process.

I can't think of a solution, but I report it as a minor issue for now.

https://github.com/user-attachments/assets/3675377a-e221-4c51-b69b-b5abdb259e94

**Comment by VShawn** [comment]
I will make it triggered only after the edit loss focus, maybe better.
