### ISSUE TITLE
Unable to resize (make smaller) the RDP window

### ISSUE THREAD

**Issue by dbczynski** [1Remote/1Remote#797]
**Describe the bug**
Whenever I try to manually make an RDP connection window bigger by dragging the edges or the corners, it snaps back after dragging the length of more than a couple pixels. You can only make it bigger by resizing by ~10 pixels at a time.
Resizing to make it smaller works as intended (but do so carefully, as resizing it back is a pain).
The main window and other connection types don't have this issue. Display>Resolution settings don't make a difference. Resizing using shortcuts (such as snapping the window to the display's edge) works without issue.

**To Reproduce**
1. Connect to any RDP using 1Remote.
2. Click and hold on an edge or a corner of the connection window.
3a. Drag it outwards at a normal speed - the edge will move a couple pixels but then it'll snap back to its previous position (leaving the mouse cursor outside the window) 
3b. Drag it outwards slowly - the edge will move a couple pixels, then the window contents will adjust. You can release the button to "set" the new position or drag it outwards a couple pixels more. Whenever you drag too quickly the edge will snap back to its previous "set" position.

**Screenshots**
![opera_5ito3wzAFY](https://github.com/user-attachments/assets/ce33dcef-2b80-4725-bab6-b60bfd63bdcd)

**Desktop (please complete the following information):**
 - OS: Win10 Pro 22H2
 - 1Remote Version1.0.1-alpha (from Choco)

**Additional context**
Couldn't reproduce the issue on Windows 11

**Comment by VShawn** [comment]
The functional buttons may not be displayed due to the RDP connection events not receiving a response, which is clearly problematic.

![image](https://github.com/user-attachments/assets/09633c90-5e44-4b5b-838f-5edec9fad322)

1. So After reconnecting or switching to a different server, do the buttons in the above image still not appear?
2. Please provide the log files to help with analysis.

**Comment by itagagaki** [comment]
I don't think it's the reported problem that the functional buttons are not being showing up.
(This is a separate issue as it is also a glitch).

The reported problem was reproduced on my Windows 10.
Please watch this video.
Note that I am holding down the left mouse button on the edge of the window and dragging it to the side without releasing it. However, the window stopped expanding halfway. And then it went back to the width it was before I dragged it. Sometimes it works, sometimes it fails. As the npreviously report said, it seems to be related to the dragging speed, but this is not always the case.

https://github.com/user-attachments/assets/3c7457f2-5fb7-4d32-a275-4532d9d16129

And after repeating this test, Explorer stopped working for a while. I then confirmed that 1Remote had frozen (hung up).
This happened to me several times.

**Comment by VShawn** [comment]
Here I used a timer to determine if the dragging is completed. Perhaps there is an issue with the logic of this timer. I need to have enough time to review this part of the code.

**Comment by dbczynski** [comment]
> The functional buttons may not be displayed due to the RDP connection events not receiving a response, which is clearly problematic.
> 
> ![image](https://private-user-images.githubusercontent.com/10143738/392187815-09633c90-5e44-4b5b-838f-5edec9fad322.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM0MzU1MzQsIm5iZiI6MTczMzQzNTIzNCwicGF0aCI6Ii8xMDE0MzczOC8zOTIxODc4MTUtMDk2MzNjOTAtNWU0NC00YjViLTgzOGYtNWVkZWM5ZmFkMzIyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA1VDIxNDcxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEzOTYxY2ZjOGVkM2VmNjNmZTg4MWE1NGQ4ZTliOTRiNWFjZjE1MDBkOGY2YmY3YzIxMjI2YjE2OTM4YWQ3MzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Wb4UmpgCZN0F49PkSeM-HdzxdAwaoZlx1Kx0f2oiw6E)
> 
>     1. So After reconnecting or switching to a different server, do the buttons in the above image still not appear?
> 
Oh, the buttons do display correctly. I just have them on the left side.

**Comment by VShawn** [comment]
By downloading historical versions of the APP, I finally find out that the bug sourced from feature #648. I will reopen #648 until the bug is fixed.

**Comment by majkinetor** [comment]
It doesn't happen to me. Resizing works OK. If I move very hard, sometimes remote desktop isn't resized correctly to match the new windows size (but rarely). Here is the screen (ignore skew):

![image](https://github.com/user-attachments/assets/d4a09774-11ce-4729-a9e7-c4f82edcbaf2)
