### ISSUE TITLE
Deleting tags in the ‘Tags’ tab causes inconsistencies in the display

### ISSUE THREAD

**Issue by itagagaki** [1Remote/1Remote#798]
After deleting a tag in the "Tags" tab, it is displayed as if it had not been deleted.

**To Reproduce**
1. View the "All" tab and switch to List view
2. Add a tag to a new or existing server
3. Switch to the "Tags" tab
4. Right-click on a tag and select Delete from the context menu. Answer [Yes] to the dialog
5. BUG: It switches the view to the “All” tab
6. BUG: The tag remains in the list view in the "All" tab, although it should have been deleted
7. BUG: The “Tags” tab remains even if the tag you deleted was the last one
8. Switch to the "Tags" tab
9. BUG: The tag does not disappear, it stays there
10. Switch to the "All" tab and edit the server that had the tag
11. The tag does not exist in the editor (maybe expected)

Commit 3bba8dd8ac2f09c28e9a8a974416f9375bc40f3d

**Comment by VShawn** [comment]
I see 
The tag has been deleted from the database, but view hasn't reloaded the data somehow.
