### ISSUE TITLE
上传下载便利性

### ISSUE THREAD

**Issue by ouyang7923** [1Remote/1Remote#806]
![2](https://github.com/user-attachments/assets/a5ca5777-d83e-498b-b1b2-a400644cfa91)

1. 上传进度区域，随着上传文件增多，高度越来越高，还无法调节，挤占上方区域空间。
2. 下载功能，建议直接拖拉下载，上传本来就已经支持拖拉。右键 保存为不方便

**Comment by VShawn** [comment]
拖拽感觉不好用，我给每行加上了下载按钮，应该能改善体验，下载列表加上了限高和加上滚动条。 在nightly 版本中可以体验。
