### ISSUE TITLE
主题切换无法即时预览

### ISSUE THREAD

**Issue by ouyang7923** [1Remote/1Remote#809]
![image](https://github.com/user-attachments/assets/0aac16ad-8017-4981-ad49-8cbd6c7093b7)
如图，切换主题后，已打开窗口是不会变化的。只能新打开窗口才能看到效果。虽然可以打开
![image](https://github.com/user-attachments/assets/53c5f32c-f70c-488d-968b-34d64317a3be)
网页预览， 还是挺让人晕乎的，选了不合适的主题又要反复再切换。方便实现即时预览是不是会更好。

**Comment by VShawn** [comment]
由于软件机制所限，无法做到实时的 SSH 主题切换。因为 1Remote 打开 SSH 时实际是启动了 KiTTY 的进程，而这个进程无法实时切换主题。但后续有个改进方向，即在网页预览中提供截图作为主题预览，等我有空再做吧。
